__This notebook loads synthetic browsing histories and shows extended samples per history per country__

In [1]:
!pip install -r requirements.txt --disable-pip-version-check | tail -n 2

Requirement already satisfied: tzdata>=2022.7 in /home/komosny/Dokumenty/01_develop/__PYTHON-312/lib64/python3.12/site-packages (from pandas==2.2.3->-r requirements.txt (line 1)) (2024.2)
Requirement already satisfied: six>=1.5 in /home/komosny/Dokumenty/01_develop/__PYTHON-312/lib64/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 1)) (1.16.0)

In [2]:
import os
import pandas as pd

# Load dataset

In [3]:
history_country = os.listdir('synthetic-browsing-history')

In [4]:
history = pd.DataFrame()

for country in history_country:

    print(country, end=' ')
    
    history_files = os.listdir(os.path.join('synthetic-browsing-history', country))

    for file in history_files:

        file_data = pd.read_csv(os.path.join('synthetic-browsing-history', country, file))

        file_data['history_name'] = file

        file_data['history_country'] = country
    
        history = pd.concat([file_data,history],ignore_index=True,copy=False)

history['history_number'] = history.history_name.apply(lambda x: x.split('_')[1].split('.')[0])

history.history_number = history.history_number.astype('int8')

history.columns

Argentina Australia Austria Belgium Brazil Bulgaria Canada Chile Croatia Czechia Denmark Egypt Estonia Finland France Germany Greece Hungary India Ireland Israel Italy Japan Latvia Lithuania Malaysia Mexico Morocco Netherlands New_Zealand Norway Pakistan Poland Portugal Romania Saudi_Arabia Serbia Singapore Slovakia Slovenia Spain Sri_Lanka Sweden Switzerland Thailand Turkiye Ukraine United_Kingdom United_States Viet_Nam

Index(['synthetic_time', 'synthetic_url', 'original_scope', 'original_content',
       'original_country_rank', 'original_world_rank', 'original_lang',
       'original_path_bin', 'history_name', 'history_country',
       'history_number'],
      dtype='object')

# Extended samples

In [5]:
groups = history.groupby(['history_country','history_number'])[['synthetic_time','synthetic_url']]

In [6]:
pd.set_option('display.max_colwidth', None)

In [7]:
for history, group in groups:
    
    print(f'{history[0]}, history number {history[1]}')
    
    print('Last 5 records')
    
    display(group.tail(5))

Argentina, history number 0
Last 5 records

,synthetic_time,synthetic_url
308787,2024-11-30 12:51:44.160972,https://ejemplos.net/ejemplos-de-totem/
308788,2024-11-30 13:37:22.135059,https://www.samsung.com/hk_en/support/model/ef-zg99pcbegew/
308789,2024-11-30 14:48:29.335401,https://subway.com
308790,2024-11-30 14:48:52.419779,https://ultimate-guitar.com
308791,2024-11-30 22:27:22.352179,https://eleconomista.es

Argentina, history number 1
Last 5 records

,synthetic_time,synthetic_url
308169,2024-11-30 11:26:02.293755,https://ejemplos.net/tipos-de-e-learning-2/
308170,2024-11-30 12:12:27.510709,https://unsplash.com/photos/a-close-up-of-some-bamboo-prulk09dyho
308171,2024-11-30 13:23:34.711051,https://subway.com
308172,2024-11-30 13:23:57.795429,https://ultimate-guitar.com
308173,2024-11-30 21:02:27.727829,https://lavanguardia.com

Argentina, history number 2
Last 5 records

,synthetic_time,synthetic_url
307554,2024-11-30 12:29:36.335189,https://ejemplos.net/via-crucis/
307555,2024-11-30 13:15:14.309276,https://www.samsung.com/levant/support/model/lc32jg52qquxen/
307556,2024-11-30 14:26:21.509618,https://capgemini.com
307557,2024-11-30 14:26:44.593996,https://abebooks.com
307558,2024-11-30 22:05:14.526396,https://redbull.com

Argentina, history number 3
Last 5 records

,synthetic_time,synthetic_url
306937,2024-11-30 13:04:35.592017,https://ejemplos.net/4-ejemplos-de-prosa/
306938,2024-11-30 13:51:00.808971,https://unsplash.com/photos/cactus-potted-plant-uoo0iklxpb8
306939,2024-11-30 15:02:08.009313,https://capgemini.com
306940,2024-11-30 15:02:31.093691,https://abebooks.com
306941,2024-11-30 22:41:01.026091,https://radiocut.fm

Argentina, history number 4
Last 5 records

,synthetic_time,synthetic_url
306315,2024-11-30 13:31:51.235249,https://ejemplos.net/4-ejemplos-de-prosa/
306316,2024-11-30 14:17:29.209336,https://www.samsung.com/latin_en/support/model/qn65qn85bafxza/
306317,2024-11-30 15:28:36.409678,https://capgemini.com
306318,2024-11-30 15:28:59.494056,https://abebooks.com
306319,2024-11-30 23:07:29.426456,https://elconfidencial.com

Argentina, history number 5
Last 5 records

,synthetic_time,synthetic_url
305699,2024-11-30 12:17:24.977146,https://ejemplos.net/tipos-de-analogias/
305700,2024-11-30 13:03:02.951233,https://www.samsung.com/levant/support/model/lc32jg52qquxen/
305701,2024-11-30 14:14:10.151575,https://capgemini.com
305702,2024-11-30 14:14:33.235953,https://abebooks.com
305703,2024-11-30 21:53:03.168353,https://eleconomista.es

Argentina, history number 6
Last 5 records

,synthetic_time,synthetic_url
305077,2024-11-30 11:39:12.686330,https://ejemplos.net/via-crucis/
305078,2024-11-30 12:24:50.660417,https://unsplash.com/photos/cactus-potted-plant-uoo0iklxpb8
305079,2024-11-30 13:35:57.860759,https://capgemini.com
305080,2024-11-30 13:36:20.945137,https://abebooks.com
305081,2024-11-30 21:14:50.877537,https://lavozdegalicia.es

Argentina, history number 7
Last 5 records

,synthetic_time,synthetic_url
304458,2024-11-30 13:32:13.075447,https://ejemplos.net/tipos-de-mesociclos/
304459,2024-11-30 14:17:51.049534,https://www.samsung.com/ae_ar/support/model/sm-j105hzwddkr/
304460,2024-11-30 15:28:58.249876,https://shell.com
304461,2024-11-30 15:29:21.334254,https://ultimate-guitar.com
304462,2024-11-30 23:07:51.266654,https://20minutos.es

Argentina, history number 8
Last 5 records

,synthetic_time,synthetic_url
303837,2024-11-30 12:46:36.664174,https://ejemplos.net/tipos-de-sensores/
303838,2024-11-30 13:32:14.638261,https://www.samsung.com/hk_en/support/model/ef-zg99pcbegew/
303839,2024-11-30 14:43:21.838603,https://capgemini.com
303840,2024-11-30 14:43:44.922981,https://ultimate-guitar.com
303841,2024-11-30 22:22:14.855381,https://eldiario.es

Argentina, history number 9
Last 5 records

,synthetic_time,synthetic_url
303224,2024-11-30 11:53:46.315522,https://ejemplos.net/4-ejemplos-de-prosa/
303225,2024-11-30 12:39:24.289609,https://www.samsung.com/ae_ar/support/model/sm-j105hzwddkr/
303226,2024-11-30 13:50:31.489951,https://subway.com
303227,2024-11-30 13:50:54.574329,https://abebooks.com
303228,2024-11-30 21:29:24.506729,https://latercera.com

Australia, history number 0
Last 5 records

,synthetic_time,synthetic_url
302601,2024-11-30 12:15:32.186398,https://www.sacredheartmission.org/op-shops/mission-mates/
302602,2024-11-30 13:01:57.403352,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
302603,2024-11-30 14:13:04.603694,https://inverse.com
302604,2024-11-30 14:13:27.688072,https://billabong.com
302605,2024-11-30 21:51:57.620472,https://hellomagazine.com

Australia, history number 1
Last 5 records

,synthetic_time,synthetic_url
301975,2024-11-30 12:57:03.571315,https://www.sacredheartmission.org/op-shops/mission-mates/
301976,2024-11-30 13:42:41.545402,https://stackexchange.com/users/8442750/unknown-user
301977,2024-11-30 14:53:48.745744,https://petmd.com
301978,2024-11-30 14:54:11.830122,https://billabong.com
301979,2024-11-30 22:32:41.762522,https://allevents.in

Australia, history number 2
Last 5 records

,synthetic_time,synthetic_url
301351,2024-11-30 13:32:21.078083,https://www.sacredheartmission.org/contact-us/
301352,2024-11-30 14:17:59.052170,https://stackexchange.com/users/17066786/oliwia-stam
301353,2024-11-30 15:29:06.252512,https://bp.com
301354,2024-11-30 15:29:29.336890,https://billabong.com
301355,2024-11-30 23:07:59.269290,https://allevents.in

Australia, history number 3
Last 5 records

,synthetic_time,synthetic_url
300726,2024-11-30 12:40:39.022429,https://www.sacredheartmission.org/contact-us/
300727,2024-11-30 13:27:04.239383,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
300728,2024-11-30 14:38:11.439725,https://bp.com
300729,2024-11-30 14:38:34.524103,https://billabong.com
300730,2024-11-30 22:17:04.456503,https://sportingnews.com

Australia, history number 4
Last 5 records

,synthetic_time,synthetic_url
300095,2024-11-30 12:57:46.415767,https://www.sacredheartmission.org/author/sarthur/
300096,2024-11-30 13:43:24.389854,https://stackexchange.com/users/8442750/unknown-user
300097,2024-11-30 14:54:31.590196,https://petmd.com
300098,2024-11-30 14:54:54.674574,https://billabong.com
300099,2024-11-30 22:33:24.606974,https://goal.com

Australia, history number 5
Last 5 records

,synthetic_time,synthetic_url
299470,2024-11-30 12:18:27.207305,https://www.sacredheartmission.org/author/sarthur/
299471,2024-11-30 13:04:05.181392,https://stackexchange.com/users/30047207/alrey-john
299472,2024-11-30 14:15:12.381734,https://jamieoliver.com
299473,2024-11-30 14:15:35.466112,https://billabong.com
299474,2024-11-30 21:54:05.398512,https://hellomagazine.com

Australia, history number 6
Last 5 records

,synthetic_time,synthetic_url
298842,2024-11-30 13:27:59.074593,https://www.sacredheartmission.org/op-shops/mission-mates/
298843,2024-11-30 14:13:37.048680,https://stackexchange.com/users/28516911/zodwa-sigutya
298844,2024-11-30 15:24:44.249022,https://jamieoliver.com
298845,2024-11-30 15:25:07.333400,https://billabong.com
298846,2024-11-30 23:03:37.265800,https://csiro.au

Australia, history number 7
Last 5 records

,synthetic_time,synthetic_url
298219,2024-11-30 12:42:24.056654,https://www.sacredheartmission.org/contact-us/
298220,2024-11-30 13:28:02.030741,https://stackexchange.com/users/5455775/ryuakamatsu
298221,2024-11-30 14:39:09.231083,https://bp.com
298222,2024-11-30 14:39:32.315461,https://billabong.com
298223,2024-11-30 22:18:02.247861,https://hellomagazine.com

Australia, history number 8
Last 5 records

,synthetic_time,synthetic_url
297590,2024-11-30 12:21:10.449369,https://www.sacredheartmission.org/contact-us/
297591,2024-11-30 13:06:48.423456,https://stackexchange.com/users/15979638/plantgeek519
297592,2024-11-30 14:17:55.623798,https://bp.com
297593,2024-11-30 14:18:18.708176,https://billabong.com
297594,2024-11-30 21:56:48.640576,https://radiotimes.com

Australia, history number 9
Last 5 records

,synthetic_time,synthetic_url
296965,2024-11-30 11:59:09.449822,https://www.sacredheartmission.org/author/sarthur/
296966,2024-11-30 12:44:47.423909,https://stackexchange.com/users/29946/marcobazzani
296967,2024-11-30 13:55:54.624251,https://draxe.com
296968,2024-11-30 13:56:17.708629,https://billabong.com
296969,2024-11-30 21:34:47.641029,https://hellomagazine.com

Austria, history number 0
Last 5 records

,synthetic_time,synthetic_url
296339,2024-11-30 13:33:36.503680,https://www.kapuzinergruft.com/habsburger
296340,2024-11-30 14:19:14.477767,https://www.britannica.com/place/limerick-county-ireland
296341,2024-11-30 15:30:21.678109,https://tu-chemnitz.de
296342,2024-11-30 15:30:44.762487,https://abebooks.com
296343,2024-11-30 23:09:14.694887,https://spektrum.de

Austria, history number 1
Last 5 records

,synthetic_time,synthetic_url
295711,2024-11-30 12:33:16.883585,https://learnattack.de/deutsch/kommasetzung
295712,2024-11-30 13:18:54.857672,https://www.britannica.com/topic/thus-spake-zarathustra
295713,2024-11-30 14:30:02.058014,https://motor1.com
295714,2024-11-30 14:30:25.142392,https://www.wattpad.com/
295715,2024-11-30 22:08:55.074792,https://srf.ch

Austria, history number 2
Last 5 records

,synthetic_time,synthetic_url
295078,2024-11-30 12:49:24.794499,https://www.lexisnexis.at/autor/katja-unger/
295079,2024-11-30 13:35:02.768586,https://www.britannica.com/biography/salif-keita-malian-athlete
295080,2024-11-30 14:46:09.968928,https://motor1.com
295081,2024-11-30 14:46:33.053306,https://www.wattpad.com/
295082,2024-11-30 22:25:02.985706,https://wdr.de

Austria, history number 3
Last 5 records

,synthetic_time,synthetic_url
294449,2024-11-30 12:21:29.216068,https://www.lexisnexis.at/2885506-2/
294450,2024-11-30 13:07:07.190155,https://www.britannica.com/topic/thus-spake-zarathustra
294451,2024-11-30 14:18:14.390497,https://tu-chemnitz.de
294452,2024-11-30 14:18:37.474875,https://wattpad.com
294453,2024-11-30 21:57:07.407275,https://businessinsider.de

Austria, history number 4
Last 5 records

,synthetic_time,synthetic_url
293825,2024-11-30 13:05:07.836286,https://www.lexisnexis.at/2885506-2/
293826,2024-11-30 13:50:45.810373,https://www.britannica.com/biography/salif-keita-malian-athlete
293827,2024-11-30 15:01:53.010715,https://motor1.com
293828,2024-11-30 15:02:16.095093,https://deviantart.com
293829,2024-11-30 22:40:46.027493,https://krone.at

Austria, history number 5
Last 5 records

,synthetic_time,synthetic_url
293202,2024-11-30 13:30:16.578939,https://www.lexisnexis.at/autor/marian-wakounig/
293203,2024-11-30 14:15:54.553026,https://www.britannica.com/place/thar-desert/additional-info
293204,2024-11-30 15:27:01.753368,https://tu-chemnitz.de
293205,2024-11-30 15:27:24.837746,https://songtell.com
293206,2024-11-30 23:05:54.770146,https://windfinder.com

Austria, history number 6
Last 5 records

,synthetic_time,synthetic_url
292573,2024-11-30 13:28:16.476674,https://www.lexisnexis.at/autor/marian-wakounig/
292574,2024-11-30 14:14:41.693628,https://www.britannica.com/science/summer-solstice-astronomy
292575,2024-11-30 15:25:48.893970,https://motor1.com
292576,2024-11-30 15:26:11.978348,https://songtell.com
292577,2024-11-30 23:04:41.910748,https://kleinezeitung.at

Austria, history number 7
Last 5 records

,synthetic_time,synthetic_url
291940,2024-11-30 13:30:52.676625,https://www.lexisnexis.at/2885506-2/
291941,2024-11-30 14:16:30.650712,https://www.britannica.com/science/pharyngeal-pouch
291942,2024-11-30 15:27:37.851054,https://tu-chemnitz.de
291943,2024-11-30 15:28:00.935432,https://songtell.com
291944,2024-11-30 23:06:30.867832,https://srf.ch

Austria, history number 8
Last 5 records

,synthetic_time,synthetic_url
291311,2024-11-30 12:12:50.722205,https://www.lexisnexis.at/sa_author/pfalz-thomas/
291312,2024-11-30 12:58:28.696292,https://www.britannica.com/topic/senate-united-states-government
291313,2024-11-30 14:09:35.896634,https://tu-chemnitz.de
291314,2024-11-30 14:09:58.981012,https://www.wattpad.com/
291315,2024-11-30 21:48:28.913412,https://krone.at

Austria, history number 9
Last 5 records

,synthetic_time,synthetic_url
290681,2024-11-30 13:22:38.823279,https://www.lexisnexis.at/sa_author/pfalz-thomas/
290682,2024-11-30 14:08:16.797366,https://www.britannica.com/biography/michal-schwartz
290683,2024-11-30 15:19:23.997708,https://motor1.com
290684,2024-11-30 15:19:47.082086,https://deviantart.com
290685,2024-11-30 22:58:17.014486,https://br.de

Belgium, history number 0
Last 5 records

,synthetic_time,synthetic_url
290056,2024-11-30 11:58:49.100056,https://www.overijse.be/bouwlijn
290057,2024-11-30 12:44:27.074143,https://stackoverflow.com/users/633802/mattypants?tab=profile
290058,2024-11-30 13:55:34.274485,https://oxfordreference.com
290059,2024-11-30 13:55:57.358863,https://jiosaavn.com
290060,2024-11-30 21:34:27.291263,https://europe1.fr

Belgium, history number 1
Last 5 records

,synthetic_time,synthetic_url
289432,2024-11-30 11:24:46.310162,https://www.schilde.be/actueel
289433,2024-11-30 12:10:24.284249,https://stackoverflow.com/users/4953216/kevin-hammet
289434,2024-11-30 13:21:31.484591,https://gamesradar.com
289435,2024-11-30 13:21:54.568969,https://jiosaavn.com
289436,2024-11-30 21:00:24.501369,https://linternaute.com

Belgium, history number 2
Last 5 records

,synthetic_time,synthetic_url
288805,2024-11-30 12:26:58.830925,https://www.aarschot.be/cambio-autodelen
288806,2024-11-30 13:12:36.805012,https://stackoverflow.com/users/1723823/ternarytopiary?tab=articles
288807,2024-11-30 14:23:44.005354,https://shell.com
288808,2024-11-30 14:24:07.089732,https://jiosaavn.com
288809,2024-11-30 22:02:37.022132,https://europe1.fr

Belgium, history number 3
Last 5 records

,synthetic_time,synthetic_url
288183,2024-11-30 11:46:51.164192,https://www.overijse.be/onze-acties
288184,2024-11-30 12:32:29.138279,https://stackoverflow.com/users/3864926/bret-van-putten
288185,2024-11-30 13:43:36.338621,https://gamesradar.com
288186,2024-11-30 13:43:59.422999,https://jiosaavn.com
288187,2024-11-30 21:22:29.355399,https://futura-sciences.com

Belgium, history number 4
Last 5 records

,synthetic_time,synthetic_url
287558,2024-11-30 13:04:32.092553,https://www.overijse.be/bouwlijn
287559,2024-11-30 13:50:10.066640,https://stackoverflow.com/users/3864926/bret-van-putten
287560,2024-11-30 15:01:17.266982,https://oxfordreference.com
287561,2024-11-30 15:01:40.351360,https://jiosaavn.com
287562,2024-11-30 22:40:10.283760,https://nos.nl

Belgium, history number 5
Last 5 records

,synthetic_time,synthetic_url
286927,2024-11-30 11:31:56.587558,https://www.schilde.be/vakantiewerking
286928,2024-11-30 12:17:34.561645,https://stackoverflow.com/users/633802/mattypants?tab=profile
286929,2024-11-30 13:28:41.761987,https://oxfordreference.com
286930,2024-11-30 13:29:04.846365,https://jiosaavn.com
286931,2024-11-30 21:07:34.778765,https://nos.nl

Belgium, history number 6
Last 5 records

,synthetic_time,synthetic_url
286294,2024-11-30 12:50:30.583202,https://www.schilde.be/deadlines-uit-kalender
286295,2024-11-30 13:36:08.557289,https://stackoverflow.com/users/1786873/leonardo-allievi?tab=tags
286296,2024-11-30 14:47:15.757631,https://oxfordreference.com
286297,2024-11-30 14:47:38.842009,https://jiosaavn.com
286298,2024-11-30 22:26:08.774409,https://nos.nl

Belgium, history number 7
Last 5 records

,synthetic_time,synthetic_url
285679,2024-11-30 11:41:11.291909,https://www.woluwe1200.be/enquetes-publiques/
285680,2024-11-30 12:26:49.265996,https://stackoverflow.com/users/12323550/kristen?tab=tags
285681,2024-11-30 13:37:56.466338,https://shell.com
285682,2024-11-30 13:38:19.550716,https://jiosaavn.com
285683,2024-11-30 21:16:49.483116,https://futura-sciences.com

Belgium, history number 8
Last 5 records

,synthetic_time,synthetic_url
285060,2024-11-30 13:36:33.320504,https://www.schilde.be/alle-activiteiten
285061,2024-11-30 14:22:11.294591,https://stackoverflow.com/help/badges/6/supporter?userid=14602915
285062,2024-11-30 15:33:18.494933,https://gamesradar.com
285063,2024-11-30 15:33:41.579311,https://jiosaavn.com
285064,2024-11-30 23:12:11.511711,https://futura-sciences.com

Belgium, history number 9
Last 5 records

,synthetic_time,synthetic_url
284425,2024-11-30 12:05:43.971623,https://www.schilde.be/maak-een-afspraak
284426,2024-11-30 12:51:21.945710,https://stackoverflow.com/users/4953216/kevin-hammet
284427,2024-11-30 14:02:29.146052,https://shell.com
284428,2024-11-30 14:02:52.230430,https://jiosaavn.com
284429,2024-11-30 21:41:22.162830,https://linternaute.com

Brazil, history number 0
Last 5 records

,synthetic_time,synthetic_url
283798,2024-11-30 12:56:18.263132,https://www.universal.org/noticias/
283799,2024-11-30 13:41:56.237219,https://stackoverflow.com/users/1601638/we-b-martians?tab=articles
283800,2024-11-30 14:53:03.437561,https://agoda.com
283801,2024-11-30 14:53:26.521939,https://redbubble.com
283802,2024-11-30 22:31:56.454339,https://tiktok.com

Brazil, history number 1
Last 5 records

,synthetic_time,synthetic_url
283176,2024-11-30 11:31:02.176739,http://www.urca.br/prpgp/resolucoes/
283177,2024-11-30 12:16:40.150826,https://stackoverflow.com/users/1723823/ternarytopiary?tab=articles
283178,2024-11-30 13:27:47.351168,https://rome2rio.com
283179,2024-11-30 13:28:10.435546,https://alamy.com
283180,2024-11-30 21:06:40.367946,https://tiktok.com

Brazil, history number 2
Last 5 records

,synthetic_time,synthetic_url
282568,2024-11-30 11:57:32.258631,https://www.suapesquisa.com/economia/dolar.htm
282569,2024-11-30 12:43:10.232718,https://stackoverflow.com/users/1601638/we-b-martians?tab=articles
282570,2024-11-30 13:54:17.433060,https://rome2rio.com
282571,2024-11-30 13:54:40.517438,https://metacritic.com
282572,2024-11-30 21:33:10.449838,https://tiktok.com

Brazil, history number 3
Last 5 records

,synthetic_time,synthetic_url
281970,2024-11-30 12:06:28.820554,https://www.suapesquisa.com/o_que_e/monarquia.htm
281971,2024-11-30 12:52:06.794641,https://www.canva.com/tr_tr/help/using-blackboard-lms/
281972,2024-11-30 14:03:13.994983,https://rome2rio.com
281973,2024-11-30 14:03:37.079361,https://metacritic.com
281974,2024-11-30 21:42:07.011761,https://tiktok.com

Brazil, history number 4
Last 5 records

,synthetic_time,synthetic_url
281363,2024-11-30 13:05:58.034236,https://www.suapesquisa.com/economia/dolar.htm
281364,2024-11-30 13:51:36.008323,https://stackoverflow.com/users/1601638/we-b-martians?tab=articles
281365,2024-11-30 15:02:43.208665,https://rome2rio.com
281366,2024-11-30 15:03:06.293043,https://alamy.com
281367,2024-11-30 22:41:36.225443,https://tiktok.com

Brazil, history number 5
Last 5 records

,synthetic_time,synthetic_url
280744,2024-11-30 12:45:43.233121,http://www.urca.br/ceua/
280745,2024-11-30 13:31:21.207208,https://www.canva.com/es_mx/plantillas/s/catalogos/
280746,2024-11-30 14:42:28.407550,https://rome2rio.com
280747,2024-11-30 14:42:51.491928,https://metacritic.com
280748,2024-11-30 22:21:21.424328,https://tiktok.com

Brazil, history number 6
Last 5 records

,synthetic_time,synthetic_url
280132,2024-11-30 13:29:47.212895,https://www.suapesquisa.com/economia/dolar.htm
280133,2024-11-30 14:15:25.186982,https://www.canva.com/ar_eg/graphs/flowcharts/
280134,2024-11-30 15:26:32.387324,https://rome2rio.com
280135,2024-11-30 15:26:55.471702,https://redbubble.com
280136,2024-11-30 23:05:25.404102,https://tiktok.com

Brazil, history number 7
Last 5 records

,synthetic_time,synthetic_url
279520,2024-11-30 13:08:10.648229,http://www.urca.br/prpgp/resolucoes/
279521,2024-11-30 13:53:48.622316,https://stackoverflow.com/users/1272950/y%c7%9ds%ca%9e%c7%9dla
279522,2024-11-30 15:04:55.822658,https://rome2rio.com
279523,2024-11-30 15:05:18.907036,https://metacritic.com
279524,2024-11-30 22:43:48.839436,https://tiktok.com

Brazil, history number 8
Last 5 records

,synthetic_time,synthetic_url
278899,2024-11-30 12:12:10.047672,https://www.suapesquisa.com/o_que_e/monarquia.htm
278900,2024-11-30 12:57:48.021759,https://www.canva.com/it_it/biglietti/modelli/invito/
278901,2024-11-30 14:08:55.222101,https://agoda.com
278902,2024-11-30 14:09:18.306479,https://metacritic.com
278903,2024-11-30 21:47:48.238879,https://tiktok.com

Brazil, history number 9
Last 5 records

,synthetic_time,synthetic_url
278286,2024-11-30 12:37:04.070773,https://www.suapesquisa.com/o_que_e/feudo.htm
278287,2024-11-30 13:22:42.044860,https://www.britannica.com/science/pharyngeal-pouch
278288,2024-11-30 14:33:49.245202,https://agoda.com
278289,2024-11-30 14:34:12.329580,https://metacritic.com
278290,2024-11-30 22:12:42.261980,https://tiktok.com

Bulgaria, history number 0
Last 5 records

,synthetic_time,synthetic_url
277673,2024-11-30 11:59:08.048999,https://www.visitplovdiv.com/en
277674,2024-11-30 12:44:46.023086,https://www.ciela.net/svobodna-zona-normativi?page=5
277675,2024-11-30 13:55:53.223428,https://byjus.com
277676,2024-11-30 13:56:16.307806,https://genius.com
277677,2024-11-30 21:34:46.240206,https://24chasa.bg

Bulgaria, history number 1
Last 5 records

,synthetic_time,synthetic_url
277033,2024-11-30 12:00:54.808741,https://www.visitplovdiv.com/en
277034,2024-11-30 12:46:32.782828,https://www.ciela.net/svobodna-zona-normativi/category/85784/?page=3
277035,2024-11-30 13:57:39.983170,https://shell.com
277036,2024-11-30 13:58:03.067548,https://genius.com
277037,2024-11-30 21:36:32.999948,https://24chasa.bg

Bulgaria, history number 2
Last 5 records

,synthetic_time,synthetic_url
276401,2024-11-30 12:12:02.643618,https://www.visitplovdiv.com/en
276402,2024-11-30 12:57:40.617705,https://dela.bg/acts/2df66c97-0bce-477f-aa57-be8f210b59f6
276403,2024-11-30 14:08:47.818047,https://loccitane.com
276404,2024-11-30 14:09:10.902425,https://target.com
276405,2024-11-30 21:47:40.834825,https://24chasa.bg

Bulgaria, history number 3
Last 5 records

,synthetic_time,synthetic_url
275768,2024-11-30 11:45:24.993569,https://www.visitplovdiv.com/en
275769,2024-11-30 12:31:50.210523,https://dela.bg/acts/2df66c97-0bce-477f-aa57-be8f210b59f6
275770,2024-11-30 13:42:57.410865,https://jooble.org
275771,2024-11-30 13:43:20.495243,https://genius.com
275772,2024-11-30 21:21:50.427643,https://24chasa.bg

Bulgaria, history number 4
Last 5 records

,synthetic_time,synthetic_url
275131,2024-11-30 13:32:29.664603,http://www.visitplovdiv.com/en
275132,2024-11-30 14:18:54.881557,https://dela.bg/acts/b6055900-bd85-4ef1-b172-3dad31ed7543
275133,2024-11-30 15:30:02.081899,https://www.loccitane.com/
275134,2024-11-30 15:30:25.166277,https://genius.com
275135,2024-11-30 23:08:55.098677,https://24chasa.bg

Bulgaria, history number 5
Last 5 records

,synthetic_time,synthetic_url
274502,2024-11-30 11:25:12.501433,https://www.aop.bg/index2.php?page_id=803
274503,2024-11-30 12:10:50.475520,https://dela.bg/acts/bf708c72-239a-47e4-8412-28a1813da704
274504,2024-11-30 13:21:57.675862,https://www.loccitane.com/
274505,2024-11-30 13:22:20.760240,https://genius.com
274506,2024-11-30 21:00:50.692640,https://24chasa.bg

Bulgaria, history number 6
Last 5 records

,synthetic_time,synthetic_url
273876,2024-11-30 11:25:14.595244,http://www.visitplovdiv.com/en
273877,2024-11-30 12:10:52.569331,https://dela.bg/acts/2df66c97-0bce-477f-aa57-be8f210b59f6
273878,2024-11-30 13:21:59.769673,https://www.loccitane.com/
273879,2024-11-30 13:22:22.854051,https://target.com
273880,2024-11-30 21:00:52.786451,https://24chasa.bg

Bulgaria, history number 7
Last 5 records

,synthetic_time,synthetic_url
273243,2024-11-30 13:27:46.616680,http://www.visitplovdiv.com/en
273244,2024-11-30 14:13:24.590767,https://dela.bg/acts/e688eaf9-e509-433e-a9db-b33f25edff23
273245,2024-11-30 15:24:31.791109,https://www.loccitane.com/
273246,2024-11-30 15:24:54.875487,https://genius.com
273247,2024-11-30 23:03:24.807887,https://24chasa.bg

Bulgaria, history number 8
Last 5 records

,synthetic_time,synthetic_url
272606,2024-11-30 12:34:28.812124,https://www.visitplovdiv.com/en
272607,2024-11-30 13:20:06.786211,https://dela.bg/acts/b8c3813f-f8fe-4fdf-baf9-68d21c63b02d
272608,2024-11-30 14:31:13.986553,https://byjus.com
272609,2024-11-30 14:31:37.070931,https://genius.com
272610,2024-11-30 22:10:07.003331,https://24chasa.bg

Bulgaria, history number 9
Last 5 records

,synthetic_time,synthetic_url
271980,2024-11-30 11:49:18.072496,http://www.visitplovdiv.com/en
271981,2024-11-30 12:34:56.046583,https://dela.bg/acts/bf708c72-239a-47e4-8412-28a1813da704
271982,2024-11-30 13:46:03.246925,https://www.loccitane.com/
271983,2024-11-30 13:46:26.331303,https://target.com
271984,2024-11-30 21:24:56.263703,https://24chasa.bg

Canada, history number 0
Last 5 records

,synthetic_time,synthetic_url
271341,2024-11-30 13:22:28.534904,https://www.cochrane.ca/?aid=861&page=0
271342,2024-11-30 14:08:06.508991,https://www.canva.com/photos/mac6dldh0oa-abdominal-massage/
271343,2024-11-30 15:19:13.709333,https://stylecraze.com
271344,2024-11-30 15:19:36.793711,https://long-mcquade.com
271345,2024-11-30 22:58:06.726111,https://allevents.in

Canada, history number 1
Last 5 records

,synthetic_time,synthetic_url
270701,2024-11-30 12:40:56.072790,https://www.cochrane.ca/?aid=862&page=2
270702,2024-11-30 13:26:34.046877,https://www.techtarget.com/contributor/alex-scroxton/page/14
270703,2024-11-30 14:37:41.247219,https://umanitoba.ca
270704,2024-11-30 14:38:04.331597,https://bedbathandbeyond.ca
270705,2024-11-30 22:16:34.263997,https://sportsnet.ca

Canada, history number 2
Last 5 records

,synthetic_time,synthetic_url
270057,2024-11-30 11:30:31.848535,https://www.rexall.ca/articles/conditions/p
270058,2024-11-30 12:16:09.822622,https://www.techradar.com/phones/motorola-phones/page/8
270059,2024-11-30 13:27:17.022964,https://investing.com
270060,2024-11-30 13:27:40.107342,https://www.gapcanada.ca/
270061,2024-11-30 21:06:10.039742,https://allevents.in

Canada, history number 3
Last 5 records

,synthetic_time,synthetic_url
269420,2024-11-30 13:04:37.070912,https://www.cochrane.ca/?aid=782&page=5
269421,2024-11-30 13:50:15.044999,https://mashable.com/deals/july-27-theragun-pro
269422,2024-11-30 15:01:22.245341,https://jooble.org
269423,2024-11-30 15:01:45.329719,https://long-mcquade.com
269424,2024-11-30 22:40:15.262119,https://sportsnet.ca

Canada, history number 4
Last 5 records

,synthetic_time,synthetic_url
268782,2024-11-30 12:18:18.089920,https://www.taoist.org/stress-relief/
268783,2024-11-30 13:03:56.064007,https://mashable.com/article/kendrick-lamar-wins-pulitzer-prize-damn
268784,2024-11-30 14:15:03.264349,https://torontomu.ca
268785,2024-11-30 14:15:26.348727,https://www.gapcanada.ca/
268786,2024-11-30 21:53:56.281127,https://timesnownews.com

Canada, history number 5
Last 5 records

,synthetic_time,synthetic_url
268140,2024-11-30 13:30:12.648075,https://www.abbotsford.ca/emergencyguides
268141,2024-11-30 14:15:50.622162,https://mashable.com/deals/july-27-pop-up-camp-cabin
268142,2024-11-30 15:26:57.822504,https://investing.com
268143,2024-11-30 15:27:20.906882,https://www.gapcanada.ca/
268144,2024-11-30 23:05:50.839282,https://allevents.in

Canada, history number 6
Last 5 records

,synthetic_time,synthetic_url
267500,2024-11-30 12:38:12.115570,https://www.rexall.ca/probiotics-and-fibre
267501,2024-11-30 13:23:50.089657,https://www.canva.com/es_mx/plantillas/s/catalogos/
267502,2024-11-30 14:34:57.289999,https://uvic.ca
267503,2024-11-30 14:35:20.374377,https://bedbathandbeyond.ca
267504,2024-11-30 22:13:50.306777,https://sportsnet.ca

Canada, history number 7
Last 5 records

,synthetic_time,synthetic_url
266863,2024-11-30 11:47:04.934231,https://www.chatham-kent.ca/aghof/pages/about.aspx
266864,2024-11-30 12:32:42.908318,https://mashable.com/article/dell-latitude-rugged-2018-line
266865,2024-11-30 13:43:50.108660,https://aafp.org
266866,2024-11-30 13:44:13.193038,https://bedbathandbeyond.ca
266867,2024-11-30 21:22:43.125438,https://nbcsports.com

Canada, history number 8
Last 5 records

,synthetic_time,synthetic_url
266228,2024-11-30 13:17:37.322179,https://www.cochrane.ca/?aid=870&page=1
266229,2024-11-30 14:03:15.296266,https://www.techtarget.com/contributor/warwick-ashford/page/16
266230,2024-11-30 15:14:22.496608,https://purewow.com
266231,2024-11-30 15:14:45.580986,https://secondhandsongs.com
266232,2024-11-30 22:53:15.513386,https://timesnownews.com

Canada, history number 9
Last 5 records

,synthetic_time,synthetic_url
265599,2024-11-30 11:42:15.161982,https://www.brant.ca/modules/news/en?page=28
265600,2024-11-30 12:27:53.136069,https://www.canva.com/es_es/plantillas/s/bacterias/
265601,2024-11-30 13:39:00.336411,https://queensu.ca
265602,2024-11-30 13:39:23.420789,https://secondhandsongs.com
265603,2024-11-30 21:17:53.353189,https://timesnownews.com

Chile, history number 0
Last 5 records

,synthetic_time,synthetic_url
264957,2024-11-30 12:59:49.155248,https://wom.cl/equipos/wom-go/
264958,2024-11-30 13:45:27.129335,https://www.britannica.com/topic/thus-spake-zarathustra
264959,2024-11-30 14:56:34.329677,https://agoda.com
264960,2024-11-30 14:56:57.414055,https://shazam.com
264961,2024-11-30 22:35:27.346455,https://eldiario.es

Chile, history number 1
Last 5 records

,synthetic_time,synthetic_url
264326,2024-11-30 12:24:12.868081,https://ejemplos.net/tipos-de-e-learning-2/
264327,2024-11-30 13:09:50.842168,https://www.britannica.com/biography/frank-morgan-american-actor
264328,2024-11-30 14:20:58.042510,https://agoda.com
264329,2024-11-30 14:21:21.126888,https://audible.com
264330,2024-11-30 21:59:51.059288,https://latercera.com

Chile, history number 2
Last 5 records

,synthetic_time,synthetic_url
263696,2024-11-30 12:57:36.910322,https://ejemplos.net/ejemplos-de-totem/
263697,2024-11-30 13:43:14.884409,https://www.britannica.com/place/thar-desert/additional-info
263698,2024-11-30 14:54:22.084751,https://agoda.com
263699,2024-11-30 14:54:45.169129,https://shazam.com
263700,2024-11-30 22:33:15.101529,https://cadenaser.com

Chile, history number 3
Last 5 records

,synthetic_time,synthetic_url
263071,2024-11-30 12:29:35.076256,https://ejemplos.net/tipos-de-mesociclos/
263072,2024-11-30 13:15:13.050343,https://www.britannica.com/topic/genesis-british-rock-group
263073,2024-11-30 14:26:20.250685,https://agoda.com
263074,2024-11-30 14:26:43.335063,https://shazam.com
263075,2024-11-30 22:05:13.267463,https://perfil.com

Chile, history number 4
Last 5 records

,synthetic_time,synthetic_url
262440,2024-11-30 13:20:59.391524,https://www.upla.cl/institutotecnologico/
262441,2024-11-30 14:06:37.365611,https://www.britannica.com/topic/senate-united-states-government
262442,2024-11-30 15:17:44.565953,https://agoda.com
262443,2024-11-30 15:18:07.650331,https://shazam.com
262444,2024-11-30 22:56:37.582731,https://infobae.com

Chile, history number 5
Last 5 records

,synthetic_time,synthetic_url
261812,2024-11-30 11:54:17.744000,https://www.upla.cl/noticias/?p=156922
261813,2024-11-30 12:39:55.718087,https://www.britannica.com/biography/michal-schwartz
261814,2024-11-30 13:51:02.918429,https://agoda.com
261815,2024-11-30 13:51:26.002807,https://shazam.com
261816,2024-11-30 21:29:55.935207,https://redbull.com

Chile, history number 6
Last 5 records

,synthetic_time,synthetic_url
261187,2024-11-30 11:54:04.965962,https://www.upla.cl/noticias/?p=174071
261188,2024-11-30 12:39:42.940049,https://www.britannica.com/topic/thus-spake-zarathustra
261189,2024-11-30 13:50:50.140391,https://agoda.com
261190,2024-11-30 13:51:13.224769,https://audible.com
261191,2024-11-30 21:29:43.157169,https://cadenaser.com

Chile, history number 7
Last 5 records

,synthetic_time,synthetic_url
260565,2024-11-30 11:56:49.015455,https://www.upla.cl/institutotecnologico/
260566,2024-11-30 12:42:26.989542,https://www.britannica.com/science/summer-solstice-astronomy
260567,2024-11-30 13:53:34.189884,https://agoda.com
260568,2024-11-30 13:53:57.274262,https://audible.com
260569,2024-11-30 21:32:27.206662,https://redbull.com

Chile, history number 8
Last 5 records

,synthetic_time,synthetic_url
259947,2024-11-30 12:17:12.797782,https://www.upla.cl/noticias/page/2884/
259948,2024-11-30 13:02:50.771869,https://www.britannica.com/place/limerick-county-ireland
259949,2024-11-30 14:13:57.972211,https://agoda.com
259950,2024-11-30 14:14:21.056589,https://shazam.com
259951,2024-11-30 21:52:50.988989,https://elconfidencial.com

Chile, history number 9
Last 5 records

,synthetic_time,synthetic_url
259322,2024-11-30 12:24:49.759029,https://ejemplos.net/ejemplos-de-totem/
259323,2024-11-30 13:10:27.733116,https://www.britannica.com/biography/michal-schwartz
259324,2024-11-30 14:21:34.933458,https://agoda.com
259325,2024-11-30 14:21:58.017836,https://shazam.com
259326,2024-11-30 22:00:27.950236,https://perfil.com

Croatia, history number 0
Last 5 records

,synthetic_time,synthetic_url
258705,2024-11-30 13:31:17.059118,https://www.prijatelji-zivotinja.hr/index.hr.php?id=226
258706,2024-11-30 14:16:55.033205,https://github.com/pypi/linehaul-cloud-function
258707,2024-11-30 15:28:02.233547,https://gamesradar.com
258708,2024-11-30 15:28:25.317925,https://jiosaavn.com
258709,2024-11-30 23:06:55.250325,https://index.hr

Croatia, history number 1
Last 5 records

,synthetic_time,synthetic_url
258095,2024-11-30 13:24:02.951287,https://www.prijatelji-zivotinja.hr/index.hr.php?id=1304
258096,2024-11-30 14:09:40.925374,https://github.com/ascoderu/lokole/pull/105
258097,2024-11-30 15:20:48.125716,https://gamesradar.com
258098,2024-11-30 15:21:11.210094,https://jiosaavn.com
258099,2024-11-30 22:59:41.142494,https://index.hr

Croatia, history number 2
Last 5 records

,synthetic_time,synthetic_url
257477,2024-11-30 11:25:48.461072,https://www.prijatelji-zivotinja.hr/index.en.php?id=2350
257478,2024-11-30 12:11:26.435159,https://github.com/battlesnakeofficial/rules
257479,2024-11-30 13:22:33.635501,https://kayak.com
257480,2024-11-30 13:22:56.719879,https://jiosaavn.com
257481,2024-11-30 21:01:26.652279,https://index.hr

Croatia, history number 3
Last 5 records

,synthetic_time,synthetic_url
256871,2024-11-30 13:17:02.128522,https://www.prijatelji-zivotinja.hr/index.hr.php?id=3711
256872,2024-11-30 14:02:40.102609,https://github.com/battlesnakeofficial/rules
256873,2024-11-30 15:13:47.302951,https://gamesradar.com
256874,2024-11-30 15:14:10.387329,https://jiosaavn.com
256875,2024-11-30 22:52:40.319729,https://index.hr

Croatia, history number 4
Last 5 records

,synthetic_time,synthetic_url
256263,2024-11-30 11:28:02.125368,https://www.prijatelji-zivotinja.hr/index.hr.php?id=1738
256264,2024-11-30 12:13:40.099455,https://github.com/m417z/global-inject-demo
256265,2024-11-30 13:24:47.299797,https://gamesradar.com
256266,2024-11-30 13:25:10.384175,https://jiosaavn.com
256267,2024-11-30 21:03:40.316575,https://index.hr

Croatia, history number 5
Last 5 records

,synthetic_time,synthetic_url
255655,2024-11-30 11:24:51.608144,https://www.rab.hr/novosti/
255656,2024-11-30 12:10:29.582231,https://github.com/pypi/linehaul-cloud-function
255657,2024-11-30 13:21:36.782573,https://kayak.com
255658,2024-11-30 13:21:59.866951,https://jiosaavn.com
255659,2024-11-30 21:00:29.799351,https://index.hr

Croatia, history number 6
Last 5 records

,synthetic_time,synthetic_url
255045,2024-11-30 11:25:13.689195,https://www.prijatelji-zivotinja.hr/index.hr.php?id=2015g
255046,2024-11-30 12:10:51.663282,https://github.com/ascoderu/lokole/pull/105
255047,2024-11-30 13:21:58.863624,https://gamesradar.com
255048,2024-11-30 13:22:21.948002,https://jiosaavn.com
255049,2024-11-30 21:00:51.880402,https://index.hr

Croatia, history number 7
Last 5 records

,synthetic_time,synthetic_url
254432,2024-11-30 13:32:53.794838,https://www.prijatelji-zivotinja.hr/index.hr.php?id=1304
254433,2024-11-30 14:18:31.768925,https://github.com/ropod-project/ropod_experiment_executor
254434,2024-11-30 15:29:38.969267,https://gamesradar.com
254435,2024-11-30 15:30:02.053645,https://jiosaavn.com
254436,2024-11-30 23:08:31.986045,https://index.hr

Croatia, history number 8
Last 5 records

,synthetic_time,synthetic_url
253830,2024-11-30 12:45:45.019000,https://prijatelji-zivotinja.hr/index.hr.php?id=4309
253831,2024-11-30 13:31:22.993087,https://github.com/sylvaingml/swift-sgitkeyboardlistener
253832,2024-11-30 14:42:30.193429,https://kayak.com
253833,2024-11-30 14:42:53.277807,https://jiosaavn.com
253834,2024-11-30 22:21:23.210207,https://index.hr

Croatia, history number 9
Last 5 records

,synthetic_time,synthetic_url
253219,2024-11-30 12:16:28.831618,https://www.prijatelji-zivotinja.hr/index.en.php?id=2350
253220,2024-11-30 13:02:06.805705,https://github.com/sylvaingml/swift-sgitkeyboardlistener
253221,2024-11-30 14:13:14.006047,https://kayak.com
253222,2024-11-30 14:13:37.090425,https://jiosaavn.com
253223,2024-11-30 21:52:07.022825,https://index.hr

Czechia, history number 0
Last 5 records

,synthetic_time,synthetic_url
252601,2024-11-30 13:17:34.519178,https://www.cojeco.cz/pantelej-joidanov-zarev
252602,2024-11-30 14:03:12.493265,https://www.policie.cz/informace-2020.aspx?q=y3bpptey
252603,2024-11-30 15:14:19.693607,https://healthline.com
252604,2024-11-30 15:14:42.777985,https://flyingtiger.com
252605,2024-11-30 22:53:12.710385,https://heureka.cz

Czechia, history number 1
Last 5 records

,synthetic_time,synthetic_url
251977,2024-11-30 11:29:01.232940,https://www.cojeco.cz/poruchy-osobnosti
251978,2024-11-30 12:14:39.207027,https://www.policie.cz/clanek/informace-pro-obeti-trestnych-cinu.aspx
251979,2024-11-30 13:25:46.407369,https://timeout.com
251980,2024-11-30 13:26:09.491747,https://flyingtiger.com
251981,2024-11-30 21:04:39.424147,https://heureka.cz

Czechia, history number 2
Last 5 records

,synthetic_time,synthetic_url
251361,2024-11-30 12:49:53.876669,https://www.cojeco.cz/dav-1
251362,2024-11-30 13:35:31.850756,https://www.policie.cz/clanek/informace-pro-obeti-trestnych-cinu.aspx
251363,2024-11-30 14:46:39.051098,https://timeout.com
251364,2024-11-30 14:47:02.135476,https://flyingtiger.com
251365,2024-11-30 22:25:32.067876,https://heureka.cz

Czechia, history number 3
Last 5 records

,synthetic_time,synthetic_url
250734,2024-11-30 12:02:01.001439,https://www.cojeco.cz/mezinarodni-den-deti
250735,2024-11-30 12:47:38.975526,https://www.hlidacstatu.cz/hledatsmlouvy?q=ico:25145444
250736,2024-11-30 13:58:46.175868,https://timeout.com
250737,2024-11-30 13:59:09.260246,https://flyingtiger.com
250738,2024-11-30 21:37:39.192646,https://heureka.cz

Czechia, history number 4
Last 5 records

,synthetic_time,synthetic_url
250126,2024-11-30 11:47:35.590615,https://www.cojeco.cz/hieros-gamos
250127,2024-11-30 12:33:13.564702,https://www.o2.cz/osobni/internet/ostrava/radvanice-a-bartovice
250128,2024-11-30 13:44:20.765044,https://healthline.com
250129,2024-11-30 13:44:43.849422,https://flyingtiger.com
250130,2024-11-30 21:23:13.781822,https://heureka.cz

Czechia, history number 5
Last 5 records

,synthetic_time,synthetic_url
249508,2024-11-30 13:12:28.759972,https://www.cojeco.cz/blog/mse-uhli
249509,2024-11-30 13:58:06.734059,https://www.o2.cz/osobni/internet/brno/brno-cernovice
249510,2024-11-30 15:09:13.934401,https://healthline.com
249511,2024-11-30 15:09:37.018779,https://flyingtiger.com
249512,2024-11-30 22:48:06.951179,https://heureka.cz

Czechia, history number 6
Last 5 records

,synthetic_time,synthetic_url
248878,2024-11-30 12:38:04.376816,https://www.cojeco.cz/muchomurka
248879,2024-11-30 13:23:42.350903,https://www.finmag.cz/obchodni-rejstrik/27827071-crystal-spring-a-s
248880,2024-11-30 14:34:49.551245,https://healthline.com
248881,2024-11-30 14:35:12.635623,https://flyingtiger.com
248882,2024-11-30 22:13:42.568023,https://heureka.cz

Czechia, history number 7
Last 5 records

,synthetic_time,synthetic_url
248263,2024-11-30 13:02:11.684489,https://www.cojeco.cz/gramicidin
248264,2024-11-30 13:47:49.658576,https://www.finmag.cz/obchodni-rejstrik/29239648-iq-heat-s-r-o
248265,2024-11-30 14:58:56.858918,https://healthline.com
248266,2024-11-30 14:59:19.943296,https://flyingtiger.com
248267,2024-11-30 22:37:49.875696,https://heureka.cz

Czechia, history number 8
Last 5 records

,synthetic_time,synthetic_url
247647,2024-11-30 12:58:56.400088,https://www.cojeco.cz/hieros-gamos
247648,2024-11-30 13:44:34.374175,https://www.mistopisy.cz/pruvodce/obec/14264/lhota-veselka/
247649,2024-11-30 14:55:41.574517,https://timeout.com
247650,2024-11-30 14:56:04.658895,https://flyingtiger.com
247651,2024-11-30 22:34:34.591295,https://heureka.cz

Czechia, history number 9
Last 5 records

,synthetic_time,synthetic_url
247031,2024-11-30 12:27:49.258637,https://www.cojeco.cz/cladosporium
247032,2024-11-30 13:13:27.232724,https://www.finmag.cz/obchodni-rejstrik/ares/10799826-marketa-kreckova
247033,2024-11-30 14:24:34.433066,https://timeout.com
247034,2024-11-30 14:24:57.517444,https://flyingtiger.com
247035,2024-11-30 22:03:27.449844,https://heureka.cz

Denmark, history number 0
Last 5 records

,synthetic_time,synthetic_url
246407,2024-11-30 12:56:35.866443,https://htk.dk/borger
246408,2024-11-30 13:42:13.840530,https://www.regionh.dk/kraeftvaerketappen/sider/default.aspx
246409,2024-11-30 14:53:21.040872,https://wise.com
246410,2024-11-30 14:53:44.125250,https://looper.com
246411,2024-11-30 22:32:14.057650,https://distractify.com

Denmark, history number 1
Last 5 records

,synthetic_time,synthetic_url
245768,2024-11-30 11:39:49.161720,https://htk.dk/politik/valg
245769,2024-11-30 12:25:27.135807,https://www.regionh.dk/til-fagfolk/sider/default.aspx
245770,2024-11-30 13:36:34.336149,https://kayak.com
245771,2024-11-30 13:36:57.420527,https://famousbirthdays.com
245772,2024-11-30 21:15:27.352927,https://distractify.com

Denmark, history number 2
Last 5 records

,synthetic_time,synthetic_url
245135,2024-11-30 11:45:51.119553,https://ballerup.dk/nyheder/borger
245136,2024-11-30 12:31:29.093640,https://www.regionh.dk/politik/nye-moeder/sider/m%c3%b8de-i-sun.aspx
245137,2024-11-30 13:42:36.293982,https://wise.com
245138,2024-11-30 13:42:59.378360,https://famousbirthdays.com
245139,2024-11-30 21:21:29.310760,https://distractify.com

Denmark, history number 3
Last 5 records

,synthetic_time,synthetic_url
244506,2024-11-30 11:57:51.318923,https://sl.dk/bornholm/
244507,2024-11-30 12:43:29.293010,https://www.regionh.dk/til-fagfolk/sider/default.aspx
244508,2024-11-30 13:54:36.493352,https://oxfordreference.com
244509,2024-11-30 13:54:59.577730,https://famousbirthdays.com
244510,2024-11-30 21:33:29.510130,https://distractify.com

Denmark, history number 4
Last 5 records

,synthetic_time,synthetic_url
243877,2024-11-30 13:34:14.895883,https://ballerup.dk/nyheder/borger?page=2
243878,2024-11-30 14:19:52.869970,https://www.regionh.dk/politik/nye-moeder/sider/m%c3%b8de-i-sun.aspx
243879,2024-11-30 15:31:00.070312,https://shell.com
243880,2024-11-30 15:31:23.154690,https://famousbirthdays.com
243881,2024-11-30 23:09:53.087090,https://usmagazine.com

Denmark, history number 5
Last 5 records

,synthetic_time,synthetic_url
243240,2024-11-30 11:49:54.756953,https://www.htk.dk/politik/valg/valgsteder
243241,2024-11-30 12:35:32.731040,https://www.regionh.dk/kraeftvaerketappen/sider/default.aspx
243242,2024-11-30 13:46:39.931382,https://oxfordreference.com
243243,2024-11-30 13:47:03.015760,https://looper.com
243244,2024-11-30 21:25:32.948160,https://usmagazine.com

Denmark, history number 6
Last 5 records

,synthetic_time,synthetic_url
242611,2024-11-30 12:28:32.431310,https://sl.dk/storkoebenhavn/
242612,2024-11-30 13:14:10.405397,https://www.regionh.dk/klima-og-miljoe/sider/default.aspx
242613,2024-11-30 14:25:17.605739,https://oxfordreference.com
242614,2024-11-30 14:25:40.690117,https://looper.com
242615,2024-11-30 22:04:10.622517,https://distractify.com

Denmark, history number 7
Last 5 records

,synthetic_time,synthetic_url
241984,2024-11-30 12:46:53.952433,https://ballerup.dk/nyheder/borger?page=2
241985,2024-11-30 13:32:31.926520,https://www.regionh.dk/politik/nye-moeder/sider/m%c3%b8de-i-sun.aspx
241986,2024-11-30 14:43:39.126862,https://wise.com
241987,2024-11-30 14:44:02.211240,https://looper.com
241988,2024-11-30 22:22:32.143640,https://usmagazine.com

Denmark, history number 8
Last 5 records

,synthetic_time,synthetic_url
241362,2024-11-30 12:41:00.413221,https://www.svendborg.dk/kommunen/aktindsigt
241363,2024-11-30 13:26:38.387308,https://www.regionh.dk/politik/nye-moeder/sider/m%c3%b8de-i-sun.aspx
241364,2024-11-30 14:37:45.587650,https://hardrock.com
241365,2024-11-30 14:38:08.672028,https://famousbirthdays.com
241366,2024-11-30 22:16:38.604428,https://distractify.com

Denmark, history number 9
Last 5 records

,synthetic_time,synthetic_url
240728,2024-11-30 12:54:11.212156,https://ballerup.dk/fjernvarme
240729,2024-11-30 13:39:49.186243,https://www.regionh.dk/til-fagfolk/sider/default.aspx
240730,2024-11-30 14:50:56.386585,https://kayak.com
240731,2024-11-30 14:51:19.470963,https://looper.com
240732,2024-11-30 22:29:49.403363,https://usmagazine.com

Egypt, history number 0
Last 5 records

,synthetic_time,synthetic_url
240099,2024-11-30 13:35:37.832208,https://zyda.com/terms-of-service
240100,2024-11-30 14:21:15.806295,https://www.techtarget.com/contributor/andrew-howard
240101,2024-11-30 15:32:23.006637,https://everydayhealth.com
240102,2024-11-30 15:32:46.091015,https://www.nefertiti-eg.com/
240103,2024-11-30 23:11:16.023415,https://www.thenationalnews.com

Egypt, history number 1
Last 5 records

,synthetic_time,synthetic_url
239522,2024-11-30 12:33:49.732518,https://zyda.com/products/engage
239523,2024-11-30 13:19:27.706605,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
239524,2024-11-30 14:30:34.906947,https://everydayhealth.com
239525,2024-11-30 14:30:57.991325,https://shellegypt.com
239526,2024-11-30 22:09:27.923725,https://zawya.com

Egypt, history number 2
Last 5 records

,synthetic_time,synthetic_url
238942,2024-11-30 12:08:45.208206,https://zyda.com/pricing
238943,2024-11-30 12:54:23.182293,https://www.techtarget.com/contributor/andrew-howard
238944,2024-11-30 14:05:30.382635,https://everydayhealth.com
238945,2024-11-30 14:05:53.467013,https://alrifaiarabia.com
238946,2024-11-30 21:44:23.399413,https://aljazeera.net

Egypt, history number 3
Last 5 records

,synthetic_time,synthetic_url
238367,2024-11-30 12:36:08.158310,https://www.shopify.com/case-studies/larroude
238368,2024-11-30 13:23:18.613800,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
238369,2024-11-30 14:34:25.814142,https://everydayhealth.com
238370,2024-11-30 14:34:48.898520,https://shellegypt.com
238371,2024-11-30 22:13:18.830920,https://radiotimes.com

Egypt, history number 4
Last 5 records

,synthetic_time,synthetic_url
237794,2024-11-30 12:30:45.009780,https://zyda.com/terms-of-service
237795,2024-11-30 13:16:22.983867,https://www.techtarget.com/news/?news_date=2022-12-11
237796,2024-11-30 14:27:30.184209,https://everydayhealth.com
237797,2024-11-30 14:27:53.268587,https://diwanegypt.com
237798,2024-11-30 22:06:23.200987,https://radiotimes.com

Egypt, history number 5
Last 5 records

,synthetic_time,synthetic_url
237223,2024-11-30 12:10:36.743507,https://zyda.com/get-started
237224,2024-11-30 12:56:14.717594,https://unsplash.com/photos/a-close-up-of-some-bamboo-prulk09dyho
237225,2024-11-30 14:07:21.917936,https://everydayhealth.com
237226,2024-11-30 14:07:45.002314,https://petsoffice.com
237227,2024-11-30 21:46:14.934714,https://radiotimes.com

Egypt, history number 6
Last 5 records

,synthetic_time,synthetic_url
236638,2024-11-30 11:51:10.005270,https://zyda.com/privacy-policy
236639,2024-11-30 12:37:35.222224,https://www.digitaltrends.com/home/homes-with-secret-passages/
236640,2024-11-30 13:48:42.422566,https://everydayhealth.com
236641,2024-11-30 13:49:05.506944,https://gourmetegypt.com
236642,2024-11-30 21:27:35.439344,https://www.thenationalnews.com

Egypt, history number 7
Last 5 records

,synthetic_time,synthetic_url
236067,2024-11-30 13:36:50.617456,https://www.simplilearn.com/bootcamps
236068,2024-11-30 14:22:28.591543,https://www.samsung.com/latin_en/support/model/qn65qn85bafxza/
236069,2024-11-30 15:33:35.791885,https://everydayhealth.com
236070,2024-11-30 15:33:58.876263,https://alrifaiarabia.com
236071,2024-11-30 23:12:28.808663,https://zawya.com

Egypt, history number 8
Last 5 records

,synthetic_time,synthetic_url
235491,2024-11-30 13:23:41.698983,https://www.simplilearn.com/bootcamps
235492,2024-11-30 14:09:19.673070,https://www.techtarget.com/news/?news_date=2022-12-11
235493,2024-11-30 15:20:26.873412,https://everydayhealth.com
235494,2024-11-30 15:20:49.957790,https://nefertiti-eg.com
235495,2024-11-30 22:59:19.890190,https://radiotimes.com

Egypt, history number 9
Last 5 records

,synthetic_time,synthetic_url
234910,2024-11-30 11:45:22.116013,https://www.shopify.com/hk-en?page=1
234911,2024-11-30 12:31:00.090100,https://www.techtarget.com/technologyguide/?newsid=4368
234912,2024-11-30 13:42:07.290442,https://everydayhealth.com
234913,2024-11-30 13:42:30.374820,https://alrifaiarabia.com
234914,2024-11-30 21:21:00.307220,https://radiotimes.com

Estonia, history number 0
Last 5 records

,synthetic_time,synthetic_url
234328,2024-11-30 12:50:30.541557,https://eelk.ee/elulood/ots_edgar.html
234329,2024-11-30 13:36:08.515644,https://www.weekend.ee/b-young-pluus-flaminia-518489.html
234330,2024-11-30 14:47:15.715986,https://wise.com
234331,2024-11-30 14:47:38.800364,https://looper.com
234332,2024-11-30 22:26:08.732764,https://err.ee

Estonia, history number 1
Last 5 records

,synthetic_time,synthetic_url
233724,2024-11-30 12:46:21.092537,https://www.viljandi.ee/palgamaarad-ja-andmed
233725,2024-11-30 13:31:59.066624,https://www.weekend.ee/brandid/parfois/lapsed.html
233726,2024-11-30 14:43:06.266966,https://wise.com
233727,2024-11-30 14:43:29.351344,https://looper.com
233728,2024-11-30 22:21:59.283744,https://err.ee

Estonia, history number 2
Last 5 records

,synthetic_time,synthetic_url
233117,2024-11-30 12:11:28.534540,https://www.viljandi.ee/palgamaarad-ja-andmed
233118,2024-11-30 12:57:06.508627,https://www.weekend.ee/vero-moda-seelik-ava-352358.html
233119,2024-11-30 14:08:13.708969,https://wise.com
233120,2024-11-30 14:08:36.793347,https://looper.com
233121,2024-11-30 21:47:06.725747,https://err.ee

Estonia, history number 3
Last 5 records

,synthetic_time,synthetic_url
232511,2024-11-30 13:01:08.620019,https://www.sorainen.com/deals/?pg=157
232512,2024-11-30 13:46:46.594106,https://www.geni.com/people/catherine-bowdish/6000000143389312838
232513,2024-11-30 14:57:53.794448,https://wise.com
232514,2024-11-30 14:58:16.878826,https://looper.com
232515,2024-11-30 22:36:46.811226,https://err.ee

Estonia, history number 4
Last 5 records

,synthetic_time,synthetic_url
231917,2024-11-30 12:04:13.817804,https://www.viljandi.ee/koostoopartnerid
231918,2024-11-30 12:49:51.791891,https://www.geni.com/people/aaron-brownmiller/6000000062291064033
231919,2024-11-30 14:00:58.992233,https://wise.com
231920,2024-11-30 14:01:22.076611,https://looper.com
231921,2024-11-30 21:39:52.009011,https://err.ee

Estonia, history number 5
Last 5 records

,synthetic_time,synthetic_url
231309,2024-11-30 11:47:22.367197,https://eelk.ee/kirik/taname/
231310,2024-11-30 12:33:00.341284,https://www.geni.com/people/aagje-dorst/6000000016953289490
231311,2024-11-30 13:44:07.541626,https://wise.com
231312,2024-11-30 13:44:30.626004,https://looper.com
231313,2024-11-30 21:23:00.558404,https://err.ee

Estonia, history number 6
Last 5 records

,synthetic_time,synthetic_url
230704,2024-11-30 12:00:34.381014,https://eelk.ee/kirik/taname/
230705,2024-11-30 12:46:12.355101,https://www.geni.com/people/gustav-eriksson/6000000198817180902
230706,2024-11-30 13:57:19.555443,https://wise.com
230707,2024-11-30 13:57:42.639821,https://looper.com
230708,2024-11-30 21:36:12.572221,https://err.ee

Estonia, history number 7
Last 5 records

,synthetic_time,synthetic_url
230094,2024-11-30 12:04:43.952988,https://www.viljandi.ee/et
230095,2024-11-30 12:50:21.927075,https://www.weekend.ee/superdry-rinnahoidja-517720.html
230096,2024-11-30 14:01:29.127417,https://wise.com
230097,2024-11-30 14:01:52.211795,https://looper.com
230098,2024-11-30 21:40:22.144195,https://err.ee

Estonia, history number 8
Last 5 records

,synthetic_time,synthetic_url
229490,2024-11-30 12:34:02.863427,https://www.viljandi.ee/koostoopartnerid
229491,2024-11-30 13:19:40.837514,https://www.weekend.ee/b-young-pluus-flaminia-518489.html
229492,2024-11-30 14:30:48.037856,https://wise.com
229493,2024-11-30 14:31:11.122234,https://looper.com
229494,2024-11-30 22:09:41.054634,https://err.ee

Estonia, history number 9
Last 5 records

,synthetic_time,synthetic_url
228888,2024-11-30 12:29:15.275324,https://www.viljandi.ee/ettevotlus1
228889,2024-11-30 13:14:53.249411,https://www.geni.com/people/margaret-wilson/6000000000664855622
228890,2024-11-30 14:26:00.449753,https://wise.com
228891,2024-11-30 14:26:23.534131,https://looper.com
228892,2024-11-30 22:04:53.466531,https://err.ee

Finland, history number 0
Last 5 records

,synthetic_time,synthetic_url
228287,2024-11-30 12:52:45.370631,https://www.opistopalvelut.fi/inga/index.php?&l=sv
228288,2024-11-30 13:38:23.344718,https://stackexchange.com/users/29946/marcobazzani
228289,2024-11-30 14:49:30.545060,https://gamesradar.com
228290,2024-11-30 14:49:53.629438,https://jiosaavn.com
228291,2024-11-30 22:28:23.561838,https://suomi24.fi

Finland, history number 1
Last 5 records

,synthetic_time,synthetic_url
227688,2024-11-30 11:35:06.766782,https://www.opistopalvelut.fi/karstula/
227689,2024-11-30 12:20:44.740869,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
227690,2024-11-30 13:31:51.941211,https://gamesradar.com
227691,2024-11-30 13:32:15.025589,https://famousbirthdays.com
227692,2024-11-30 21:10:44.957989,https://suomi24.fi

Finland, history number 2
Last 5 records

,synthetic_time,synthetic_url
227096,2024-11-30 11:51:31.800253,https://puolustusvoimat.fi/haku?q=puheet
227097,2024-11-30 12:37:09.774340,https://stackexchange.com/users/29946/marcobazzani
227098,2024-11-30 13:48:16.974682,https://oxfordreference.com
227099,2024-11-30 13:48:40.059060,https://storytel.com
227100,2024-11-30 21:27:09.991460,https://suomi24.fi

Finland, history number 3
Last 5 records

,synthetic_time,synthetic_url
226504,2024-11-30 13:13:11.728607,https://puolustusvoimat.fi/haku?q=rauhanturvaajat
226505,2024-11-30 13:58:49.702694,https://stackexchange.com/users/23211477/phoenix-in-the-air
226506,2024-11-30 15:09:56.903036,https://gamesradar.com
226507,2024-11-30 15:10:19.987414,https://storytel.com
226508,2024-11-30 22:48:49.919814,https://suomi24.fi

Finland, history number 4
Last 5 records

,synthetic_time,synthetic_url
225918,2024-11-30 12:10:11.105253,https://www.kuusamo.fi/ajankohtaista/
225919,2024-11-30 12:55:49.079340,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
225920,2024-11-30 14:06:56.279682,https://oxfordreference.com
225921,2024-11-30 14:07:19.364060,https://storytel.com
225922,2024-11-30 21:45:49.296460,https://suomi24.fi

Finland, history number 5
Last 5 records

,synthetic_time,synthetic_url
225326,2024-11-30 12:52:30.504928,https://puolustusvoimat.fi/miljazz-2024
225327,2024-11-30 13:38:08.479015,https://stackexchange.com/users/29946/marcobazzani
225328,2024-11-30 14:49:15.679357,https://rome2rio.com
225329,2024-11-30 14:49:38.763735,https://jiosaavn.com
225330,2024-11-30 22:28:08.696135,https://suomi24.fi

Finland, history number 6
Last 5 records

,synthetic_time,synthetic_url
224726,2024-11-30 11:41:46.831005,https://www.opistopalvelut.fi/karstula/
224727,2024-11-30 12:27:24.805092,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
224728,2024-11-30 13:38:32.005434,https://bestbuy.com
224729,2024-11-30 13:38:55.089812,https://storytel.com
224730,2024-11-30 21:17:25.022212,https://suomi24.fi

Finland, history number 7
Last 5 records

,synthetic_time,synthetic_url
224132,2024-11-30 12:08:02.802953,https://www.opistopalvelut.fi/saarijarvi/
224133,2024-11-30 12:53:40.777040,https://stackexchange.com/users/17066786/oliwia-stam
224134,2024-11-30 14:04:47.977382,https://rome2rio.com
224135,2024-11-30 14:05:11.061760,https://storytel.com
224136,2024-11-30 21:43:40.994160,https://suomi24.fi

Finland, history number 8
Last 5 records

,synthetic_time,synthetic_url
223544,2024-11-30 12:00:48.058075,https://www.kuopio.fi/eloiloolo/
223545,2024-11-30 12:46:26.032162,https://stackexchange.com/users/8442750/unknown-user
223546,2024-11-30 13:57:33.232504,https://gamesradar.com
223547,2024-11-30 13:57:56.316882,https://famousbirthdays.com
223548,2024-11-30 21:36:26.249282,https://suomi24.fi

Finland, history number 9
Last 5 records

,synthetic_time,synthetic_url
222952,2024-11-30 11:34:37.405492,https://www.opistopalvelut.fi/kiuruvesi/info.php?l=sv
222953,2024-11-30 12:20:15.379579,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
222954,2024-11-30 13:31:22.579921,https://rome2rio.com
222955,2024-11-30 13:31:45.664299,https://famousbirthdays.com
222956,2024-11-30 21:10:15.596699,https://suomi24.fi

France, history number 0
Last 5 records

,synthetic_time,synthetic_url
222374,2024-11-30 12:00:25.153638,https://www.ville-vichy.fr/elus/fpm-desbrest
222375,2024-11-30 12:46:03.127725,https://github.com/m417z/global-inject-demo
222376,2024-11-30 13:57:10.328067,https://merckmanuals.com
222377,2024-11-30 13:57:33.412445,https://livre-rare-book.com
222378,2024-11-30 21:36:03.344845,https://europe1.fr

France, history number 1
Last 5 records

,synthetic_time,synthetic_url
221756,2024-11-30 11:24:41.950108,https://www.saintsebastien.fr/annuaire/alss-handball/
221757,2024-11-30 12:10:19.924195,https://github.com/icsharpcode/ilspy#ilspy-------
221758,2024-11-30 13:21:27.124537,https://globalsources.com
221759,2024-11-30 13:21:50.208915,https://livre-rare-book.com
221760,2024-11-30 21:00:20.141315,https://europe1.fr

France, history number 2
Last 5 records

,synthetic_time,synthetic_url
221146,2024-11-30 12:03:55.309650,https://www.ville-vichy.fr/projets/allier
221147,2024-11-30 12:49:33.283737,https://github.com/battlesnakeofficial/rules
221148,2024-11-30 14:00:40.484079,https://shell.com
221149,2024-11-30 14:01:03.568457,https://livre-rare-book.com
221150,2024-11-30 21:39:33.500857,https://numerama.com

France, history number 3
Last 5 records

,synthetic_time,synthetic_url
220532,2024-11-30 13:23:02.425452,https://www.ville-vichy.fr/pij
220533,2024-11-30 14:08:40.399539,https://github.com/ascoderu/lokole/pull/105
220534,2024-11-30 15:19:47.599881,https://globalsources.com
220535,2024-11-30 15:20:10.684259,https://livre-rare-book.com
220536,2024-11-30 22:58:40.616659,https://numerama.com

France, history number 4
Last 5 records

,synthetic_time,synthetic_url
219918,2024-11-30 11:30:36.764506,https://www.ville-vichy.fr/animaux
219919,2024-11-30 12:16:14.738593,https://github.com/ropod-project/ropod_experiment_executor
219920,2024-11-30 13:27:21.938935,https://globalsources.com
219921,2024-11-30 13:27:45.023313,https://livre-rare-book.com
219922,2024-11-30 21:06:14.955713,https://goal.com

France, history number 5
Last 5 records

,synthetic_time,synthetic_url
219305,2024-11-30 12:02:28.509414,https://vertou.fr/club-de-lecture-ado/
219306,2024-11-30 12:48:06.483501,https://github.com/m417z/global-inject-demo
219307,2024-11-30 13:59:13.683843,https://merckmanuals.com
219308,2024-11-30 13:59:36.768221,https://livre-rare-book.com
219309,2024-11-30 21:38:06.700621,https://goal.com

France, history number 6
Last 5 records

,synthetic_time,synthetic_url
218687,2024-11-30 11:46:49.938750,https://www.ville-vichy.fr/animaux
218688,2024-11-30 12:32:27.912837,https://github.com/battlesnakeofficial/rules
218689,2024-11-30 13:43:35.113179,https://merckmanuals.com
218690,2024-11-30 13:43:58.197557,https://livre-rare-book.com
218691,2024-11-30 21:22:28.129957,https://numerama.com

France, history number 7
Last 5 records

,synthetic_time,synthetic_url
218061,2024-11-30 11:42:59.853967,https://metz.fr/lieux/lieu-4201.php
218062,2024-11-30 12:28:37.828054,https://github.com/tutao/tutanota/issues/1579
218063,2024-11-30 13:39:45.028396,https://www.merckmanuals.com/
218064,2024-11-30 13:40:08.112774,https://livre-rare-book.com
218065,2024-11-30 21:18:38.045174,https://goal.com

France, history number 8
Last 5 records

,synthetic_time,synthetic_url
217450,2024-11-30 11:36:25.090256,https://www.lonslesaunier.fr/lons-mag-juin-2022/
217451,2024-11-30 12:22:03.064343,https://github.com/sylvaingml/swift-sgitkeyboardlistener
217452,2024-11-30 13:33:10.264685,https://globalsources.com
217453,2024-11-30 13:33:33.349063,https://livre-rare-book.com
217454,2024-11-30 21:12:03.281463,https://numerama.com

France, history number 9
Last 5 records

,synthetic_time,synthetic_url
216828,2024-11-30 13:30:43.225979,https://www.quizz.biz/quizz-569741.html
216829,2024-11-30 14:16:21.200066,https://github.com/battlesnakeofficial/rules
216830,2024-11-30 15:27:28.400408,https://merckmanuals.com
216831,2024-11-30 15:27:51.484786,https://livre-rare-book.com
216832,2024-11-30 23:06:21.417186,https://europe1.fr

Germany, history number 0
Last 5 records

,synthetic_time,synthetic_url
216202,2024-11-30 13:03:59.962583,https://administrator.de/user/vetti/
216203,2024-11-30 13:49:37.936670,https://stackexchange.com/users/17066786/oliwia-stam
216204,2024-11-30 15:00:45.137012,https://motor1.com
216205,2024-11-30 15:01:08.221390,https://jiosaavn.com
216206,2024-11-30 22:39:38.153790,https://rbb-online.de

Germany, history number 1
Last 5 records

,synthetic_time,synthetic_url
215621,2024-11-30 12:10:19.232659,https://www.rheinbach.de/veranstaltungen
215622,2024-11-30 12:55:57.206746,https://stackexchange.com/users/29946/marcobazzani
215623,2024-11-30 14:07:04.407088,https://motor1.com
215624,2024-11-30 14:07:27.491466,https://jiosaavn.com
215625,2024-11-30 21:45:57.423866,https://hessenschau.de

Germany, history number 2
Last 5 records

,synthetic_time,synthetic_url
215054,2024-11-30 13:31:56.315025,https://www.rheinbach.de/veranstaltungen
215055,2024-11-30 14:17:34.289112,https://stackexchange.com/users/17066786/oliwia-stam
215056,2024-11-30 15:28:41.489454,https://subway.com
215057,2024-11-30 15:29:04.573832,https://jiosaavn.com
215058,2024-11-30 23:07:34.506232,https://stuttgarter-zeitung.de

Germany, history number 3
Last 5 records

,synthetic_time,synthetic_url
214480,2024-11-30 12:00:29.903606,https://administrator.de/user/nico34/
214481,2024-11-30 12:46:07.877693,https://stackexchange.com/users/17066786/oliwia-stam
214482,2024-11-30 13:57:15.078035,https://shell.com
214483,2024-11-30 13:57:38.162413,https://jiosaavn.com
214484,2024-11-30 21:36:08.094813,https://www.ndr.de:443/fernsehen/sendungen/markt/index.html

Germany, history number 4
Last 5 records

,synthetic_time,synthetic_url
213906,2024-11-30 12:32:55.442367,https://administrator.de/user/charley44/
213907,2024-11-30 13:18:33.416454,https://stackexchange.com/users/28516911/zodwa-sigutya
213908,2024-11-30 14:29:40.616796,https://shell.com
213909,2024-11-30 14:30:03.701174,https://jiosaavn.com
213910,2024-11-30 22:08:33.633574,https://stuttgarter-nachrichten.de

Germany, history number 5
Last 5 records

,synthetic_time,synthetic_url
213332,2024-11-30 11:51:07.771016,https://administrator.de/user/vetti/
213333,2024-11-30 12:36:45.745103,https://stackexchange.com/users/17066786/oliwia-stam
213334,2024-11-30 13:47:52.945445,https://subway.com
213335,2024-11-30 13:48:16.029823,https://jiosaavn.com
213336,2024-11-30 21:26:45.962223,https://t-online.de

Germany, history number 6
Last 5 records

,synthetic_time,synthetic_url
212767,2024-11-30 13:15:43.896373,https://www.kaarst.de/datenschutzerklaerung
212768,2024-11-30 14:01:21.870460,https://stackexchange.com/users/30047207/alrey-john
212769,2024-11-30 15:12:29.070802,https://subway.com
212770,2024-11-30 15:12:52.155180,https://jiosaavn.com
212771,2024-11-30 22:51:22.087580,https://br.de

Germany, history number 7
Last 5 records

,synthetic_time,synthetic_url
212195,2024-11-30 12:30:48.996677,https://www.kaarst.de/europawahl-2024
212196,2024-11-30 13:16:26.970764,https://stackexchange.com/users/30047207/alrey-john
212197,2024-11-30 14:27:34.171106,https://motor1.com
212198,2024-11-30 14:27:57.255484,https://jiosaavn.com
212199,2024-11-30 22:06:27.187884,https://derwesten.de

Germany, history number 8
Last 5 records

,synthetic_time,synthetic_url
211622,2024-11-30 12:26:36.133074,https://administrator.de/user/strods/
211623,2024-11-30 13:12:14.107161,https://stackexchange.com/users/8442750/unknown-user
211624,2024-11-30 14:23:21.307503,https://subway.com
211625,2024-11-30 14:23:44.391881,https://jiosaavn.com
211626,2024-11-30 22:02:14.324281,https://sportskeeda.com

Germany, history number 9
Last 5 records

,synthetic_time,synthetic_url
211048,2024-11-30 12:19:41.707944,https://www.kaarst.de/datenschutzerklaerung
211049,2024-11-30 13:05:19.682031,https://stackexchange.com/users/23211477/phoenix-in-the-air
211050,2024-11-30 14:16:26.882373,https://subway.com
211051,2024-11-30 14:16:49.966751,https://jiosaavn.com
211052,2024-11-30 21:55:19.899151,https://t-online.de

Greece, history number 0
Last 5 records

,synthetic_time,synthetic_url
210467,2024-11-30 11:58:08.193773,https://lingvanex.com/terms-of-service/
210468,2024-11-30 12:45:18.649263,https://www.techradar.com/phones/motorola-phones/page/8
210469,2024-11-30 13:56:25.849605,https://ferries.gr
210470,2024-11-30 13:56:48.933983,https://vectorstock.com
210471,2024-11-30 21:35:18.866383,https://skroutz.gr

Greece, history number 1
Last 5 records

,synthetic_time,synthetic_url
209860,2024-11-30 11:29:04.681870,https://lingvanex.com/terms-of-service/
209861,2024-11-30 12:16:15.137360,https://www.techradar.com/news/wandavision-episode-8-recap-review
209862,2024-11-30 13:27:22.337702,https://medicalnewstoday.com
209863,2024-11-30 13:27:45.422080,https://famousbirthdays.com
209864,2024-11-30 21:06:15.354480,https://skroutz.gr

Greece, history number 2
Last 5 records

,synthetic_time,synthetic_url
209246,2024-11-30 11:45:47.027832,https://lingvanex.com/terms-of-service/
209247,2024-11-30 12:32:57.483322,https://www.techradar.com/news/wandavision-episode-8-recap-review
209248,2024-11-30 13:44:04.683664,https://hrs.com
209249,2024-11-30 13:44:27.768042,https://famousbirthdays.com
209250,2024-11-30 21:22:57.700442,https://skroutz.gr

Greece, history number 3
Last 5 records

,synthetic_time,synthetic_url
208642,2024-11-30 12:31:22.236982,https://lingvanex.com/terms-of-service/
208643,2024-11-30 13:18:32.692472,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
208644,2024-11-30 14:29:39.892814,https://corissia.com
208645,2024-11-30 14:30:02.977192,https://vectorstock.com
208646,2024-11-30 22:08:32.909592,https://skroutz.gr

Greece, history number 4
Last 5 records

,synthetic_time,synthetic_url
208030,2024-11-30 13:28:11.568326,https://lingvanex.com/terms-of-service/
208031,2024-11-30 14:15:22.023816,https://www.digitaltrends.com/home/philips-hue-debuts-its-new-app/
208032,2024-11-30 15:26:29.224158,https://medicalnewstoday.com
208033,2024-11-30 15:26:52.308536,https://famousbirthdays.com
208034,2024-11-30 23:05:22.240936,https://skroutz.gr

Greece, history number 5
Last 5 records

,synthetic_time,synthetic_url
207421,2024-11-30 12:14:21.270433,https://lingvanex.com/terms-of-service/
207422,2024-11-30 13:01:31.725923,https://www.techradar.com/gaming/consoles-pc/playstation/page/3
207423,2024-11-30 14:12:38.926265,https://ferries.gr
207424,2024-11-30 14:13:02.010643,https://vectorstock.com
207425,2024-11-30 21:51:31.943043,https://skroutz.gr

Greece, history number 6
Last 5 records

,synthetic_time,synthetic_url
206817,2024-11-30 12:59:03.251601,https://lingvanex.com/terms-of-service/
206818,2024-11-30 13:46:13.707091,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
206819,2024-11-30 14:57:20.907433,https://halkidiki.com
206820,2024-11-30 14:57:43.991811,https://vectorstock.com
206821,2024-11-30 22:36:13.924211,https://skroutz.gr

Greece, history number 7
Last 5 records

,synthetic_time,synthetic_url
206205,2024-11-30 12:36:16.611487,https://lingvanex.com/terms-of-service/
206206,2024-11-30 13:23:27.066977,https://www.digitaltrends.com/computing/acer-unveils-aspire-p3-ultrabook/
206207,2024-11-30 14:34:34.267319,https://halkidiki.com
206208,2024-11-30 14:34:57.351697,https://famousbirthdays.com
206209,2024-11-30 22:13:27.284097,https://skroutz.gr

Greece, history number 8
Last 5 records

,synthetic_time,synthetic_url
205589,2024-11-30 11:52:50.099828,https://lingvanex.com/terms-of-service/
205590,2024-11-30 12:40:00.555318,https://www.techradar.com/gaming/consoles-pc/playstation/page/3
205591,2024-11-30 13:51:07.755660,https://achaiaclauss.gr
205592,2024-11-30 13:51:30.840038,https://famousbirthdays.com
205593,2024-11-30 21:30:00.772438,https://skroutz.gr

Greece, history number 9
Last 5 records

,synthetic_time,synthetic_url
204978,2024-11-30 13:29:41.578164,https://lingvanex.com/terms-of-service/
204979,2024-11-30 14:16:52.033654,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
204980,2024-11-30 15:27:59.233996,https://medicalnewstoday.com
204981,2024-11-30 15:28:22.318374,https://famousbirthdays.com
204982,2024-11-30 23:06:52.250774,https://skroutz.gr

Hungary, history number 0
Last 5 records

,synthetic_time,synthetic_url
204379,2024-11-30 13:02:54.568288,https://www.maltai.hu/?action=new&newid=1285
204380,2024-11-30 13:48:32.542375,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
204381,2024-11-30 14:59:39.742717,https://rome2rio.com
204382,2024-11-30 15:00:02.827095,https://disneyplus.com
204383,2024-11-30 22:38:32.759495,https://allevents.in

Hungary, history number 1
Last 5 records

,synthetic_time,synthetic_url
203746,2024-11-30 12:37:42.252817,https://maltai.hu/efop182422202200002
203747,2024-11-30 13:23:20.226904,https://stackexchange.com/users/5455775/ryuakamatsu
203748,2024-11-30 14:34:27.427246,https://jamieoliver.com
203749,2024-11-30 14:34:50.511624,https://allmusic.com
203750,2024-11-30 22:13:20.444024,https://goal.com

Hungary, history number 2
Last 5 records

,synthetic_time,synthetic_url
203108,2024-11-30 13:20:12.591123,https://maltai.hu/gondviseleshazatokaj
203109,2024-11-30 14:05:50.565210,https://stackexchange.com/users/17066786/oliwia-stam
203110,2024-11-30 15:16:57.765552,https://rome2rio.com
203111,2024-11-30 15:17:20.849930,https://shazam.com
203112,2024-11-30 22:55:50.782330,https://allevents.in

Hungary, history number 3
Last 5 records

,synthetic_time,synthetic_url
202480,2024-11-30 11:30:34.975233,https://maltai.hu/efop182422202200002
202481,2024-11-30 12:16:12.949320,https://stackexchange.com/users/8442750/unknown-user
202482,2024-11-30 13:27:20.149662,https://dexerto.com
202483,2024-11-30 13:27:43.234040,https://disneyplus.com
202484,2024-11-30 21:06:13.166440,https://allevents.in

Hungary, history number 4
Last 5 records

,synthetic_time,synthetic_url
201853,2024-11-30 13:11:19.764049,https://www.maltai.hu/specialisonkentesseg
201854,2024-11-30 13:56:57.738136,https://stackexchange.com/users/17066786/oliwia-stam
201855,2024-11-30 15:08:04.938478,https://jamieoliver.com
201856,2024-11-30 15:08:28.022856,https://disneyplus.com
201857,2024-11-30 22:46:57.955256,https://goal.com

Hungary, history number 5
Last 5 records

,synthetic_time,synthetic_url
201212,2024-11-30 12:47:48.105052,https://maltai.hu/vasjelnyelvtolmacs
201213,2024-11-30 13:33:26.079139,https://stackexchange.com/users/23211477/phoenix-in-the-air
201214,2024-11-30 14:44:33.279481,https://jamieoliver.com
201215,2024-11-30 14:44:56.363859,https://disneyplus.com
201216,2024-11-30 22:23:26.296259,https://allevents.in

Hungary, history number 6
Last 5 records

,synthetic_time,synthetic_url
200576,2024-11-30 11:40:14.556000,https://www.maltai.hu/?action=new&newid=1232
200577,2024-11-30 12:25:52.530087,https://stackexchange.com/users/23211477/phoenix-in-the-air
200578,2024-11-30 13:36:59.730429,https://rome2rio.com
200579,2024-11-30 13:37:22.814807,https://shazam.com
200580,2024-11-30 21:15:52.747207,https://allevents.in

Hungary, history number 7
Last 5 records

,synthetic_time,synthetic_url
199941,2024-11-30 12:10:14.765550,https://www.maltai.hu/?action=new&newid=1195
199942,2024-11-30 12:55:52.739637,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
199943,2024-11-30 14:06:59.939979,https://dexerto.com
199944,2024-11-30 14:07:23.024357,https://shopalike.hu
199945,2024-11-30 21:45:52.956757,https://allevents.in

Hungary, history number 8
Last 5 records

,synthetic_time,synthetic_url
199307,2024-11-30 12:15:32.001650,https://www.maltai.hu/?action=new&newid=1232
199308,2024-11-30 13:01:09.975737,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
199309,2024-11-30 14:12:17.176079,https://dexerto.com
199310,2024-11-30 14:12:40.260457,https://shopalike.hu
199311,2024-11-30 21:51:10.192857,https://allevents.in

Hungary, history number 9
Last 5 records

,synthetic_time,synthetic_url
198671,2024-11-30 12:31:20.652024,https://reformatus.hu/mediumok/hirek/?page=17
198672,2024-11-30 13:16:58.626111,https://stackexchange.com/users/5455775/ryuakamatsu
198673,2024-11-30 14:28:05.826453,https://dexerto.com
198674,2024-11-30 14:28:28.910831,https://allmusic.com
198675,2024-11-30 22:06:58.843231,https://allevents.in

India, history number 0
Last 5 records

,synthetic_time,synthetic_url
198043,2024-11-30 12:50:39.594519,https://www.drikpanchang.com/tamil/tamil-gowri-panchangam.html?date=05/01/2017
198044,2024-11-30 13:36:17.568606,https://www.techtarget.com/news/?news_date=2023-04-23
198045,2024-11-30 14:47:24.768948,https://everydayhealth.com
198046,2024-11-30 14:47:47.853326,https://floweraura.com
198047,2024-11-30 22:26:17.785726,https://indiatimes.com

India, history number 1
Last 5 records

,synthetic_time,synthetic_url
197403,2024-11-30 11:41:44.045908,https://weddingz.in/wedding-photographers/mysore/
197404,2024-11-30 12:27:22.019995,https://www.techtarget.com/technologyguide/?newsid=4368
197405,2024-11-30 13:38:29.220337,https://everydayhealth.com
197406,2024-11-30 13:38:52.304715,https://floweraura.com
197407,2024-11-30 21:17:22.237115,https://indiatimes.com

India, history number 2
Last 5 records

,synthetic_time,synthetic_url
196770,2024-11-30 12:14:01.236948,https://www.drikpanchang.com/festivals/guru-purnima/guru-purnima-date-time.html?year=2022
196771,2024-11-30 12:59:39.211035,https://www.techtarget.com/contributor/alex-scroxton/page/14
196772,2024-11-30 14:10:46.411377,https://everydayhealth.com
196773,2024-11-30 14:11:09.495755,https://floweraura.com
196774,2024-11-30 21:49:39.428155,https://indiatimes.com

India, history number 3
Last 5 records

,synthetic_time,synthetic_url
196141,2024-11-30 12:31:49.376838,https://weddingz.in/party-plots/kolkata/thakurpukur/
196142,2024-11-30 13:17:27.350925,https://www.udemy.com/course/sales-leadership/
196143,2024-11-30 14:28:34.551267,https://everydayhealth.com
196144,2024-11-30 14:28:57.635645,https://archiecomics.com
196145,2024-11-30 22:07:27.568045,https://indiatimes.com

India, history number 4
Last 5 records

,synthetic_time,synthetic_url
195510,2024-11-30 13:15:20.221226,https://www.drikpanchang.com/tamil/tamil-gowri-panchangam.html?date=07/02/2495
195511,2024-11-30 14:00:58.195313,https://www.oracle.com/java/technologies/?er=221886
195512,2024-11-30 15:12:05.395655,https://everydayhealth.com
195513,2024-11-30 15:12:28.480033,https://archiecomics.com
195514,2024-11-30 22:50:58.412433,https://indiatimes.com

India, history number 5
Last 5 records

,synthetic_time,synthetic_url
194879,2024-11-30 12:03:19.077003,https://weddingz.in
194880,2024-11-30 12:48:57.051090,https://www.udemy.com/course/sales-leadership/
194881,2024-11-30 14:00:04.251432,https://everydayhealth.com
194882,2024-11-30 14:00:27.335810,https://floweraura.com
194883,2024-11-30 21:38:57.268210,https://indiatimes.com

India, history number 6
Last 5 records

,synthetic_time,synthetic_url
194244,2024-11-30 11:56:53.566573,https://weddingz.in/kolkata/china-palace-banquet-hall-behala/
194245,2024-11-30 12:42:31.540660,https://www.oracle.com/database/cloud-migration/
194246,2024-11-30 13:53:38.741002,https://everydayhealth.com
194247,2024-11-30 13:54:01.825380,https://floweraura.com
194248,2024-11-30 21:32:31.757780,https://indiatimes.com

India, history number 7
Last 5 records

,synthetic_time,synthetic_url
193618,2024-11-30 12:06:26.007322,https://weddingz.in/mussoorie/the-fern-brentwood-resort-spa-mussoorie-the-mall-road/
193619,2024-11-30 12:52:03.981409,https://www.techtarget.com/news/?news_date=2023-04-23
193620,2024-11-30 14:03:11.181751,https://everydayhealth.com
193621,2024-11-30 14:03:34.266129,https://floweraura.com
193622,2024-11-30 21:42:04.198529,https://indiatimes.com

India, history number 8
Last 5 records

,synthetic_time,synthetic_url
192993,2024-11-30 13:26:42.443365,https://weddingz.in/jaipur/la-premier-resort-jaipur-ameramber/
192994,2024-11-30 14:12:20.417452,https://www.udemy.com/course/civil-works-expert-civil3d-level-1/
192995,2024-11-30 15:23:27.617794,https://everydayhealth.com
192996,2024-11-30 15:23:50.702172,https://bajajfinservmarkets.in
192997,2024-11-30 23:02:20.634572,https://indiatimes.com

India, history number 9
Last 5 records

,synthetic_time,synthetic_url
192356,2024-11-30 12:43:54.405765,https://weddingz.in/bridal-mehndi-artists/meerut/
192357,2024-11-30 13:29:32.379852,https://www.techtarget.com/news/?news_date=2022-12-11
192358,2024-11-30 14:40:39.580194,https://everydayhealth.com
192359,2024-11-30 14:41:02.664572,https://floweraura.com
192360,2024-11-30 22:19:32.596972,https://indiatimes.com

Ireland, history number 0
Last 5 records

,synthetic_time,synthetic_url
191721,2024-11-30 12:56:37.367044,https://www.dctrust.ie/product/c-9.html
191722,2024-11-30 13:42:15.341131,https://stackoverflow.com/users/1786873/leonardo-allievi?tab=tags
191723,2024-11-30 14:53:22.541473,https://everydayhealth.com
191724,2024-11-30 14:53:45.625851,https://mountainwarehouse.com
191725,2024-11-30 22:32:15.558251,https://irishcentral.com

Ireland, history number 1
Last 5 records

,synthetic_time,synthetic_url
191083,2024-11-30 12:56:30.180819,https://www.tipperarycoco.ie/arts-and-culture?page=1
191084,2024-11-30 13:42:55.397773,https://stackoverflow.com/users/4953216/kevin-hammet
191085,2024-11-30 14:54:02.598115,https://everydayhealth.com
191086,2024-11-30 14:54:25.682493,https://www.mountainwarehouse.com/
191087,2024-11-30 22:32:55.614893,https://sportskeeda.com

Ireland, history number 2
Last 5 records

,synthetic_time,synthetic_url
190450,2024-11-30 11:28:57.108763,https://www.dctrust.ie/books-dvd-s/c-1.html
190451,2024-11-30 12:14:35.082850,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
190452,2024-11-30 13:25:42.283192,https://everydayhealth.com
190453,2024-11-30 13:26:05.367570,https://mountainwarehouse.com
190454,2024-11-30 21:04:35.299970,https://allevents.in

Ireland, history number 3
Last 5 records

,synthetic_time,synthetic_url
189807,2024-11-30 12:45:17.004140,https://www.dctrust.ie/genealogy/home.html
189808,2024-11-30 13:30:54.978227,https://stackoverflow.com/users/3864926/bret-van-putten
189809,2024-11-30 14:42:02.178569,https://everydayhealth.com
189810,2024-11-30 14:42:25.262947,https://www.mountainwarehouse.com/
189811,2024-11-30 22:20:55.195347,https://mentalfloss.com

Ireland, history number 4
Last 5 records

,synthetic_time,synthetic_url
189171,2024-11-30 12:51:08.329520,https://www.tipperarycoco.ie/information-technology
189172,2024-11-30 13:36:46.303607,https://www.techtarget.com/iotagenda/definition/zigbee
189173,2024-11-30 14:47:53.503949,https://everydayhealth.com
189174,2024-11-30 14:48:16.588327,https://www.mountainwarehouse.com/
189175,2024-11-30 22:26:46.520727,https://sportskeeda.com

Ireland, history number 5
Last 5 records

,synthetic_time,synthetic_url
188534,2024-11-30 11:45:49.051734,https://clarecoco.ie/services/planning/
188535,2024-11-30 12:31:27.025821,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
188536,2024-11-30 13:42:34.226163,https://everydayhealth.com
188537,2024-11-30 13:42:57.310541,https://www.mountainwarehouse.com/
188538,2024-11-30 21:21:27.242941,https://cbssports.com

Ireland, history number 6
Last 5 records

,synthetic_time,synthetic_url
187894,2024-11-30 13:09:29.171902,https://www.dctrust.ie/product/c-9.html
187895,2024-11-30 13:55:07.145989,https://www.digitaltrends.com/home/homes-with-secret-passages/
187896,2024-11-30 15:06:14.346331,https://everydayhealth.com
187897,2024-11-30 15:06:37.430709,https://mountainwarehouse.com
187898,2024-11-30 22:45:07.363109,https://hellomagazine.com

Ireland, history number 7
Last 5 records

,synthetic_time,synthetic_url
187255,2024-11-30 13:19:47.855211,https://www.dctrust.ie/product/c-9.html
187256,2024-11-30 14:06:13.072165,https://stackoverflow.com/help/badges/1/teacher?userid=16446
187257,2024-11-30 15:17:20.272507,https://everydayhealth.com
187258,2024-11-30 15:17:43.356885,https://mountainwarehouse.com
187259,2024-11-30 22:56:13.289285,https://sportskeeda.com

Ireland, history number 8
Last 5 records

,synthetic_time,synthetic_url
186610,2024-11-30 12:14:49.764239,https://www.tipperarycoco.ie/arts-and-culture?page=1
186611,2024-11-30 13:00:27.738326,https://stackoverflow.com/users/3864926/bret-van-putten
186612,2024-11-30 14:11:34.938668,https://everydayhealth.com
186613,2024-11-30 14:11:58.023046,https://mountainwarehouse.com
186614,2024-11-30 21:50:27.955446,https://mentalfloss.com

Ireland, history number 9
Last 5 records

,synthetic_time,synthetic_url
185966,2024-11-30 11:41:19.446885,https://lingvanex.com/terms-of-service/
185967,2024-11-30 12:27:44.663839,https://stackoverflow.com/users/1601638/we-b-martians?tab=articles
185968,2024-11-30 13:38:51.864181,https://everydayhealth.com
185969,2024-11-30 13:39:14.948559,https://mountainwarehouse.com
185970,2024-11-30 21:17:44.880959,https://irishcentral.com

Israel, history number 0
Last 5 records

,synthetic_time,synthetic_url
185326,2024-11-30 12:37:46.739211,https://www.karmanow.com/shop?retailers=2002
185327,2024-11-30 13:23:24.713298,https://www.digitaltrends.com/mobile/apple-watch-sales-november/
185328,2024-11-30 14:34:31.913640,https://tomsguide.com
185329,2024-11-30 14:34:54.998018,https://365scores.com
185330,2024-11-30 22:13:24.930418,https://tiktok.com

Israel, history number 1
Last 5 records

,synthetic_time,synthetic_url
184707,2024-11-30 12:38:43.682621,http://syriacorthodoxresources.org/bethgazo/index.html
184708,2024-11-30 13:24:21.656708,https://www.digitaltrends.com/news/spacex-nasa-crewed-launch/
184709,2024-11-30 14:35:28.857050,https://bcg.com
184710,2024-11-30 14:35:51.941428,https://allmusic.com
184711,2024-11-30 22:14:21.873828,https://tiktok.com

Israel, history number 2
Last 5 records

,synthetic_time,synthetic_url
184085,2024-11-30 12:25:13.342231,https://www.secrettelaviv.com/tickets/jimbo-j-barby-6
184086,2024-11-30 13:10:51.316318,https://www.digitaltrends.com/mobile/apple-watch-sales-november/
184087,2024-11-30 14:21:58.516660,https://bcg.com
184088,2024-11-30 14:22:21.601038,https://harelart.com
184089,2024-11-30 22:00:51.533438,https://tiktok.com

Israel, history number 3
Last 5 records

,synthetic_time,synthetic_url
183457,2024-11-30 12:57:49.709821,https://www.karmanow.com/shop?retailers=168636
183458,2024-11-30 13:43:27.683908,https://www.digitaltrends.com/home/homes-with-secret-passages/
183459,2024-11-30 14:54:34.884250,https://bcg.com
183460,2024-11-30 14:54:57.968628,https://www.harelart.com/
183461,2024-11-30 22:33:27.901028,https://tiktok.com

Israel, history number 4
Last 5 records

,synthetic_time,synthetic_url
182828,2024-11-30 11:50:09.424615,https://shimur.org/events/31142/
182829,2024-11-30 12:35:47.398702,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
182830,2024-11-30 13:46:54.599044,https://www.bcg.com:443/portugal
182831,2024-11-30 13:47:17.683422,https://365scores.com
182832,2024-11-30 21:25:47.615822,https://tiktok.com

Israel, history number 5
Last 5 records

,synthetic_time,synthetic_url
182207,2024-11-30 12:37:09.973933,https://www.algosec.com/company/events
182208,2024-11-30 13:22:47.948020,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
182209,2024-11-30 14:33:55.148362,https://www.bcg.com:443/portugal
182210,2024-11-30 14:34:18.232740,https://levantinegallery.com
182211,2024-11-30 22:12:48.165140,https://tiktok.com

Israel, history number 6
Last 5 records

,synthetic_time,synthetic_url
181574,2024-11-30 13:20:54.635123,https://www.algosec.com/company/management
181575,2024-11-30 14:06:32.609210,https://www.digitaltrends.com/home/philips-hue-debuts-its-new-app/
181576,2024-11-30 15:17:39.809552,https://www.bcg.com:443/portugal
181577,2024-11-30 15:18:02.893930,https://tubitv.com
181578,2024-11-30 22:56:32.826330,https://tiktok.com

Israel, history number 7
Last 5 records

,synthetic_time,synthetic_url
180950,2024-11-30 12:39:35.271574,https://www.algosec.com/check-point-and-algosec
180951,2024-11-30 13:25:13.245661,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
180952,2024-11-30 14:36:20.446003,https://www.bcg.com:443/portugal
180953,2024-11-30 14:36:43.530381,https://tubitv.com
180954,2024-11-30 22:15:13.462781,https://tiktok.com

Israel, history number 8
Last 5 records

,synthetic_time,synthetic_url
180321,2024-11-30 13:19:44.762063,http://syriacorthodoxresources.org/bethgazo/index.html
180322,2024-11-30 14:05:22.736150,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
180323,2024-11-30 15:16:29.936492,https://tomsguide.com
180324,2024-11-30 15:16:53.020870,https://harelart.com
180325,2024-11-30 22:55:22.953270,https://tiktok.com

Israel, history number 9
Last 5 records

,synthetic_time,synthetic_url
179695,2024-11-30 11:25:27.589476,https://www.karmanow.com/shop?retailers=2002
179696,2024-11-30 12:11:05.563563,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
179697,2024-11-30 13:22:12.763905,https://bcg.com
179698,2024-11-30 13:22:35.848283,https://ultimate-guitar.com
179699,2024-11-30 21:01:05.780683,https://tiktok.com

Italy, history number 0
Last 5 records

,synthetic_time,synthetic_url
179064,2024-11-30 12:03:50.244049,https://www.studentville.it/appunti/in-calce/
179065,2024-11-30 12:51:00.699539,https://www.britannica.com/biography/salif-keita-malian-athlete
179066,2024-11-30 14:02:07.899881,https://investing.com
179067,2024-11-30 14:02:30.984259,https://chordify.net
179068,2024-11-30 21:41:00.916659,https://virgilio.it

Italy, history number 1
Last 5 records

,synthetic_time,synthetic_url
178440,2024-11-30 13:21:38.281902,https://www.studentville.it/appunti/in-calce/
178441,2024-11-30 14:08:48.737392,https://www.britannica.com/science/summer-solstice-astronomy
178442,2024-11-30 15:19:55.937734,https://investing.com
178443,2024-11-30 15:20:19.022112,https://chordify.net
178444,2024-11-30 22:58:48.954512,https://ansa.it

Italy, history number 2
Last 5 records

,synthetic_time,synthetic_url
177828,2024-11-30 12:54:06.873755,https://www.studentville.it/appunti/in-calce/
177829,2024-11-30 13:41:17.329245,https://www.britannica.com/science/pharyngeal-pouch
177830,2024-11-30 14:52:24.529587,https://investing.com
177831,2024-11-30 14:52:47.613965,https://chordify.net
177832,2024-11-30 22:31:17.546365,https://sportskeeda.com

Italy, history number 3
Last 5 records

,synthetic_time,synthetic_url
177219,2024-11-30 12:38:48.019777,https://www.studentville.it/appunti/in-calce/
177220,2024-11-30 13:25:58.475267,https://www.britannica.com/topic/thus-spake-zarathustra
177221,2024-11-30 14:37:05.675609,https://investing.com
177222,2024-11-30 14:37:28.759987,https://chordify.net
177223,2024-11-30 22:15:58.692387,https://sportskeeda.com

Italy, history number 4
Last 5 records

,synthetic_time,synthetic_url
176603,2024-11-30 11:56:35.629665,https://www.studentville.it/appunti/in-calce/
176604,2024-11-30 12:43:46.085155,https://www.britannica.com/biography/frank-morgan-american-actor
176605,2024-11-30 13:54:53.285497,https://investing.com
176606,2024-11-30 13:55:16.369875,https://chordify.net
176607,2024-11-30 21:33:46.302275,https://virgilio.it

Italy, history number 5
Last 5 records

,synthetic_time,synthetic_url
175981,2024-11-30 13:33:56.578711,https://www.studentville.it/appunti/in-calce/
175982,2024-11-30 14:21:07.034201,https://www.britannica.com/biography/frank-morgan-american-actor
175983,2024-11-30 15:32:14.234543,https://investing.com
175984,2024-11-30 15:32:37.318921,https://chordify.net
175985,2024-11-30 23:11:07.251321,https://ilfattoquotidiano.it

Italy, history number 6
Last 5 records

,synthetic_time,synthetic_url
175359,2024-11-30 13:02:37.472946,https://www.studentville.it/appunti/in-calce/
175360,2024-11-30 13:49:47.928436,https://www.britannica.com/topic/thus-spake-zarathustra
175361,2024-11-30 15:00:55.128778,https://investing.com
175362,2024-11-30 15:01:18.213156,https://chordify.net
175363,2024-11-30 22:39:48.145556,https://virgilio.it

Italy, history number 7
Last 5 records

,synthetic_time,synthetic_url
174746,2024-11-30 12:37:30.827210,https://www.studentville.it/appunti/in-calce/
174747,2024-11-30 13:24:41.282700,https://www.britannica.com/biography/frank-morgan-american-actor
174748,2024-11-30 14:35:48.483042,https://investing.com
174749,2024-11-30 14:36:11.567420,https://chordify.net
174750,2024-11-30 22:14:41.499820,https://ilfattoquotidiano.it

Italy, history number 8
Last 5 records

,synthetic_time,synthetic_url
174131,2024-11-30 11:58:55.897520,https://www.studentville.it/appunti/in-calce/
174132,2024-11-30 12:46:06.353010,https://www.britannica.com/topic/thus-spake-zarathustra
174133,2024-11-30 13:57:13.553352,https://investing.com
174134,2024-11-30 13:57:36.637730,https://chordify.net
174135,2024-11-30 21:36:06.570130,https://ansa.it

Italy, history number 9
Last 5 records

,synthetic_time,synthetic_url
173498,2024-11-30 13:05:08.255984,https://www.studentville.it/appunti/in-calce/
173499,2024-11-30 13:52:18.711474,https://www.britannica.com/place/thar-desert/additional-info
173500,2024-11-30 15:03:25.911816,https://investing.com
173501,2024-11-30 15:03:48.996194,https://chordify.net
173502,2024-11-30 22:42:18.928594,https://ilfattoquotidiano.it

Japan, history number 0
Last 5 records

,synthetic_time,synthetic_url
172885,2024-11-30 12:09:25.488771,https://mombetsu.jp/gikai/outline/
172886,2024-11-30 12:55:03.462858,https://qiita.com/ruyo/following_organizations
172887,2024-11-30 14:06:10.663200,https://nyk.com
172888,2024-11-30 14:06:33.747578,https://cyzo.com
172889,2024-11-30 21:45:03.679978,https://tiktok.com

Japan, history number 1
Last 5 records

,synthetic_time,synthetic_url
172261,2024-11-30 11:26:59.112356,https://mombetsu.jp/life/?content=606
172262,2024-11-30 12:12:37.086443,https://qiita.com/cy-n_ao/following_organizations
172263,2024-11-30 13:23:44.286785,https://nyk.com
172264,2024-11-30 13:24:07.371163,https://cyzo.com
172265,2024-11-30 21:02:37.303563,https://tiktok.com

Japan, history number 2
Last 5 records

,synthetic_time,synthetic_url
171640,2024-11-30 12:15:44.436977,https://mombetsu.jp/life/?content=6
171641,2024-11-30 13:01:22.411064,https://qiita.com/bitter_fox/following_users
171642,2024-11-30 14:12:29.611406,https://nyk.com
171643,2024-11-30 14:12:52.695784,https://hands.net
171644,2024-11-30 21:51:22.628184,https://tiktok.com

Japan, history number 3
Last 5 records

,synthetic_time,synthetic_url
171020,2024-11-30 11:43:10.455377,https://mombetsu.jp/life/?content=6
171021,2024-11-30 12:28:48.429464,https://qiita.com/mitsukimaru/following_users
171022,2024-11-30 13:39:55.629806,https://nyk.com
171023,2024-11-30 13:40:18.714184,https://hands.net
171024,2024-11-30 21:18:48.646584,https://tiktok.com

Japan, history number 4
Last 5 records

,synthetic_time,synthetic_url
170393,2024-11-30 12:43:52.399771,https://mombetsu.jp/life/?content=373
170394,2024-11-30 13:30:17.616725,https://qiita.com/mitsukimaru/following_users
170395,2024-11-30 14:41:24.817067,https://nyk.com
170396,2024-11-30 14:41:47.901445,https://cyzo.com
170397,2024-11-30 22:20:17.833845,https://tiktok.com

Japan, history number 5
Last 5 records

,synthetic_time,synthetic_url
169776,2024-11-30 12:11:49.712460,https://mombetsu.jp/news/?category=93
169777,2024-11-30 12:57:27.686547,https://qiita.com/uspsocceracademy/following_tags
169778,2024-11-30 14:08:34.886889,https://nyk.com
169779,2024-11-30 14:08:57.971267,https://cyzo.com
169780,2024-11-30 21:47:27.903667,https://tiktok.com

Japan, history number 6
Last 5 records

,synthetic_time,synthetic_url
169141,2024-11-30 11:33:12.188310,https://mombetsu.jp/news/?category=93
169142,2024-11-30 12:18:50.162397,https://qiita.com/ruyo/following_organizations
169143,2024-11-30 13:29:57.362739,https://nyk.com
169144,2024-11-30 13:30:20.447117,https://hands.net
169145,2024-11-30 21:08:50.379517,https://tiktok.com

Japan, history number 7
Last 5 records

,synthetic_time,synthetic_url
168513,2024-11-30 12:49:33.262633,https://mombetsu.jp/education/?content=1862
168514,2024-11-30 13:35:11.236720,https://qiita.com/mitsukimaru/following_users
168515,2024-11-30 14:46:18.437062,https://nyk.com
168516,2024-11-30 14:46:41.521440,https://hands.net
168517,2024-11-30 22:25:11.453840,https://tiktok.com

Japan, history number 8
Last 5 records

,synthetic_time,synthetic_url
167893,2024-11-30 12:13:27.274690,https://mombetsu.jp/welfare/?content=483
167894,2024-11-30 12:59:05.248777,https://qiita.com/ruyo/following_organizations
167895,2024-11-30 14:10:12.449119,https://nyk.com
167896,2024-11-30 14:10:35.533497,https://hands.net
167897,2024-11-30 21:49:05.465897,https://tiktok.com

Japan, history number 9
Last 5 records

,synthetic_time,synthetic_url
167264,2024-11-30 11:25:27.935364,https://mombetsu.jp/life/?content=606
167265,2024-11-30 12:11:05.909451,https://qiita.com/bitter_fox/following_users
167266,2024-11-30 13:22:13.109793,https://nyk.com
167267,2024-11-30 13:22:36.194171,https://hands.net
167268,2024-11-30 21:01:06.126571,https://tiktok.com

Latvia, history number 0
Last 5 records

,synthetic_time,synthetic_url
166641,2024-11-30 13:10:08.363030,https://www.cvk.lv/lv
166642,2024-11-30 13:55:46.337117,https://www.digitaltrends.com/home/homes-with-secret-passages/
166643,2024-11-30 15:06:53.537459,https://eurogamer.net
166644,2024-11-30 15:07:16.621837,https://boozt.com
166645,2024-11-30 22:45:46.554237,https://la.lv

Latvia, history number 1
Last 5 records

,synthetic_time,synthetic_url
166057,2024-11-30 13:20:24.693435,https://www.cvk.lv/en
166058,2024-11-30 14:06:02.667522,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
166059,2024-11-30 15:17:09.867864,https://oxfordreference.com
166060,2024-11-30 15:17:32.952242,https://boozt.com
166061,2024-11-30 22:56:02.884642,https://la.lv

Latvia, history number 2
Last 5 records

,synthetic_time,synthetic_url
165472,2024-11-30 11:34:12.086282,https://www.cvk.lv/en
165473,2024-11-30 12:19:50.060369,https://www.samsung.com/africa_fr/support/model/cg-a515fzbsmmc/
165474,2024-11-30 13:30:57.260711,https://oxfordreference.com
165475,2024-11-30 13:31:20.345089,https://www.boozt.com/
165476,2024-11-30 21:09:50.277489,https://la.lv

Latvia, history number 3
Last 5 records

,synthetic_time,synthetic_url
164894,2024-11-30 12:40:44.370693,https://www.sorainen.com/recent-posts/?pg=354
164895,2024-11-30 13:26:22.344780,https://www.samsung.com/n_africa/support/model/sm-n980fzngect/
164896,2024-11-30 14:37:29.545122,https://oxfordreference.com
164897,2024-11-30 14:37:52.629500,https://boozt.com
164898,2024-11-30 22:16:22.561900,https://la.lv

Latvia, history number 4
Last 5 records

,synthetic_time,synthetic_url
164319,2024-11-30 12:37:09.700842,https://www.cvk.lv/lv
164320,2024-11-30 13:22:47.674929,https://www.digitaltrends.com/news/spacex-nasa-crewed-launch/
164321,2024-11-30 14:33:54.875271,https://oxfordreference.com
164322,2024-11-30 14:34:17.959649,https://boozt.com
164323,2024-11-30 22:12:47.892049,https://la.lv

Latvia, history number 5
Last 5 records

,synthetic_time,synthetic_url
163739,2024-11-30 11:48:47.407198,https://www.visitdaugavpils.lv/pasakumi/2024-06-12/
163740,2024-11-30 12:35:12.624152,https://www.samsung.com/n_africa/support/model/sm-n980fzngect/
163741,2024-11-30 13:46:19.824494,https://oxfordreference.com
163742,2024-11-30 13:46:42.908872,https://www.boozt.com/
163743,2024-11-30 21:25:12.841272,https://la.lv

Latvia, history number 6
Last 5 records

,synthetic_time,synthetic_url
163155,2024-11-30 12:32:40.581134,https://www.visitdaugavpils.lv/pasakumi/2024-06-12/
163156,2024-11-30 13:18:18.555221,https://www.samsung.com/africa_en/microwave-ovens/grill/ms32-tas/
163157,2024-11-30 14:29:25.755563,https://eurogamer.net
163158,2024-11-30 14:29:48.839941,https://boozt.com
163159,2024-11-30 22:08:18.772341,https://la.lv

Latvia, history number 7
Last 5 records

,synthetic_time,synthetic_url
162574,2024-11-30 12:51:53.532380,https://www.sorainen.com/deals/?pg=52
162575,2024-11-30 13:37:31.506467,https://www.digitaltrends.com/computing/acer-unveils-aspire-p3-ultrabook/
162576,2024-11-30 14:48:38.706809,https://oxfordreference.com
162577,2024-11-30 14:49:01.791187,https://boozt.com
162578,2024-11-30 22:27:31.723587,https://la.lv

Latvia, history number 8
Last 5 records

,synthetic_time,synthetic_url
162000,2024-11-30 11:39:22.210676,https://www.sorainen.com/recent-posts/?pg=354
162001,2024-11-30 12:25:00.184763,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
162002,2024-11-30 13:36:07.385105,https://oxfordreference.com
162003,2024-11-30 13:36:30.469483,https://www.boozt.com/
162004,2024-11-30 21:15:00.401883,https://la.lv

Latvia, history number 9
Last 5 records

,synthetic_time,synthetic_url
161417,2024-11-30 11:59:20.701363,https://www.visitdaugavpils.lv/pasakumi/2024-06-12/
161418,2024-11-30 12:44:58.675450,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
161419,2024-11-30 13:56:05.875792,https://eurogamer.net
161420,2024-11-30 13:56:28.960170,https://www.boozt.com/
161421,2024-11-30 21:34:58.892570,https://la.lv

Lithuania, history number 0
Last 5 records

,synthetic_time,synthetic_url
160843,2024-11-30 12:14:27.390753,https://www.mln.lt/aclit-uab/
160844,2024-11-30 13:00:05.364840,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
160845,2024-11-30 14:11:12.565182,https://timeout.com
160846,2024-11-30 14:11:35.649560,https://barnesandnoble.com
160847,2024-11-30 21:50:05.581960,https://thehindu.com

Lithuania, history number 1
Last 5 records

,synthetic_time,synthetic_url
160205,2024-11-30 12:35:06.134956,https://www.cherryservers.com/blog?page=4
160206,2024-11-30 13:20:44.109043,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
160207,2024-11-30 14:31:51.309385,https://lonelyplanet.com
160208,2024-11-30 14:32:14.393763,https://empireonline.com
160209,2024-11-30 22:10:44.326163,https://radiotimes.com

Lithuania, history number 2
Last 5 records

,synthetic_time,synthetic_url
159569,2024-11-30 13:30:23.417828,https://www.mln.lt/adblue-www-adblue-lt/
159570,2024-11-30 14:16:48.634782,https://stackexchange.com/users/17066786/oliwia-stam
159571,2024-11-30 15:27:55.835124,https://timeout.com
159572,2024-11-30 15:28:18.919502,https://discogs.com
159573,2024-11-30 23:06:48.851902,https://thehindu.com

Lithuania, history number 3
Last 5 records

,synthetic_time,synthetic_url
158940,2024-11-30 12:50:25.262336,https://www.cherryservers.com/legal/cookies
158941,2024-11-30 13:36:03.236423,https://stackexchange.com/users/28516911/zodwa-sigutya
158942,2024-11-30 14:47:10.436765,https://europart.net
158943,2024-11-30 14:47:33.521143,https://deviantart.com
158944,2024-11-30 22:26:03.453543,https://thehindu.com

Lithuania, history number 4
Last 5 records

,synthetic_time,synthetic_url
158304,2024-11-30 12:30:57.691648,https://www.cherryservers.com/blog?page=4
158305,2024-11-30 13:16:35.665735,https://stackexchange.com/users/17066786/oliwia-stam
158306,2024-11-30 14:27:42.866077,https://timeout.com
158307,2024-11-30 14:28:05.950455,https://discogs.com
158308,2024-11-30 22:06:35.882855,https://thehindu.com

Lithuania, history number 5
Last 5 records

,synthetic_time,synthetic_url
157675,2024-11-30 13:08:42.723070,https://www.cherryservers.com/blog
157676,2024-11-30 13:54:20.697157,https://stackexchange.com/users/28516911/zodwa-sigutya
157677,2024-11-30 15:05:27.897499,https://eso.lt
157678,2024-11-30 15:05:50.981877,https://empireonline.com
157679,2024-11-30 22:44:20.914277,https://radiotimes.com

Lithuania, history number 6
Last 5 records

,synthetic_time,synthetic_url
157041,2024-11-30 11:43:02.878037,https://www.cherryservers.com/legal/privacy-policy
157042,2024-11-30 12:28:40.852124,https://stackexchange.com/users/17066786/oliwia-stam
157043,2024-11-30 13:39:48.052466,https://timeout.com
157044,2024-11-30 13:40:11.136844,https://empireonline.com
157045,2024-11-30 21:18:41.069244,https://radiotimes.com

Lithuania, history number 7
Last 5 records

,synthetic_time,synthetic_url
156414,2024-11-30 12:32:39.319205,https://www.cherryservers.com/dedicated-gpu-servers
156415,2024-11-30 13:18:17.293292,https://stackexchange.com/users/17066786/oliwia-stam
156416,2024-11-30 14:29:24.493634,https://europart.net
156417,2024-11-30 14:29:47.578012,https://barnesandnoble.com
156418,2024-11-30 22:08:17.510412,https://thehindu.com

Lithuania, history number 8
Last 5 records

,synthetic_time,synthetic_url
155774,2024-11-30 12:23:19.547943,https://www.mln.lt/moletunas-uab/
155775,2024-11-30 13:08:57.522030,https://stackexchange.com/users/30047207/alrey-john
155776,2024-11-30 14:20:04.722372,https://europart.net
155777,2024-11-30 14:20:27.806750,https://boxofficemojo.com
155778,2024-11-30 21:58:57.739150,https://radiotimes.com

Lithuania, history number 9
Last 5 records

,synthetic_time,synthetic_url
155136,2024-11-30 12:35:43.891900,https://www.cherryservers.com/blog
155137,2024-11-30 13:21:21.865987,https://stackexchange.com/users/27587530/jo%c3%a3o-ribeiro
155138,2024-11-30 14:32:29.066329,https://eso.lt
155139,2024-11-30 14:32:52.150707,https://deviantart.com
155140,2024-11-30 22:11:22.083107,https://thehindu.com

Malaysia, history number 0
Last 5 records

,synthetic_time,synthetic_url
154508,2024-11-30 12:26:35.581114,https://www.calculator.net/z-score-calculator.html
154509,2024-11-30 13:12:13.555201,https://www.grammarly.com/business/learn/modmed-ai-grammarly/
154510,2024-11-30 14:23:20.755543,https://everydayhealth.com
154511,2024-11-30 14:23:43.839921,https://lyrics.com
154512,2024-11-30 22:02:13.772321,https://transfermarkt.com

Malaysia, history number 1
Last 5 records

,synthetic_time,synthetic_url
153863,2024-11-30 12:52:39.710123,https://www.asus.com/news/3jghn1jitrjezcoe/
153864,2024-11-30 13:38:17.684210,https://lingvanex.com/dictionary/english-to-romanian/tenement
153865,2024-11-30 14:49:24.884552,https://everydayhealth.com
153866,2024-11-30 14:49:47.968930,https://koreaboo.com
153867,2024-11-30 22:28:17.901330,https://transfermarkt.com

Malaysia, history number 2
Last 5 records

,synthetic_time,synthetic_url
153222,2024-11-30 12:39:49.389457,https://a-z-animals.com/animals/dalmatian-mix/
153223,2024-11-30 13:25:27.363544,https://lingvanex.com/dictionary/english-to-romanian/peeling
153224,2024-11-30 14:36:34.563886,https://everydayhealth.com
153225,2024-11-30 14:36:57.648264,https://lyrics.com
153226,2024-11-30 22:15:27.580664,https://transfermarkt.com

Malaysia, history number 3
Last 5 records

,synthetic_time,synthetic_url
152583,2024-11-30 13:02:02.273002,https://www.ny.gov/?page=455
152584,2024-11-30 13:47:40.247089,https://lingvanex.com/dictionary/english-to-catalan/anode
152585,2024-11-30 14:58:47.447431,https://everydayhealth.com
152586,2024-11-30 14:59:10.531809,https://koreaboo.com
152587,2024-11-30 22:37:40.464209,https://mathworks.com

Malaysia, history number 4
Last 5 records

,synthetic_time,synthetic_url
151935,2024-11-30 12:36:06.461157,https://www.ny.gov/events?page=201
151936,2024-11-30 13:21:44.435244,https://lingvanex.com/dictionary/english-to-malay/qualifier
151937,2024-11-30 14:32:51.635586,https://everydayhealth.com
151938,2024-11-30 14:33:14.719964,https://lyrics.com
151939,2024-11-30 22:11:44.652364,https://livemint.com

Malaysia, history number 5
Last 5 records

,synthetic_time,synthetic_url
151292,2024-11-30 13:01:38.222835,https://a-z-animals.com/animals/dalmatian-mix/
151293,2024-11-30 13:47:16.196922,https://www.vecteezy.com/vector-art/1184088-top-view-white-wood-texture
151294,2024-11-30 14:58:23.397264,https://everydayhealth.com
151295,2024-11-30 14:58:46.481642,https://lyrics.com
151296,2024-11-30 22:37:16.414042,https://si.com

Malaysia, history number 6
Last 5 records

,synthetic_time,synthetic_url
150651,2024-11-30 12:52:32.000150,https://www.ny.gov/events?page=262
150652,2024-11-30 13:38:09.974237,https://www.grammarly.com/browser?utm_medium=social
150653,2024-11-30 14:49:17.174579,https://everydayhealth.com
150654,2024-11-30 14:49:40.258957,https://lyrics.com
150655,2024-11-30 22:28:10.191357,https://transfermarkt.com

Malaysia, history number 7
Last 5 records

,synthetic_time,synthetic_url
150007,2024-11-30 12:51:05.466744,https://www.ny.gov/events?page=201
150008,2024-11-30 13:36:43.440831,https://www.vecteezy.com/vector-art/1184088-top-view-white-wood-texture
150009,2024-11-30 14:47:50.641173,https://everydayhealth.com
150010,2024-11-30 14:48:13.725551,https://koreaboo.com
150011,2024-11-30 22:26:43.657951,https://livemint.com

Malaysia, history number 8
Last 5 records

,synthetic_time,synthetic_url
149369,2024-11-30 11:43:13.961143,https://www.ny.gov/?page=392
149370,2024-11-30 12:28:51.935230,https://www.grammarly.com/browser?utm_medium=social
149371,2024-11-30 13:39:59.135572,https://everydayhealth.com
149372,2024-11-30 13:40:22.219950,https://koreaboo.com
149373,2024-11-30 21:18:52.152350,https://mathworks.com

Malaysia, history number 9
Last 5 records

,synthetic_time,synthetic_url
148731,2024-11-30 12:19:37.659153,https://www.ny.gov/events?page=92
148732,2024-11-30 13:05:15.633240,https://lingvanex.com/dictionary/english-to-arabic/villain
148733,2024-11-30 14:16:22.833582,https://everydayhealth.com
148734,2024-11-30 14:16:45.917960,https://lyrics.com
148735,2024-11-30 21:55:15.850360,https://mathworks.com

Mexico, history number 0
Last 5 records

,synthetic_time,synthetic_url
148094,2024-11-30 11:48:56.362353,https://www.smartick.es/blog/lectura/page/2/
148095,2024-11-30 12:34:34.336440,https://www.canva.com/pl_pl/help/connect-to-moodle/
148096,2024-11-30 13:45:41.536782,https://babycenter.com
148097,2024-11-30 13:46:04.621160,https://nike.com
148098,2024-11-30 21:24:34.553560,https://lavozdegalicia.es

Mexico, history number 1
Last 5 records

,synthetic_time,synthetic_url
147524,2024-11-30 12:50:29.662627,https://www.flaticon.es/iconos-gratis/alquiler
147525,2024-11-30 13:36:07.636714,https://www.canva.com/colors/color-palettes/ice-cold-rose/
147526,2024-11-30 14:47:14.837056,https://ehu.eus
147527,2024-11-30 14:47:37.921434,https://cinemex.com
147528,2024-11-30 22:26:07.853834,https://as.com

Mexico, history number 2
Last 5 records

,synthetic_time,synthetic_url
146959,2024-11-30 11:28:08.760604,https://www.biblia.work/sermons/
146960,2024-11-30 12:13:46.734691,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
146961,2024-11-30 13:24:53.935033,https://answers.com
146962,2024-11-30 13:25:17.019411,https://nike.com
146963,2024-11-30 21:03:46.951811,https://sportskeeda.com

Mexico, history number 3
Last 5 records

,synthetic_time,synthetic_url
146382,2024-11-30 12:35:38.309635,https://www.flaticon.es/iconos-gratis/feto
146383,2024-11-30 13:22:03.526589,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
146384,2024-11-30 14:33:10.726931,https://babycenter.com
146385,2024-11-30 14:33:33.811309,https://cinemex.com
146386,2024-11-30 22:12:03.743709,https://as.com

Mexico, history number 4
Last 5 records

,synthetic_time,synthetic_url
145796,2024-11-30 12:53:58.644375,https://www.flaticon.es/iconos-gratis/tugrik
145797,2024-11-30 13:39:36.618462,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
145798,2024-11-30 14:50:43.818804,https://www.merckmanuals.com/
145799,2024-11-30 14:51:06.903182,https://nike.com
145800,2024-11-30 22:29:36.835582,https://as.com

Mexico, history number 5
Last 5 records

,synthetic_time,synthetic_url
145205,2024-11-30 13:27:25.916494,https://www.smartick.es/blog/lectura/esquema/
145206,2024-11-30 14:13:03.890581,https://www.canva.com/colors/color-palettes/camera-ready/
145207,2024-11-30 15:24:11.090923,https://plannedparenthood.org
145208,2024-11-30 15:24:34.175301,https://cinemex.com
145209,2024-11-30 23:03:04.107701,https://mundodeportivo.com

Mexico, history number 6
Last 5 records

,synthetic_time,synthetic_url
144621,2024-11-30 12:50:28.515707,https://www.flaticon.es/iconos-gratis/alquiler
144622,2024-11-30 13:36:06.489794,https://www.canva.com/tr_tr/sablonlar/s/nisan/
144623,2024-11-30 14:47:13.690136,https://ehu.eus
144624,2024-11-30 14:47:36.774514,https://cinemex.com
144625,2024-11-30 22:26:06.706914,https://sport.es

Mexico, history number 7
Last 5 records

,synthetic_time,synthetic_url
144038,2024-11-30 11:36:31.622870,https://www.flaticon.es/iconos-gratis/alquiler
144039,2024-11-30 12:22:09.596957,https://www.canva.com/tr_tr/help/using-blackboard-lms/
144040,2024-11-30 13:33:16.797299,https://answers.com
144041,2024-11-30 13:33:39.881677,https://cinemex.com
144042,2024-11-30 21:12:09.814077,https://pressreader.com

Mexico, history number 8
Last 5 records

,synthetic_time,synthetic_url
143459,2024-11-30 13:01:05.296405,https://www.smartick.es/blog/lectura/esquema/
143460,2024-11-30 13:46:43.270492,https://www.canva.com/tr_tr/help/using-blackboard-lms/
143461,2024-11-30 14:57:50.470834,https://answers.com
143462,2024-11-30 14:58:13.555212,https://nike.com
143463,2024-11-30 22:36:43.487612,https://cope.es

Mexico, history number 9
Last 5 records

,synthetic_time,synthetic_url
142894,2024-11-30 12:39:30.165042,https://www.flaticon.es/iconos-gratis/feto
142895,2024-11-30 13:25:08.139129,https://www.canva.com/photos/mac6dldh0oa-abdominal-massage/
142896,2024-11-30 14:36:15.339471,https://answers.com
142897,2024-11-30 14:36:38.423849,https://nike.com
142898,2024-11-30 22:15:08.356249,https://cope.es

Morocco, history number 0
Last 5 records

,synthetic_time,synthetic_url
142319,2024-11-30 11:45:29.148069,https://www.scribbr.fr/author/raimo/
142320,2024-11-30 12:31:07.122156,https://www.canva.com/tr_tr/help/using-blackboard-lms/
142321,2024-11-30 13:42:14.322498,https://investing.com
142322,2024-11-30 13:42:37.406876,https://themoviedb.org
142323,2024-11-30 21:21:07.339276,https://europe1.fr

Morocco, history number 1
Last 5 records

,synthetic_time,synthetic_url
141710,2024-11-30 11:51:44.402241,https://www.scribbr.fr/author/raimo/
141711,2024-11-30 12:37:22.376328,https://www.canva.com/es_es/plantillas/s/bacterias/
141712,2024-11-30 13:48:29.576670,https://investing.com
141713,2024-11-30 13:48:52.661048,https://www.asos.com/
141714,2024-11-30 21:27:22.593448,https://france.tv

Morocco, history number 2
Last 5 records

,synthetic_time,synthetic_url
141096,2024-11-30 13:27:44.520746,https://www.scribbr.fr/author/raimo/
141097,2024-11-30 14:13:22.494833,https://www.canva.com/photos/mac6dldh0oa-abdominal-massage/
141098,2024-11-30 15:24:29.695175,https://jooble.org
141099,2024-11-30 15:24:52.779553,https://themoviedb.org
141100,2024-11-30 23:03:22.711953,https://europe1.fr

Morocco, history number 3
Last 5 records

,synthetic_time,synthetic_url
140489,2024-11-30 12:42:41.935236,https://www.merci-app.com/lexique/subit-ou-subi
140490,2024-11-30 13:28:19.909323,https://www.canva.com/es_mx/plantillas/s/catalogos/
140491,2024-11-30 14:39:27.109665,https://investing.com
140492,2024-11-30 14:39:50.194043,https://themoviedb.org
140493,2024-11-30 22:18:20.126443,https://europe1.fr

Morocco, history number 4
Last 5 records

,synthetic_time,synthetic_url
139883,2024-11-30 12:20:39.921372,https://www.scribbr.fr/author/raimo/
139884,2024-11-30 13:06:17.895459,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
139885,2024-11-30 14:17:25.095801,https://investing.com
139886,2024-11-30 14:17:48.180179,https://www.asos.com/
139887,2024-11-30 21:56:18.112579,https://rts.ch

Morocco, history number 5
Last 5 records

,synthetic_time,synthetic_url
139279,2024-11-30 12:50:26.177199,https://www.scribbr.fr/author/justine/
139280,2024-11-30 13:36:04.151286,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
139281,2024-11-30 14:47:11.351628,https://investing.com
139282,2024-11-30 14:47:34.436006,https://asos.com
139283,2024-11-30 22:26:04.368406,https://cnrs.fr

Morocco, history number 6
Last 5 records

,synthetic_time,synthetic_url
138667,2024-11-30 13:33:15.907262,https://www.scribbr.fr/author/justine/
138668,2024-11-30 14:18:53.881349,https://www.canva.com/it_it/biglietti/modelli/invito/
138669,2024-11-30 15:30:01.081691,https://investing.com
138670,2024-11-30 15:30:24.166069,https://asos.com
138671,2024-11-30 23:08:54.098469,https://france.tv

Morocco, history number 7
Last 5 records

,synthetic_time,synthetic_url
138060,2024-11-30 12:16:38.367239,https://www.scribbr.fr/author/justine/
138061,2024-11-30 13:02:16.341326,https://www.canva.com/photos/mac6dldh0oa-abdominal-massage/
138062,2024-11-30 14:13:23.541668,https://jooble.org
138063,2024-11-30 14:13:46.626046,https://asos.com
138064,2024-11-30 21:52:16.558446,https://europe1.fr

Morocco, history number 8
Last 5 records

,synthetic_time,synthetic_url
137459,2024-11-30 12:18:22.314113,https://www.scribbr.fr/author/raimo/
137460,2024-11-30 13:04:47.531067,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
137461,2024-11-30 14:15:54.731409,https://jooble.org
137462,2024-11-30 14:16:17.815787,https://themoviedb.org
137463,2024-11-30 21:54:47.748187,https://numerama.com

Morocco, history number 9
Last 5 records

,synthetic_time,synthetic_url
136850,2024-11-30 12:20:40.099759,https://www.scribbr.fr/author/raimo/
136851,2024-11-30 13:07:05.316713,https://www.canva.com/it_it/biglietti/modelli/invito/
136852,2024-11-30 14:18:12.517055,https://jooble.org
136853,2024-11-30 14:18:35.601433,https://asos.com
136854,2024-11-30 21:57:05.533833,https://cnrs.fr

Netherlands, history number 0
Last 5 records

,synthetic_time,synthetic_url
136237,2024-11-30 13:03:54.463786,https://www.velsen.nl/kindgebonden-budget
136238,2024-11-30 13:49:32.437873,https://www.digitaltrends.com/computing/acer-unveils-aspire-p3-ultrabook/
136239,2024-11-30 15:00:39.638215,https://maastrichtuniversity.nl
136240,2024-11-30 15:01:02.722593,https://foam.org
136241,2024-11-30 22:39:32.654993,https://allevents.in

Netherlands, history number 1
Last 5 records

,synthetic_time,synthetic_url
135618,2024-11-30 12:55:28.208595,https://www.rijswijk.nl/nieuwsoverzicht?page=42
135619,2024-11-30 13:41:06.182682,https://www.samsung.com/levant/support/model/lc32jg52qquxen/
135620,2024-11-30 14:52:13.383024,https://maastrichtuniversity.nl
135621,2024-11-30 14:52:36.467402,https://vectorstock.com
135622,2024-11-30 22:31:06.399802,https://npo.nl

Netherlands, history number 2
Last 5 records

,synthetic_time,synthetic_url
134996,2024-11-30 11:32:45.244626,https://www.velsen.nl/sportpark-waterloo
134997,2024-11-30 12:18:23.218713,https://www.samsung.com/africa_fr/support/model/cg-a515fzbsmmc/
134998,2024-11-30 13:29:30.419055,https://maastrichtuniversity.nl
134999,2024-11-30 13:29:53.503433,https://lyrics.com
135000,2024-11-30 21:08:23.435833,https://allevents.in

Netherlands, history number 3
Last 5 records

,synthetic_time,synthetic_url
134370,2024-11-30 13:31:28.175245,https://www.nuenen.nl/bezwaar-maken
134371,2024-11-30 14:17:06.149332,https://www.samsung.com/latin_en/support/model/qn65qn85bafxza/
134372,2024-11-30 15:28:13.349674,https://tomsguide.com
134373,2024-11-30 15:28:36.434052,https://foam.org
134374,2024-11-30 23:07:06.366452,https://npo.nl

Netherlands, history number 4
Last 5 records

,synthetic_time,synthetic_url
133746,2024-11-30 12:42:22.706810,https://www.velsen.nl/petrakerk-pont-tot-park
133747,2024-11-30 13:28:00.680897,https://www.samsung.com/hk_en/support/model/ef-zg99pcbegew/
133748,2024-11-30 14:39:07.881239,https://tomsguide.com
133749,2024-11-30 14:39:30.965617,https://lyrics.com
133750,2024-11-30 22:18:00.898017,https://npo.nl

Netherlands, history number 5
Last 5 records

,synthetic_time,synthetic_url
133119,2024-11-30 11:42:09.319990,https://www.aalsmeer.nl/home
133120,2024-11-30 12:27:47.294077,https://www.samsung.com/latin_en/support/model/qn65qn85bafxza/
133121,2024-11-30 13:38:54.494419,https://tomsguide.com
133122,2024-11-30 13:39:17.578797,https://foam.org
133123,2024-11-30 21:17:47.511197,https://allevents.in

Netherlands, history number 6
Last 5 records

,synthetic_time,synthetic_url
132504,2024-11-30 12:34:58.259593,https://www.alkmaar.nl/duurzaam/nieuwsbrief/
132505,2024-11-30 13:20:36.233680,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
132506,2024-11-30 14:31:43.434022,https://maastrichtuniversity.nl
132507,2024-11-30 14:32:06.518400,https://lyrics.com
132508,2024-11-30 22:10:36.450800,https://npo.nl

Netherlands, history number 7
Last 5 records

,synthetic_time,synthetic_url
131885,2024-11-30 11:54:25.973736,https://www.velsen.nl/kindgebonden-budget
131886,2024-11-30 12:40:03.947823,https://www.digitaltrends.com/home/homes-with-secret-passages/
131887,2024-11-30 13:51:11.148165,https://maastrichtuniversity.nl
131888,2024-11-30 13:51:34.232543,https://lyrics.com
131889,2024-11-30 21:30:04.164943,https://npo.nl

Netherlands, history number 8
Last 5 records

,synthetic_time,synthetic_url
131265,2024-11-30 12:47:57.210368,https://www.woerden.nl/subsidie/boom
131266,2024-11-30 13:33:35.184455,https://www.samsung.com/africa_en/microwave-ovens/grill/ms32-tas/
131267,2024-11-30 14:44:42.384797,https://tomsguide.com
131268,2024-11-30 14:45:05.469175,https://foam.org
131269,2024-11-30 22:23:35.401575,https://allevents.in

Netherlands, history number 9
Last 5 records

,synthetic_time,synthetic_url
130635,2024-11-30 12:18:54.668810,https://www.woerden.nl/aanbesteding_inhuur
130636,2024-11-30 13:04:32.642897,https://www.digitaltrends.com/mobile/apple-watch-sales-november/
130637,2024-11-30 14:15:39.843239,https://maastrichtuniversity.nl
130638,2024-11-30 14:16:02.927617,https://vectorstock.com
130639,2024-11-30 21:54:32.860017,https://allevents.in

New_Zealand, history number 0
Last 5 records

,synthetic_time,synthetic_url
130015,2024-11-30 13:30:51.288651,https://pasttenses.com/junkings-synonyms
130016,2024-11-30 14:16:29.262738,https://www.techtarget.com/contributor/alex-scroxton/page/14
130017,2024-11-30 15:27:36.463080,https://everydayhealth.com
130018,2024-11-30 15:27:59.547458,https://www.pinkvilla.com/
130019,2024-11-30 23:06:29.479858,https://pennmedicine.org

New_Zealand, history number 1
Last 5 records

,synthetic_time,synthetic_url
129371,2024-11-30 11:39:40.700333,https://pasttenses.com/wired-synonyms
129372,2024-11-30 12:25:18.674420,https://www.techtarget.com/contributor/andrew-howard
129373,2024-11-30 13:36:25.874762,https://everydayhealth.com
129374,2024-11-30 13:36:48.959140,https://behindthevoiceactors.com
129375,2024-11-30 21:15:18.891540,https://skysports.com

New_Zealand, history number 2
Last 5 records

,synthetic_time,synthetic_url
128726,2024-11-30 11:33:52.545809,https://lingvanex.com/terms-of-service/
128727,2024-11-30 12:19:30.519896,https://www.digitaltrends.com/cool-tech/wi-fi-detects-suspicious-items/
128728,2024-11-30 13:30:37.720238,https://everydayhealth.com
128729,2024-11-30 13:31:00.804616,https://davidjones.com
128730,2024-11-30 21:09:30.737016,https://pennmedicine.org

New_Zealand, history number 3
Last 5 records

,synthetic_time,synthetic_url
128089,2024-11-30 12:43:37.179588,https://pasttenses.com/apt-synonyms
128090,2024-11-30 13:29:15.153675,https://www.digitaltrends.com/news/spacex-nasa-crewed-launch/
128091,2024-11-30 14:40:22.354017,https://everydayhealth.com
128092,2024-11-30 14:40:45.438395,https://www.pinkvilla.com/
128093,2024-11-30 22:19:15.370795,https://skysports.com

New_Zealand, history number 4
Last 5 records

,synthetic_time,synthetic_url
127442,2024-11-30 12:38:58.522076,https://pasttenses.com/marginalize-synonyms
127443,2024-11-30 13:24:36.496163,https://www.techtarget.com/contributor/warwick-ashford/page/16
127444,2024-11-30 14:35:43.696505,https://everydayhealth.com
127445,2024-11-30 14:36:06.780883,https://www.pinkvilla.com/
127446,2024-11-30 22:14:36.713283,https://thehindu.com

New_Zealand, history number 5
Last 5 records

,synthetic_time,synthetic_url
126799,2024-11-30 11:59:02.976569,https://thecontentauthority.com/blog/enclave-vs-exclave
126800,2024-11-30 12:44:40.950656,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
126801,2024-11-30 13:55:48.150998,https://everydayhealth.com
126802,2024-11-30 13:56:11.235376,https://davidjones.com
126803,2024-11-30 21:34:41.167776,https://pennmedicine.org

New_Zealand, history number 6
Last 5 records

,synthetic_time,synthetic_url
126152,2024-11-30 12:31:44.810502,https://thecontentauthority.com/blog/canon-vs-cannon
126153,2024-11-30 13:17:22.784589,https://www.techtarget.com/technologyguide/?newsid=4368
126154,2024-11-30 14:28:29.984931,https://everydayhealth.com
126155,2024-11-30 14:28:53.069309,https://www.pinkvilla.com/
126156,2024-11-30 22:07:23.001709,https://skysports.com

New_Zealand, history number 7
Last 5 records

,synthetic_time,synthetic_url
125505,2024-11-30 11:24:24.597541,https://pasttenses.com/stampeding-synonyms
125506,2024-11-30 12:10:02.571628,https://www.techtarget.com/iotagenda/definition/zigbee
125507,2024-11-30 13:21:09.771970,https://everydayhealth.com
125508,2024-11-30 13:21:32.856348,https://davidjones.com
125509,2024-11-30 21:00:02.788748,https://skysports.com

New_Zealand, history number 8
Last 5 records

,synthetic_time,synthetic_url
124863,2024-11-30 11:24:26.230173,https://watv.org/history/
124864,2024-11-30 12:10:04.204260,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
124865,2024-11-30 13:21:11.404602,https://everydayhealth.com
124866,2024-11-30 13:21:34.488980,https://behindthevoiceactors.com
124867,2024-11-30 21:00:04.421380,https://thehindu.com

New_Zealand, history number 9
Last 5 records

,synthetic_time,synthetic_url
124221,2024-11-30 12:54:52.609911,https://pasttenses.com/junkings-synonyms
124222,2024-11-30 13:40:30.583998,https://www.digitaltrends.com/news/spacex-nasa-crewed-launch/
124223,2024-11-30 14:51:37.784340,https://everydayhealth.com
124224,2024-11-30 14:52:00.868718,https://pinkvilla.com
124225,2024-11-30 22:30:30.801118,https://skysports.com

Norway, history number 0
Last 5 records

,synthetic_time,synthetic_url
123574,2024-11-30 12:36:09.292788,https://www.lawinsider.com/contracts/2cji1iob4im
123575,2024-11-30 13:21:47.266875,https://stackexchange.com/users/5455775/ryuakamatsu
123576,2024-11-30 14:32:54.467217,https://pcgamer.com
123577,2024-11-30 14:33:17.551595,https://vectorstock.com
123578,2024-11-30 22:11:47.483995,https://nrk.no

Norway, history number 1
Last 5 records

,synthetic_time,synthetic_url
122963,2024-11-30 12:51:17.644807,https://www.lawinsider.com/contracts/9ksd80nvaua
122964,2024-11-30 13:36:55.618894,https://stackexchange.com/users/29946/marcobazzani
122965,2024-11-30 14:48:02.819236,https://eurogamer.net
122966,2024-11-30 14:48:25.903614,https://vectorstock.com
122967,2024-11-30 22:26:55.836014,https://nrk.no

Norway, history number 2
Last 5 records

,synthetic_time,synthetic_url
122354,2024-11-30 12:13:44.531955,https://www.lawinsider.com/contracts/6ze3ydqzbnt
122355,2024-11-30 12:59:22.506042,https://stackexchange.com/users/5455775/ryuakamatsu
122356,2024-11-30 14:10:29.706384,https://pcgamesn.com
122357,2024-11-30 14:10:52.790762,https://vectorstock.com
122358,2024-11-30 21:49:22.723162,https://nrk.no

Norway, history number 3
Last 5 records

,synthetic_time,synthetic_url
121747,2024-11-30 13:24:03.431891,https://www.lawinsider.com/clause/gross-negligence
121748,2024-11-30 14:09:41.405978,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
121749,2024-11-30 15:20:48.606320,https://eurogamer.net
121750,2024-11-30 15:21:11.690698,https://vectorstock.com
121751,2024-11-30 22:59:41.623098,https://nrk.no

Norway, history number 4
Last 5 records

,synthetic_time,synthetic_url
121149,2024-11-30 12:14:19.277248,https://www.lawinsider.com/clause/gross-negligence
121150,2024-11-30 12:59:57.251335,https://stackexchange.com/users/23211477/phoenix-in-the-air
121151,2024-11-30 14:11:04.451677,https://pcgamesn.com
121152,2024-11-30 14:11:27.536055,https://vectorstock.com
121153,2024-11-30 21:49:57.468455,https://nrk.no

Norway, history number 5
Last 5 records

,synthetic_time,synthetic_url
120530,2024-11-30 12:32:46.872681,https://www.lawinsider.com/contracts/9vmjyy9ihpy
120531,2024-11-30 13:18:24.846768,https://stackexchange.com/users/30047207/alrey-john
120532,2024-11-30 14:29:32.047110,https://pcgamesn.com
120533,2024-11-30 14:29:55.131488,https://vectorstock.com
120534,2024-11-30 22:08:25.063888,https://nrk.no

Norway, history number 6
Last 5 records

,synthetic_time,synthetic_url
119917,2024-11-30 13:20:50.180376,https://www.lawinsider.com/clause/company-limited
119918,2024-11-30 14:06:28.154463,https://stackexchange.com/users/30047207/alrey-john
119919,2024-11-30 15:17:35.354805,https://pcgamesn.com
119920,2024-11-30 15:17:58.439183,https://vectorstock.com
119921,2024-11-30 22:56:28.371583,https://nrk.no

Norway, history number 7
Last 5 records

,synthetic_time,synthetic_url
119308,2024-11-30 11:26:59.633331,https://www.lawinsider.com/clause/company-limited
119309,2024-11-30 12:12:37.607418,https://stackexchange.com/users/17066786/oliwia-stam
119310,2024-11-30 13:23:44.807760,https://eurogamer.net
119311,2024-11-30 13:24:07.892138,https://vectorstock.com
119312,2024-11-30 21:02:37.824538,https://nrk.no

Norway, history number 8
Last 5 records

,synthetic_time,synthetic_url
118701,2024-11-30 11:32:36.704893,https://www.wondershare.com/cookies-policy.html
118702,2024-11-30 12:18:14.678980,https://stackexchange.com/users/17066786/oliwia-stam
118703,2024-11-30 13:29:21.879322,https://pcgamer.com
118704,2024-11-30 13:29:44.963700,https://vectorstock.com
118705,2024-11-30 21:08:14.896100,https://nrk.no

Norway, history number 9
Last 5 records

,synthetic_time,synthetic_url
118097,2024-11-30 12:52:32.755260,https://www.wondershare.com/refund-policy.html
118098,2024-11-30 13:38:10.729347,https://stackexchange.com/users/30047207/alrey-john
118099,2024-11-30 14:49:17.929689,https://eurogamer.net
118100,2024-11-30 14:49:41.014067,https://vectorstock.com
118101,2024-11-30 22:28:10.946467,https://nrk.no

Pakistan, history number 0
Last 5 records

,synthetic_time,synthetic_url
117484,2024-11-30 13:23:41.223337,http://www.nsdsoft.net/almadinadik/
117485,2024-11-30 14:09:19.197424,https://www.shopify.com/blog/what-is-intellectual-property
117486,2024-11-30 15:20:26.397766,https://www.lovetoknow.com
117487,2024-11-30 15:20:49.482144,https://varietybooks.pk
117488,2024-11-30 22:59:19.414544,https://rsc.org

Pakistan, history number 1
Last 5 records

,synthetic_time,synthetic_url
116855,2024-11-30 12:35:38.760056,https://www.coinbase.com/converter/socc/eur
116856,2024-11-30 13:21:16.734143,https://www.shopify.com/blog/what-is-intellectual-property
116857,2024-11-30 14:32:23.934485,https://aafp.org
116858,2024-11-30 14:32:47.018863,https://www.wattpad.com/
116859,2024-11-30 22:11:16.951263,https://pennmedicine.org

Pakistan, history number 2
Last 5 records

,synthetic_time,synthetic_url
116225,2024-11-30 12:09:46.147647,https://www.arhamsoft.com/about-us
116226,2024-11-30 12:55:24.121734,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
116227,2024-11-30 14:06:31.322076,https://www.lovetoknow.com
116228,2024-11-30 14:06:54.406454,https://routledge.com
116229,2024-11-30 21:45:24.338854,https://goal.com

Pakistan, history number 3
Last 5 records

,synthetic_time,synthetic_url
115599,2024-11-30 12:00:33.923747,https://quran.com/3/138
115600,2024-11-30 12:46:11.897834,https://www.shopify.com/blog/what-is-intellectual-property
115601,2024-11-30 13:57:19.098176,https://www.lovetoknow.com/
115602,2024-11-30 13:57:42.182554,https://bravoen.com
115603,2024-11-30 21:36:12.114954,https://thequint.com

Pakistan, history number 4
Last 5 records

,synthetic_time,synthetic_url
114973,2024-11-30 13:14:36.609714,https://quran.com/al-araf/34
114974,2024-11-30 14:00:14.583801,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
114975,2024-11-30 15:11:21.784143,https://lovetoknow.com
114976,2024-11-30 15:11:44.868521,https://routledge.com
114977,2024-11-30 22:50:14.800921,https://indiatvnews.com

Pakistan, history number 5
Last 5 records

,synthetic_time,synthetic_url
114344,2024-11-30 12:01:23.547932,https://www.bollywoodshaadis.com/tags/rohit-purohit
114345,2024-11-30 12:47:01.522019,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
114346,2024-11-30 13:58:08.722361,https://aafp.org
114347,2024-11-30 13:58:31.806739,https://routledge.com
114348,2024-11-30 21:37:01.739139,https://livemint.com

Pakistan, history number 6
Last 5 records

,synthetic_time,synthetic_url
113716,2024-11-30 12:30:31.661047,https://quran.com/al-kahf/74
113717,2024-11-30 13:16:09.635134,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
113718,2024-11-30 14:27:16.835476,https://www.lovetoknow.com
113719,2024-11-30 14:27:39.919854,https://www.wattpad.com/
113720,2024-11-30 22:06:09.852254,https://livemint.com

Pakistan, history number 7
Last 5 records

,synthetic_time,synthetic_url
113095,2024-11-30 12:33:56.666660,http://slideplayer.com/slide/4998950/
113096,2024-11-30 13:19:34.640747,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
113097,2024-11-30 14:30:41.841089,https://aafp.org
113098,2024-11-30 14:31:04.925467,https://bravoen.com
113099,2024-11-30 22:09:34.857867,https://pennmedicine.org

Pakistan, history number 8
Last 5 records

,synthetic_time,synthetic_url
112464,2024-11-30 12:55:38.735442,https://quran.com/10/84-86
112465,2024-11-30 13:41:16.709529,https://www.shopify.com/blog/how-to-get-money-to-start-a-business
112466,2024-11-30 14:52:23.909871,https://aafp.org
112467,2024-11-30 14:52:46.994249,https://varietybooks.pk
112468,2024-11-30 22:31:16.926649,https://rsc.org

Pakistan, history number 9
Last 5 records

,synthetic_time,synthetic_url
111836,2024-11-30 13:06:33.515468,https://quran.com/6/143
111837,2024-11-30 13:52:11.489555,https://www.shopify.com/blog/what-is-intellectual-property
111838,2024-11-30 15:03:18.689897,https://lovetoknow.com
111839,2024-11-30 15:03:41.774275,https://www.wattpad.com/
111840,2024-11-30 22:42:11.706675,https://livemint.com

Poland, history number 0
Last 5 records

,synthetic_time,synthetic_url
111202,2024-11-30 12:06:00.272513,https://interviewme.pl/blog/nip
111203,2024-11-30 12:51:38.246600,"https://www.weselezklasa.pl/wynajem-namiotow,18/nowe-miasteczko/"
111204,2024-11-30 14:02:45.446942,https://ubereats.com
111205,2024-11-30 14:03:08.531320,https://redbubble.com
111206,2024-11-30 21:41:38.463720,https://onet.pl

Poland, history number 1
Last 5 records

,synthetic_time,synthetic_url
110595,2024-11-30 13:20:42.361295,https://www.medianauka.pl/tojesc-gajowa
110596,2024-11-30 14:06:20.335382,"https://www.prv.pl/info/domena,czystko.pev.pl"
110597,2024-11-30 15:17:27.535724,https://ubereats.com
110598,2024-11-30 15:17:50.620102,https://redbubble.com
110599,2024-11-30 22:56:20.552502,https://onet.pl

Poland, history number 2
Last 5 records

,synthetic_time,synthetic_url
109998,2024-11-30 11:34:07.554224,https://www.medianauka.pl/karp
109999,2024-11-30 12:19:45.528311,https://www.neonet.pl/do-kuchni/suszarki-do-owocow-warzyw-grzybow.html
110000,2024-11-30 13:30:52.728653,https://ubereats.com
110001,2024-11-30 13:31:15.813031,https://redbubble.com
110002,2024-11-30 21:09:45.745431,https://onet.pl

Poland, history number 3
Last 5 records

,synthetic_time,synthetic_url
109390,2024-11-30 12:15:10.549755,https://www.ang.pl/profil/518199/wpisy
109391,2024-11-30 13:00:48.523842,"https://www.prv.pl/info/domena,retromas.prv.pl"
109392,2024-11-30 14:11:55.724184,https://ubereats.com
109393,2024-11-30 14:12:18.808562,https://redbubble.com
109394,2024-11-30 21:50:48.740962,https://onet.pl

Poland, history number 4
Last 5 records

,synthetic_time,synthetic_url
108784,2024-11-30 12:46:28.663535,https://www.medianauka.pl/koziol-sniezny
108785,2024-11-30 13:32:06.637622,https://www.prv.pl/przejmowanie-domen/?name=gimnazjum57&domain=2
108786,2024-11-30 14:43:13.837964,https://ubereats.com
108787,2024-11-30 14:43:36.922342,https://redbubble.com
108788,2024-11-30 22:22:06.854742,https://onet.pl

Poland, history number 5
Last 5 records

,synthetic_time,synthetic_url
108178,2024-11-30 13:00:00.841789,https://www.gildia.pl/szukaj/osoba/maciej-kur
108179,2024-11-30 13:45:38.815876,"https://www.prv.pl/info/domena,czystko.pev.pl"
108180,2024-11-30 14:56:46.016218,https://shell.com
108181,2024-11-30 14:57:09.100596,https://redbubble.com
108182,2024-11-30 22:35:39.032996,https://onet.pl

Poland, history number 6
Last 5 records

,synthetic_time,synthetic_url
107573,2024-11-30 13:15:39.088821,https://www.medianauka.pl/kruk-tasmanski
107574,2024-11-30 14:01:17.062908,"https://www.prv.pl/domeny-do-przejecia/alfabetycznie,g,3"
107575,2024-11-30 15:12:24.263250,https://shell.com
107576,2024-11-30 15:12:47.347628,https://redbubble.com
107577,2024-11-30 22:51:17.280028,https://onet.pl

Poland, history number 7
Last 5 records

,synthetic_time,synthetic_url
106968,2024-11-30 11:39:30.697971,https://www.jhi.pl/wizyta
106969,2024-11-30 12:25:08.672058,https://home.pl/szkolenie-office365-administrator/
106970,2024-11-30 13:36:15.872400,https://shell.com
106971,2024-11-30 13:36:38.956778,https://redbubble.com
106972,2024-11-30 21:15:08.889178,https://onet.pl

Poland, history number 8
Last 5 records

,synthetic_time,synthetic_url
106365,2024-11-30 13:03:40.291213,https://www.ang.pl/profil/824767
106366,2024-11-30 13:49:18.265300,https://www.prv.pl/przejmowanie-domen/?name=ciepla-woda&domain=2
106367,2024-11-30 15:00:25.465642,https://shell.com
106368,2024-11-30 15:00:48.550020,https://redbubble.com
106369,2024-11-30 22:39:18.482420,https://onet.pl

Poland, history number 9
Last 5 records

,synthetic_time,synthetic_url
105760,2024-11-30 11:34:52.992872,https://www.ang.pl/profil/707936
105761,2024-11-30 12:20:30.966959,https://home.pl/bonus/?ax%5b0%5d=help_o365_1&p=p_1970
105762,2024-11-30 13:31:38.167301,https://shell.com
105763,2024-11-30 13:32:01.251679,https://redbubble.com
105764,2024-11-30 21:10:31.184079,https://onet.pl

Portugal, history number 0
Last 5 records

,synthetic_time,synthetic_url
105156,2024-11-30 13:20:48.572743,https://www.cm-almada.pt/diretorio
105157,2024-11-30 14:06:26.546830,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
105158,2024-11-30 15:17:33.747172,https://www.starbucks.com/
105159,2024-11-30 15:17:56.831550,https://deviantart.com
105160,2024-11-30 22:56:26.763950,https://uefa.com

Portugal, history number 1
Last 5 records

,synthetic_time,synthetic_url
104569,2024-11-30 13:06:51.906399,https://cnpj.biz/59369264000160
104570,2024-11-30 13:52:29.880486,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
104571,2024-11-30 15:03:37.080828,https://www.starbucks.com/
104572,2024-11-30 15:04:00.165206,https://deviantart.com
104573,2024-11-30 22:42:30.097606,https://rtp.pt

Portugal, history number 2
Last 5 records

,synthetic_time,synthetic_url
103975,2024-11-30 11:26:14.457982,https://cnpj.biz/empresas/bari-apulia
103976,2024-11-30 12:11:52.432069,https://stackexchange.com/users/30047207/alrey-john
103977,2024-11-30 13:22:59.632411,https://starbucks.com
103978,2024-11-30 13:23:22.716789,https://deviantart.com
103979,2024-11-30 21:01:52.649189,https://www.scielo.br/

Portugal, history number 3
Last 5 records

,synthetic_time,synthetic_url
103382,2024-11-30 12:50:45.697362,https://www.cm-almada.pt/?page=0
103383,2024-11-30 13:37:10.914316,https://stackexchange.com/users/8442750/unknown-user
103384,2024-11-30 14:48:18.114658,https://www.starbucks.com/
103385,2024-11-30 14:48:41.199036,https://deviantart.com
103386,2024-11-30 22:27:11.131436,https://www.scielo.br/

Portugal, history number 4
Last 5 records

,synthetic_time,synthetic_url
102791,2024-11-30 11:59:17.346192,https://www.cm-almada.pt/conferencia-ruas-vivas
102792,2024-11-30 12:44:55.320279,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
102793,2024-11-30 13:56:02.520621,https://starbucks.com
102794,2024-11-30 13:56:25.604999,https://nike.com
102795,2024-11-30 21:34:55.537399,https://skysports.com

Portugal, history number 5
Last 5 records

,synthetic_time,synthetic_url
102207,2024-11-30 12:16:00.482956,https://cnpj.biz/empresas/luxemburgo-lu
102208,2024-11-30 13:01:38.457043,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
102209,2024-11-30 14:12:45.657385,https://www.starbucks.com/
102210,2024-11-30 14:13:08.741763,https://redbubble.com
102211,2024-11-30 21:51:38.674163,https://skysports.com

Portugal, history number 6
Last 5 records

,synthetic_time,synthetic_url
101630,2024-11-30 12:13:26.117239,https://cnpj.biz/01276838000175
101631,2024-11-30 12:59:04.091326,https://stackexchange.com/users/13438166/vin%c3%adcius-f%c3%a9lix
101632,2024-11-30 14:10:11.291668,https://www.starbucks.com/
101633,2024-11-30 14:10:34.376046,https://nike.com
101634,2024-11-30 21:49:04.308446,https://skysports.com

Portugal, history number 7
Last 5 records

,synthetic_time,synthetic_url
101045,2024-11-30 11:36:34.241110,https://www.cm-almada.pt/museus/casa-com-jardim
101046,2024-11-30 12:22:12.215197,https://stackexchange.com/users/14097039/gustavo-luiz-bispo-dos-santos
101047,2024-11-30 13:33:19.415539,https://www.starbucks.com/
101048,2024-11-30 13:33:42.499917,https://365scores.com
101049,2024-11-30 21:12:12.432317,https://rtp.pt

Portugal, history number 8
Last 5 records

,synthetic_time,synthetic_url
100452,2024-11-30 12:58:41.854413,https://www.cm-almada.pt/conferencia-ruas-vivas
100453,2024-11-30 13:44:19.828500,https://stackexchange.com/users/23211477/phoenix-in-the-air
100454,2024-11-30 14:55:27.028842,https://starbucks.com
100455,2024-11-30 14:55:50.113220,https://redbubble.com
100456,2024-11-30 22:34:20.045620,https://scielo.br

Portugal, history number 9
Last 5 records

,synthetic_time,synthetic_url
99864,2024-11-30 13:19:00.919360,https://cnpj.biz/01276838000175
99865,2024-11-30 14:04:38.893447,https://stackexchange.com/users/17066786/oliwia-stam
99866,2024-11-30 15:15:46.093789,https://www.starbucks.com/
99867,2024-11-30 15:16:09.178167,https://redbubble.com
99868,2024-11-30 22:54:39.110567,https://scielo.br

Romania, history number 0
Last 5 records

,synthetic_time,synthetic_url
99271,2024-11-30 13:14:14.989533,https://www.universuljuridic.ro/page/2226/
99272,2024-11-30 13:59:52.963620,https://stackoverflow.com/users/633802/mattypants?tab=profile
99273,2024-11-30 15:11:00.163962,https://pcgamer.com
99274,2024-11-30 15:11:23.248340,https://shazam.com
99275,2024-11-30 22:49:53.180740,https://olx.ro

Romania, history number 1
Last 5 records

,synthetic_time,synthetic_url
98711,2024-11-30 12:31:06.400351,https://www.vodafone.ro/serviciifixe/one
98712,2024-11-30 13:16:44.374438,https://stackoverflow.com/users/3864926/bret-van-putten
98713,2024-11-30 14:27:51.574780,https://gamesradar.com
98714,2024-11-30 14:28:14.659158,https://shazam.com
98715,2024-11-30 22:06:44.591558,https://olx.ro

Romania, history number 2
Last 5 records

,synthetic_time,synthetic_url
98159,2024-11-30 13:13:16.787055,https://www.vodafone.ro/pentruromania
98160,2024-11-30 13:58:54.761142,https://stackoverflow.com/users/12323550/kristen?tab=tags
98161,2024-11-30 15:10:01.961484,https://pcgamer.com
98162,2024-11-30 15:10:25.045862,https://shazam.com
98163,2024-11-30 22:48:54.978262,https://olx.ro

Romania, history number 3
Last 5 records

,synthetic_time,synthetic_url
97600,2024-11-30 11:29:37.546825,https://www.vodafone.ro/pentruromania
97601,2024-11-30 12:15:15.520912,https://stackoverflow.com/users/4953216/kevin-hammet
97602,2024-11-30 13:26:22.721254,https://gamesradar.com
97603,2024-11-30 13:26:45.805632,https://shazam.com
97604,2024-11-30 21:05:15.738032,https://olx.ro

Romania, history number 4
Last 5 records

,synthetic_time,synthetic_url
97035,2024-11-30 12:23:35.865112,https://www.universuljuridic.ro/page/2226/
97036,2024-11-30 13:09:13.839199,https://stackoverflow.com/help/badges/6/supporter?userid=14602915
97037,2024-11-30 14:20:21.039541,https://gamesradar.com
97038,2024-11-30 14:20:44.123919,https://disneyplus.com
97039,2024-11-30 21:59:14.056319,https://olx.ro

Romania, history number 5
Last 5 records

,synthetic_time,synthetic_url
96463,2024-11-30 12:46:59.970722,https://www.universuljuridic.ro/page/2226/
96464,2024-11-30 13:32:37.944809,https://stackoverflow.com/users/1272950/y%c7%9ds%ca%9e%c7%9dla
96465,2024-11-30 14:43:45.145151,https://gamesradar.com
96466,2024-11-30 14:44:08.229529,https://shazam.com
96467,2024-11-30 22:22:38.161929,https://olx.ro

Romania, history number 6
Last 5 records

,synthetic_time,synthetic_url
95896,2024-11-30 13:13:44.036269,https://www.universuljuridic.ro/autor/raul-hodos/
95897,2024-11-30 13:59:22.010356,https://stackoverflow.com/users/4953216/kevin-hammet
95898,2024-11-30 15:10:29.210698,https://gamesradar.com
95899,2024-11-30 15:10:52.295076,https://shazam.com
95900,2024-11-30 22:49:22.227476,https://olx.ro

Romania, history number 7
Last 5 records

,synthetic_time,synthetic_url
95334,2024-11-30 13:04:07.913194,https://www.vodafone.ro/pentruromania
95335,2024-11-30 13:49:45.887281,https://stackoverflow.com/users/3864926/bret-van-putten
95336,2024-11-30 15:00:53.087623,https://pcgamer.com
95337,2024-11-30 15:01:16.172001,https://disneyplus.com
95338,2024-11-30 22:39:46.104401,https://olx.ro

Romania, history number 8
Last 5 records

,synthetic_time,synthetic_url
94776,2024-11-30 13:05:28.806393,https://www.vodafone.ro/pentruromania
94777,2024-11-30 13:51:06.780480,https://stackoverflow.com/users/633802/mattypants?tab=profile
94778,2024-11-30 15:02:13.980822,https://gamesradar.com
94779,2024-11-30 15:02:37.065200,https://disneyplus.com
94780,2024-11-30 22:41:06.997600,https://olx.ro

Romania, history number 9
Last 5 records

,synthetic_time,synthetic_url
94215,2024-11-30 13:06:33.404325,https://www.universuljuridic.ro/autor/giulia-sologon/
94216,2024-11-30 13:52:11.378412,https://stackoverflow.com/help/badges/1/teacher?userid=16446
94217,2024-11-30 15:03:18.578754,https://pcgamer.com
94218,2024-11-30 15:03:41.663132,https://disneyplus.com
94219,2024-11-30 22:42:11.595532,https://olx.ro

Saudi_Arabia, history number 0
Last 5 records

,synthetic_time,synthetic_url
93657,2024-11-30 12:35:42.140315,https://apkpure.net/terms.html
93658,2024-11-30 13:22:52.595805,https://www.adslgate.com/user_threads.php?u=830864
93659,2024-11-30 14:33:59.796147,https://www.loccitane.com/
93660,2024-11-30 14:34:22.880525,https://ninewest.com
93661,2024-11-30 22:12:52.812925,https://zawya.com

Saudi_Arabia, history number 1
Last 5 records

,synthetic_time,synthetic_url
93042,2024-11-30 11:47:10.463924,https://apkpure.net/terms.html
93043,2024-11-30 12:34:20.919414,https://www.adslgate.com/profile.php?userid=929873
93044,2024-11-30 13:45:28.119756,https://subway.com
93045,2024-11-30 13:45:51.204134,https://ninewest.com
93046,2024-11-30 21:24:21.136534,https://aljazeera.net

Saudi_Arabia, history number 2
Last 5 records

,synthetic_time,synthetic_url
92418,2024-11-30 12:10:37.319757,https://apkpure.net/terms.html
92419,2024-11-30 12:57:47.775247,https://www.adslgate.com/profile.php?userid=205290
92420,2024-11-30 14:08:54.975589,https://www.loccitane.com/
92421,2024-11-30 14:09:18.059967,https://ninewest.com
92422,2024-11-30 21:47:47.992367,https://aljazeera.net

Saudi_Arabia, history number 3
Last 5 records

,synthetic_time,synthetic_url
91794,2024-11-30 11:23:14.325059,https://apkpure.net/terms.html
91795,2024-11-30 12:10:24.780549,https://www.adslgate.com/user_threads.php?u=544952
91796,2024-11-30 13:21:31.980891,https://www.loccitane.com/
91797,2024-11-30 13:21:55.065269,https://ninewest.com
91798,2024-11-30 21:00:24.997669,https://zawya.com

Saudi_Arabia, history number 4
Last 5 records

,synthetic_time,synthetic_url
91173,2024-11-30 12:30:30.264360,https://apkpure.net/terms.html
91174,2024-11-30 13:17:40.719850,https://www.adslgate.com/profile.php?userid=694090
91175,2024-11-30 14:28:47.920192,https://www.loccitane.com/
91176,2024-11-30 14:29:11.004570,https://ninewest.com
91177,2024-11-30 22:07:40.936970,https://sportskeeda.com

Saudi_Arabia, history number 5
Last 5 records

,synthetic_time,synthetic_url
90554,2024-11-30 13:09:17.948510,https://apkpure.net/terms.html
90555,2024-11-30 13:56:28.404000,https://www.adslgate.com/user_threads.php?u=625409
90556,2024-11-30 15:07:35.604342,https://bestbuy.com
90557,2024-11-30 15:07:58.688720,https://ninewest.com
90558,2024-11-30 22:46:28.621120,https://zawya.com

Saudi_Arabia, history number 6
Last 5 records

,synthetic_time,synthetic_url
89942,2024-11-30 11:34:58.325326,https://apkpure.net/terms.html
89943,2024-11-30 12:22:08.780816,https://www.adslgate.com/profile.php?userid=96544
89944,2024-11-30 13:33:15.981158,https://bestbuy.com
89945,2024-11-30 13:33:39.065536,https://ninewest.com
89946,2024-11-30 21:12:08.997936,https://goal.com

Saudi_Arabia, history number 7
Last 5 records

,synthetic_time,synthetic_url
89323,2024-11-30 13:06:29.128667,https://apkpure.net/terms.html
89324,2024-11-30 13:53:39.584157,https://www.adslgate.com/profile.php?userid=250981
89325,2024-11-30 15:04:46.784499,https://www.loccitane.com/
89326,2024-11-30 15:05:09.868877,https://ninewest.com
89327,2024-11-30 22:43:39.801277,https://goal.com

Saudi_Arabia, history number 8
Last 5 records

,synthetic_time,synthetic_url
88695,2024-11-30 12:53:32.783090,https://apkpure.net/terms.html
88696,2024-11-30 13:40:43.238580,https://www.hindawi.org/books/categories/detective.fiction/4/
88697,2024-11-30 14:51:50.438922,https://dhl.com
88698,2024-11-30 14:52:13.523300,https://ninewest.com
88699,2024-11-30 22:30:43.455700,https://goal.com

Saudi_Arabia, history number 9
Last 5 records

,synthetic_time,synthetic_url
88079,2024-11-30 11:29:02.110865,https://apkpure.net/terms.html
88080,2024-11-30 12:16:12.566355,https://www.adslgate.com/profile.php?userid=205290
88081,2024-11-30 13:27:19.766697,https://www.loccitane.com/
88082,2024-11-30 13:27:42.851075,https://ninewest.com
88083,2024-11-30 21:06:12.783475,https://sportskeeda.com

Serbia, history number 0
Last 5 records

,synthetic_time,synthetic_url
87452,2024-11-30 13:26:19.990006,http://www.bgprevoz.rs/linije/aktuelne-izmene
87453,2024-11-30 14:11:57.964093,https://pdfcoffee.com/hermann-hesse-demian-pdf-free.html
87454,2024-11-30 15:23:05.164435,https://gamesradar.com
87455,2024-11-30 15:23:28.248813,https://wattpad.com
87456,2024-11-30 23:01:58.181213,https://uefa.com

Serbia, history number 1
Last 5 records

,synthetic_time,synthetic_url
86811,2024-11-30 12:31:24.953636,https://stackoverflow.com/users/182072/ewan-todd
86812,2024-11-30 13:17:02.927723,https://github.com/ropod-project/ropod_experiment_executor
86813,2024-11-30 14:28:10.128065,https://tomsguide.com
86814,2024-11-30 14:28:33.212443,https://coolshop.rs
86815,2024-11-30 22:07:03.144843,https://uefa.com

Serbia, history number 2
Last 5 records

,synthetic_time,synthetic_url
86172,2024-11-30 12:10:03.791569,https://www.gohome.rs/kuce+novi+sad/page3/
86173,2024-11-30 12:55:41.765656,https://pdfcoffee.com/trinity-syllabus-piano-5-pdf-free.html
86174,2024-11-30 14:06:48.965998,https://gamesradar.com
86175,2024-11-30 14:07:12.050376,https://wattpad.com
86176,2024-11-30 21:45:41.982776,https://uefa.com

Serbia, history number 3
Last 5 records

,synthetic_time,synthetic_url
85528,2024-11-30 12:15:04.371245,https://www.rt-rk.com/rt-rk-tech-day/
85529,2024-11-30 13:00:42.345332,https://pdfcoffee.com/trinity-syllabus-piano-5-pdf-free.html
85530,2024-11-30 14:11:49.545674,https://tomsguide.com
85531,2024-11-30 14:12:12.630052,https://tubitv.com
85532,2024-11-30 21:50:42.562452,https://uefa.com

Serbia, history number 4
Last 5 records

,synthetic_time,synthetic_url
84887,2024-11-30 12:32:33.103097,https://www.lektire.rs/ratar-veljko-petrovic/
84888,2024-11-30 13:18:11.077184,https://github.com/ropod-project/ropod_experiment_executor
84889,2024-11-30 14:29:18.277526,https://gamesradar.com
84890,2024-11-30 14:29:41.361904,https://coolshop.rs
84891,2024-11-30 22:08:11.294304,https://b92.net

Serbia, history number 5
Last 5 records

,synthetic_time,synthetic_url
84248,2024-11-30 11:29:09.524764,https://www.rt-rk.com/novi-sad-office/
84249,2024-11-30 12:14:47.498851,https://pdfcoffee.com/ipc-notes-5-pdf-free.html
84250,2024-11-30 13:25:54.699193,https://gamesradar.com
84251,2024-11-30 13:26:17.783571,https://coolshop.rs
84252,2024-11-30 21:04:47.715971,https://b92.net

Serbia, history number 6
Last 5 records

,synthetic_time,synthetic_url
83609,2024-11-30 12:19:06.475360,https://www.lektire.rs/izbiracica-knjiga/
83610,2024-11-30 13:04:44.449447,https://github.com/tutao/tutanota/issues/1579
83611,2024-11-30 14:15:51.649789,https://tomsguide.com
83612,2024-11-30 14:16:14.734167,https://coolshop.rs
83613,2024-11-30 21:54:44.666567,https://b92.net

Serbia, history number 7
Last 5 records

,synthetic_time,synthetic_url
82969,2024-11-30 13:17:32.701026,https://www.rt-rk.com/novi-sad-office/
82970,2024-11-30 14:03:10.675113,https://pdfcoffee.com/calculation-of-pump-pdf-free.html
82971,2024-11-30 15:14:17.875455,https://gamesradar.com
82972,2024-11-30 15:14:40.959833,https://www.wattpad.com/
82973,2024-11-30 22:53:10.892233,https://www.b92.net/

Serbia, history number 8
Last 5 records

,synthetic_time,synthetic_url
82326,2024-11-30 12:29:10.308943,https://bgprevoz.rs/linije/vanredne-izmene
82327,2024-11-30 13:14:48.283030,https://github.com/battlesnakeofficial/rules
82328,2024-11-30 14:25:55.483372,https://gamesradar.com
82329,2024-11-30 14:26:18.567750,https://tubitv.com
82330,2024-11-30 22:04:48.500150,https://www.b92.net/

Serbia, history number 9
Last 5 records

,synthetic_time,synthetic_url
81683,2024-11-30 12:01:13.537295,https://www.lektire.rs/kalenic-vasko-popa/
81684,2024-11-30 12:46:51.511382,https://github.com/tutao/tutanota/issues/1579
81685,2024-11-30 13:57:58.711724,https://gamesradar.com
81686,2024-11-30 13:58:21.796102,https://wattpad.com
81687,2024-11-30 21:36:51.728502,https://www.b92.net/

Singapore, history number 0
Last 5 records

,synthetic_time,synthetic_url
81045,2024-11-30 11:53:33.996272,https://pasttenses.com/one-accord-synonyms
81046,2024-11-30 12:39:11.970359,https://mashable.com/article/westworld-rick-roll
81047,2024-11-30 13:50:19.170701,https://everydayhealth.com
81048,2024-11-30 13:50:42.255079,https://www.pinkvilla.com/
81049,2024-11-30 21:29:12.187479,https://skysports.com

Singapore, history number 1
Last 5 records

,synthetic_time,synthetic_url
80410,2024-11-30 11:50:15.431520,https://pasttenses.com/speak-synonyms
80411,2024-11-30 12:35:53.405607,https://www.howstuffworks.com/howstuffworks-newsletter-riddle42.htm
80412,2024-11-30 13:47:00.605949,https://everydayhealth.com
80413,2024-11-30 13:47:23.690327,https://pinkvilla.com
80414,2024-11-30 21:25:53.622727,https://omnicalculator.com

Singapore, history number 2
Last 5 records

,synthetic_time,synthetic_url
79782,2024-11-30 11:50:48.997727,https://pasttenses.com/speak-synonyms
79783,2024-11-30 12:36:26.971814,https://www.state.gov/report/custom/0289093b77/
79784,2024-11-30 13:47:34.172156,https://everydayhealth.com
79785,2024-11-30 13:47:57.256534,https://www.pinkvilla.com/
79786,2024-11-30 21:26:27.188934,https://skysports.com

Singapore, history number 3
Last 5 records

,synthetic_time,synthetic_url
79151,2024-11-30 12:42:05.144316,https://pasttenses.com/subdue-synonyms
79152,2024-11-30 13:27:43.118403,https://mashable.com/article/westworld-rick-roll
79153,2024-11-30 14:38:50.318745,https://everydayhealth.com
79154,2024-11-30 14:39:13.403123,https://www.pinkvilla.com/
79155,2024-11-30 22:17:43.335523,https://omnicalculator.com

Singapore, history number 4
Last 5 records

,synthetic_time,synthetic_url
78524,2024-11-30 12:41:58.636911,https://thecontentauthority.com/blog/enclave-vs-exclave
78525,2024-11-30 13:27:36.610998,https://mashable.com/article/amazon-music-integrates-with-audi
78526,2024-11-30 14:38:43.811340,https://everydayhealth.com
78527,2024-11-30 14:39:06.895718,https://www.pinkvilla.com/
78528,2024-11-30 22:17:36.828118,https://omnicalculator.com

Singapore, history number 5
Last 5 records

,synthetic_time,synthetic_url
77892,2024-11-30 13:23:11.839441,https://pasttenses.com/apt-synonyms
77893,2024-11-30 14:08:49.813528,https://www.howstuffworks.com/howstuffworks-newsletter-riddle22.htm
77894,2024-11-30 15:19:57.013870,https://everydayhealth.com
77895,2024-11-30 15:20:20.098248,https://fresha.com
77896,2024-11-30 22:58:50.030648,https://skysports.com

Singapore, history number 6
Last 5 records

,synthetic_time,synthetic_url
77262,2024-11-30 12:29:44.850357,https://pasttenses.com/subdue-synonyms
77263,2024-11-30 13:15:22.824444,https://www.state.gov/public-schedule-august-2-2023
77264,2024-11-30 14:26:30.024786,https://everydayhealth.com
77265,2024-11-30 14:26:53.109164,https://fresha.com
77266,2024-11-30 22:05:23.041564,https://skysports.com

Singapore, history number 7
Last 5 records

,synthetic_time,synthetic_url
76639,2024-11-30 13:17:43.575271,https://pasttenses.com/stampeding-synonyms
76640,2024-11-30 14:03:21.549358,https://www.howstuffworks.com/howstuffworks-newsletter-riddle26.htm
76641,2024-11-30 15:14:28.749700,https://everydayhealth.com
76642,2024-11-30 15:14:51.834078,https://pinkvilla.com
76643,2024-11-30 22:53:21.766478,https://omnicalculator.com

Singapore, history number 8
Last 5 records

,synthetic_time,synthetic_url
76007,2024-11-30 13:13:03.023972,https://thecontentauthority.com/blog/virtual-vs-digital
76008,2024-11-30 13:58:40.998059,https://mashable.com/deals/july-27-theragun-pro
76009,2024-11-30 15:09:48.198401,https://everydayhealth.com
76010,2024-11-30 15:10:11.282779,https://www.pinkvilla.com/
76011,2024-11-30 22:48:41.215179,https://skysports.com

Singapore, history number 9
Last 5 records

,synthetic_time,synthetic_url
75375,2024-11-30 11:49:30.771404,https://pasttenses.com/befang-past-tense
75376,2024-11-30 12:35:08.745491,https://mashable.com/article/ios-11-iphone-storage
75377,2024-11-30 13:46:15.945833,https://everydayhealth.com
75378,2024-11-30 13:46:39.030211,https://www.pinkvilla.com/
75379,2024-11-30 21:25:08.962611,https://omnicalculator.com

Slovakia, history number 0
Last 5 records

,synthetic_time,synthetic_url
74746,2024-11-30 11:53:53.207892,https://www.banskastiavnica.sk/potrebujem-vybavit/
74747,2024-11-30 12:40:18.424846,https://www.packeta.sk/blog/simona-kijonkova-odchadza-z-vedenia-packety
74748,2024-11-30 13:51:25.625188,https://kayak.com
74749,2024-11-30 13:51:48.709566,https://revngo.com
74750,2024-11-30 21:30:18.641966,https://pravda.sk

Slovakia, history number 1
Last 5 records

,synthetic_time,synthetic_url
74109,2024-11-30 13:06:14.654603,https://www.banskastiavnica.sk/potrebujem-vybavit/
74110,2024-11-30 13:51:52.628690,https://www.packeta.sk/pobocky/pisek-na-rozhledne-2698-1
74111,2024-11-30 15:02:59.829032,https://kayak.com
74112,2024-11-30 15:03:22.913410,https://revngo.com
74113,2024-11-30 22:41:52.845810,https://pravda.sk

Slovakia, history number 2
Last 5 records

,synthetic_time,synthetic_url
73471,2024-11-30 11:59:58.813094,https://www.petrzalka.sk/socialne-veci/page/4/
73472,2024-11-30 12:45:36.787181,https://www.packeta.sk/pobocky/volary-prachaticka
73473,2024-11-30 13:56:43.987523,https://gamesradar.com
73474,2024-11-30 13:57:07.071901,https://revngo.com
73475,2024-11-30 21:35:37.004301,https://pravda.sk

Slovakia, history number 3
Last 5 records

,synthetic_time,synthetic_url
72837,2024-11-30 12:47:30.142390,https://www.petrzalka.sk/zbernydvor/
72838,2024-11-30 13:33:08.116477,https://www.birdz.sk/forum/dnes-som-striekal/196812-tema.html
72839,2024-11-30 14:44:15.316819,https://kayak.com
72840,2024-11-30 14:44:38.401197,https://revngo.com
72841,2024-11-30 22:23:08.333597,https://pravda.sk

Slovakia, history number 4
Last 5 records

,synthetic_time,synthetic_url
72196,2024-11-30 12:05:03.364216,https://www.petrzalka.sk/zbernydvor/
72197,2024-11-30 12:50:41.338303,https://www.techbox.sk/leica-x2-taky-nie-uplne-bezny-kompakt
72198,2024-11-30 14:01:48.538645,https://kayak.com
72199,2024-11-30 14:02:11.623023,https://revngo.com
72200,2024-11-30 21:40:41.555423,https://pravda.sk

Slovakia, history number 5
Last 5 records

,synthetic_time,synthetic_url
71562,2024-11-30 12:06:04.423709,https://www.petrzalka.sk/zbernydvor/
71563,2024-11-30 12:52:58.179487,https://nbs.sk/vyskum/zoznam-autorov/zelenak-karol/
71564,2024-11-30 14:04:05.379829,https://gamesradar.com
71565,2024-11-30 14:04:28.464207,https://revngo.com
71566,2024-11-30 21:42:58.396607,https://pravda.sk

Slovakia, history number 6
Last 5 records

,synthetic_time,synthetic_url
70925,2024-11-30 13:08:41.956632,https://www.banskastiavnica.sk/potrebujem-vybavit/
70926,2024-11-30 13:55:07.173586,https://www.birdz.sk/karlotiskot/obrazok/-d/1090748-foto.html
70927,2024-11-30 15:06:14.373928,https://gamesradar.com
70928,2024-11-30 15:06:37.458306,https://revngo.com
70929,2024-11-30 22:45:07.390706,https://pravda.sk

Slovakia, history number 7
Last 5 records

,synthetic_time,synthetic_url
70293,2024-11-30 12:34:15.146223,https://www.petrzalka.sk/socialne-veci/page/4/
70294,2024-11-30 13:19:53.120310,https://www.packeta.sk/pobocky/borsov-nad-vltavou-poricska-699
70295,2024-11-30 14:31:00.320652,https://gamesradar.com
70296,2024-11-30 14:31:23.405030,https://revngo.com
70297,2024-11-30 22:09:53.337430,https://pravda.sk

Slovakia, history number 8
Last 5 records

,synthetic_time,synthetic_url
69650,2024-11-30 12:33:56.363200,https://www.petrzalka.sk/socialne-veci/page/4/
69651,2024-11-30 13:19:34.337287,https://nbs.sk/financna-stabilita/nastroje-fs/
69652,2024-11-30 14:30:41.537629,https://gamesradar.com
69653,2024-11-30 14:31:04.622007,https://revngo.com
69654,2024-11-30 22:09:34.554407,https://pravda.sk

Slovakia, history number 9
Last 5 records

,synthetic_time,synthetic_url
69015,2024-11-30 11:56:30.336350,https://www.petrzalka.sk/zbernydvor/
69016,2024-11-30 12:42:08.310437,https://www.birdz.sk/pubertslatinocelny/albumy
69017,2024-11-30 13:53:15.510779,https://gamesradar.com
69018,2024-11-30 13:53:38.595157,https://revngo.com
69019,2024-11-30 21:32:08.527557,https://pravda.sk

Slovenia, history number 0
Last 5 records

,synthetic_time,synthetic_url
68377,2024-11-30 12:02:40.746733,https://www.piran.si/objava/949560
68378,2024-11-30 12:48:18.720820,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
68379,2024-11-30 13:59:25.921162,https://medicalnewstoday.com
68380,2024-11-30 13:59:49.005540,https://bananaway.si
68381,2024-11-30 21:38:18.937940,https://usmagazine.com

Slovenia, history number 1
Last 5 records

,synthetic_time,synthetic_url
67742,2024-11-30 12:40:29.830955,https://www.piran.si/objava/963371
67743,2024-11-30 13:26:07.805042,https://www.dictionary.com/e/love-adding-emoji-dictionary/
67744,2024-11-30 14:37:15.005384,https://aeroklub-jk-ajdovscina.si
67745,2024-11-30 14:37:38.089762,https://bananaway.si
67746,2024-11-30 22:16:08.022162,https://transfermarkt.com

Slovenia, history number 2
Last 5 records

,synthetic_time,synthetic_url
67111,2024-11-30 11:24:32.638049,https://piran.si/objava/965363
67112,2024-11-30 12:10:10.612136,https://www.digitaltrends.com/home/philips-hue-debuts-its-new-app/
67113,2024-11-30 13:21:17.812478,https://kitajski-vrt.com
67114,2024-11-30 13:21:40.896856,https://bananaway.si
67115,2024-11-30 21:00:10.829256,https://allevents.in

Slovenia, history number 3
Last 5 records

,synthetic_time,synthetic_url
66480,2024-11-30 12:32:05.707469,https://www.piran.si/objava/949560
66481,2024-11-30 13:17:43.681556,https://www.digitaltrends.com/mobile/best-samsung-galaxy-note-20-cases/
66482,2024-11-30 14:28:50.881898,https://gamespot.com
66483,2024-11-30 14:29:13.966276,https://tubitv.com
66484,2024-11-30 22:07:43.898676,https://usmagazine.com

Slovenia, history number 4
Last 5 records

,synthetic_time,synthetic_url
65847,2024-11-30 13:09:58.559903,https://piran.si/objava/770308
65848,2024-11-30 13:55:36.533990,https://www.digitaltrends.com/computing/acer-unveils-aspire-p3-ultrabook/
65849,2024-11-30 15:06:43.734332,https://timeout.com
65850,2024-11-30 15:07:06.818710,https://bananaway.si
65851,2024-11-30 22:45:36.751110,https://cbssports.com

Slovenia, history number 5
Last 5 records

,synthetic_time,synthetic_url
65209,2024-11-30 13:08:25.672959,https://piran.si/objava/965026
65210,2024-11-30 13:54:03.647046,https://www.dictionary.com/e/word-of-the-day/intercalary-2020-02-29/
65211,2024-11-30 15:05:10.847388,https://medicalnewstoday.com
65212,2024-11-30 15:05:33.931766,https://empireonline.com
65213,2024-11-30 22:44:03.864166,https://transfermarkt.com

Slovenia, history number 6
Last 5 records

,synthetic_time,synthetic_url
64575,2024-11-30 13:08:03.889385,https://www.piran.si/objava/790098
64576,2024-11-30 13:53:41.863472,https://www.digitaltrends.com/dtdeals/roku-ultra-deal-cyber-monday-2020/
64577,2024-11-30 15:04:49.063814,https://timeout.com
64578,2024-11-30 15:05:12.148192,https://empireonline.com
64579,2024-11-30 22:43:42.080592,https://allevents.in

Slovenia, history number 7
Last 5 records

,synthetic_time,synthetic_url
63944,2024-11-30 11:28:10.072211,https://www.koper.si/regulation/un-kamnolom/
63945,2024-11-30 12:13:48.046298,https://www.digitaltrends.com/news/spacex-nasa-crewed-launch/
63946,2024-11-30 13:24:55.246640,https://urbandictionary.com
63947,2024-11-30 13:25:18.331018,https://empireonline.com
63948,2024-11-30 21:03:48.263418,https://transfermarkt.com

Slovenia, history number 8
Last 5 records

,synthetic_time,synthetic_url
63312,2024-11-30 12:41:22.461814,https://www.nova-gorica.si/mestni-svet/
63313,2024-11-30 13:27:00.435901,https://www.digitaltrends.com/mobile/apple-watch-sales-november/
63314,2024-11-30 14:38:07.636243,https://lassana.si
63315,2024-11-30 14:38:30.720621,https://tubitv.com
63316,2024-11-30 22:17:00.653021,https://transfermarkt.com

Slovenia, history number 9
Last 5 records

,synthetic_time,synthetic_url
62686,2024-11-30 12:23:41.604710,https://www.piran.si/objava/798231
62687,2024-11-30 13:09:19.578797,https://www.digitaltrends.com/dtdeals/roku-ultra-deal-cyber-monday-2020/
62688,2024-11-30 14:20:26.779139,https://aeroklub-jk-ajdovscina.si
62689,2024-11-30 14:20:49.863517,https://empireonline.com
62690,2024-11-30 21:59:19.795917,https://cbssports.com

Spain, history number 0
Last 5 records

,synthetic_time,synthetic_url
62050,2024-11-30 13:05:14.566189,https://www.tuexperto.com/category/spam/
62051,2024-11-30 13:52:25.021679,https://unsplash.com/photos/person-walking-on-desert-tejvysibyi4
62052,2024-11-30 15:03:32.222021,https://rentalia.com
62053,2024-11-30 15:03:55.306399,https://jiosaavn.com
62054,2024-11-30 22:42:25.238799,https://tiktok.com

Spain, history number 1
Last 5 records

,synthetic_time,synthetic_url
61444,2024-11-30 13:21:36.278180,https://www.tuexperto.com/category/spam/
61445,2024-11-30 14:08:46.733670,https://www.canva.com/es_mx/plantillas/s/catalogos/
61446,2024-11-30 15:19:53.934012,https://rentalia.com
61447,2024-11-30 15:20:17.018390,https://jiosaavn.com
61448,2024-11-30 22:58:46.950790,https://tiktok.com

Spain, history number 2
Last 5 records

,synthetic_time,synthetic_url
60838,2024-11-30 13:11:07.971547,https://www.tuexperto.com/category/spam/
60839,2024-11-30 13:58:18.427037,https://www.canva.com/colors/color-palettes/camera-ready/
60840,2024-11-30 15:09:25.627379,https://rentalia.com
60841,2024-11-30 15:09:48.711757,https://jiosaavn.com
60842,2024-11-30 22:48:18.644157,https://tiktok.com

Spain, history number 3
Last 5 records

,synthetic_time,synthetic_url
60239,2024-11-30 13:20:03.891520,https://www.tuexperto.com/category/spam/
60240,2024-11-30 14:07:14.347010,https://www.canva.com/hu_hu/help/team-banner-logo/
60241,2024-11-30 15:18:21.547352,https://colegiotresolivos.org
60242,2024-11-30 15:18:44.631730,https://jiosaavn.com
60243,2024-11-30 22:57:14.564130,https://tiktok.com

Spain, history number 4
Last 5 records

,synthetic_time,synthetic_url
59640,2024-11-30 12:50:00.460633,https://www.tuexperto.com/category/spam/
59641,2024-11-30 13:37:10.916123,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
59642,2024-11-30 14:48:18.116465,https://colegiotresolivos.org
59643,2024-11-30 14:48:41.200843,https://jiosaavn.com
59644,2024-11-30 22:27:11.133243,https://tiktok.com

Spain, history number 5
Last 5 records

,synthetic_time,synthetic_url
59043,2024-11-30 13:30:13.748644,https://www.tuexperto.com/category/spam/
59044,2024-11-30 14:17:24.204134,https://unsplash.com/photos/a-close-up-of-some-bamboo-prulk09dyho
59045,2024-11-30 15:28:31.404476,https://colegiotresolivos.org
59046,2024-11-30 15:28:54.488854,https://jiosaavn.com
59047,2024-11-30 23:07:24.421254,https://tiktok.com

Spain, history number 6
Last 5 records

,synthetic_time,synthetic_url
58439,2024-11-30 12:37:27.268901,https://www.tuexperto.com/category/spam/
58440,2024-11-30 13:24:37.724391,https://www.canva.com/tr_tr/help/using-blackboard-lms/
58441,2024-11-30 14:35:44.924733,https://colegiotresolivos.org
58442,2024-11-30 14:36:08.009111,https://jiosaavn.com
58443,2024-11-30 22:14:37.941511,https://tiktok.com

Spain, history number 7
Last 5 records

,synthetic_time,synthetic_url
57837,2024-11-30 11:59:36.056498,https://www.tuexperto.com/category/spam/
57838,2024-11-30 12:46:46.511988,https://unsplash.com/photos/cactus-potted-plant-uoo0iklxpb8
57839,2024-11-30 13:57:53.712330,https://colegiotresolivos.org
57840,2024-11-30 13:58:16.796708,https://jiosaavn.com
57841,2024-11-30 21:36:46.729108,https://tiktok.com

Spain, history number 8
Last 5 records

,synthetic_time,synthetic_url
57232,2024-11-30 11:31:16.259467,https://www.tuexperto.com/category/spam/
57233,2024-11-30 12:18:26.714957,https://www.canva.com/ar_eg/graphs/flowcharts/
57234,2024-11-30 13:29:33.915299,https://colegiotresolivos.org
57235,2024-11-30 13:29:56.999677,https://jiosaavn.com
57236,2024-11-30 21:08:26.932077,https://tiktok.com

Spain, history number 9
Last 5 records

,synthetic_time,synthetic_url
56635,2024-11-30 13:14:48.907003,https://www.tuexperto.com/category/spam/
56636,2024-11-30 14:01:59.362493,https://www.canva.com/pl_pl/help/connect-to-moodle/
56637,2024-11-30 15:13:06.562835,https://rentalia.com
56638,2024-11-30 15:13:29.647213,https://jiosaavn.com
56639,2024-11-30 22:51:59.579613,https://tiktok.com

Sri_Lanka, history number 0
Last 5 records

,synthetic_time,synthetic_url
56030,2024-11-30 13:31:09.773196,https://everydaypower.com/fountainhead-quotes/
56031,2024-11-30 14:16:47.747283,https://www.udemy.com/course/sales-leadership/
56032,2024-11-30 15:27:54.947625,https://ef.com
56033,2024-11-30 15:28:18.032003,https://bollywoodhungama.com
56034,2024-11-30 23:06:47.964403,https://sportingnews.com

Sri_Lanka, history number 1
Last 5 records

,synthetic_time,synthetic_url
55417,2024-11-30 12:56:56.980662,https://www.undp.org/partners/governments
55418,2024-11-30 13:42:34.954749,https://www.techradar.com/author/john-loeffler/page/4
55419,2024-11-30 14:53:42.155091,https://gamesradar.com
55420,2024-11-30 14:54:05.239469,https://bollywoodhungama.com
55421,2024-11-30 22:32:35.171869,https://omnicalculator.com

Sri_Lanka, history number 2
Last 5 records

,synthetic_time,synthetic_url
54806,2024-11-30 12:30:24.049136,https://samadada.com/karpoora-mullai/
54807,2024-11-30 13:16:02.023223,https://www.digitaltrends.com/home/philips-hue-debuts-its-new-app/
54808,2024-11-30 14:27:09.223565,https://marketscreener.com
54809,2024-11-30 14:27:32.307943,https://bollywoodhungama.com
54810,2024-11-30 22:06:02.240343,https://pennmedicine.org

Sri_Lanka, history number 3
Last 5 records

,synthetic_time,synthetic_url
54189,2024-11-30 12:52:20.330789,https://www.smithsonianmag.com/author/bill-bleyer/
54190,2024-11-30 13:37:58.304876,https://www.digitaltrends.com/mobile/verizon-ellipsis-10-tablet-news/
54191,2024-11-30 14:49:05.505218,https://gamesradar.com
54192,2024-11-30 14:49:28.589596,https://bollywoodhungama.com
54193,2024-11-30 22:27:58.521996,https://sportingnews.com

Sri_Lanka, history number 4
Last 5 records

,synthetic_time,synthetic_url
53576,2024-11-30 13:20:44.991728,https://samadada.com/sita-ramam-songs/
53577,2024-11-30 14:06:22.965815,https://www.digitaltrends.com/home/homes-with-secret-passages/
53578,2024-11-30 15:17:30.166157,https://ef.com
53579,2024-11-30 15:17:53.250535,https://bollywoodhungama.com
53580,2024-11-30 22:56:23.182935,https://omnicalculator.com

Sri_Lanka, history number 5
Last 5 records

,synthetic_time,synthetic_url
52972,2024-11-30 11:53:26.459921,https://everydaypower.com/fountainhead-quotes/
52973,2024-11-30 12:39:04.434008,https://www.udemy.com/course/civil-works-expert-civil3d-level-1/
52974,2024-11-30 13:50:11.634350,https://ef.com
52975,2024-11-30 13:50:34.718728,https://bollywoodhungama.com
52976,2024-11-30 21:29:04.651128,https://deccanherald.com

Sri_Lanka, history number 6
Last 5 records

,synthetic_time,synthetic_url
52359,2024-11-30 11:40:54.457275,https://clipart-library.com/dancers-silhouette.html
52360,2024-11-30 12:26:32.431362,https://www.oracle.com/legal/privacy/privacy-policy.html?rl=1721283108
52361,2024-11-30 13:37:39.631704,https://marketscreener.com
52362,2024-11-30 13:38:02.716082,https://bollywoodhungama.com
52363,2024-11-30 21:16:32.648482,https://pennmedicine.org

Sri_Lanka, history number 7
Last 5 records

,synthetic_time,synthetic_url
51740,2024-11-30 12:23:13.328864,https://clipart-library.com/clipart/6ir5dg54t.htm
51741,2024-11-30 13:08:51.302951,https://www.techtarget.com/whatis/definition/packet-coalescing
51742,2024-11-30 14:19:58.503293,https://gamesradar.com
51743,2024-11-30 14:20:21.587671,https://bollywoodhungama.com
51744,2024-11-30 21:58:51.520071,https://sportingnews.com

Sri_Lanka, history number 8
Last 5 records

,synthetic_time,synthetic_url
51120,2024-11-30 12:07:34.269699,https://samadada.com/theera-kaadhal-songs/
51121,2024-11-30 12:53:12.243786,https://www.samsung.com/latin_en/support/model/qn65qn85bafxza/
51122,2024-11-30 14:04:19.444128,https://gamesradar.com
51123,2024-11-30 14:04:42.528506,https://bollywoodhungama.com
51124,2024-11-30 21:43:12.460906,https://scroll.in

Sri_Lanka, history number 9
Last 5 records

,synthetic_time,synthetic_url
50513,2024-11-30 13:34:01.011957,https://thelawdictionary.org/keogh-act-plan/
50514,2024-11-30 14:19:38.986044,https://www.digitaltrends.com/home/homes-with-secret-passages/
50515,2024-11-30 15:30:46.186386,https://gamesradar.com
50516,2024-11-30 15:31:09.270764,https://bollywoodhungama.com
50517,2024-11-30 23:09:39.203164,https://pennmedicine.org

Sweden, history number 0
Last 5 records

,synthetic_time,synthetic_url
49903,2024-11-30 12:25:35.782101,https://lidingo.se/toppmeny/byggabo
49904,2024-11-30 13:12:46.237591,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
49905,2024-11-30 14:23:53.437933,https://oxfordreference.com
49906,2024-11-30 14:24:16.522311,https://jiosaavn.com
49907,2024-11-30 22:02:46.454711,https://sportskeeda.com

Sweden, history number 1
Last 5 records

,synthetic_time,synthetic_url
49275,2024-11-30 12:52:19.221972,https://lidingo.se/toppmeny/byggabo
49276,2024-11-30 13:39:29.677462,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
49277,2024-11-30 14:50:36.877804,https://gamesradar.com
49278,2024-11-30 14:50:59.962182,https://looper.com
49279,2024-11-30 22:29:29.894582,https://mynewsdesk.com

Sweden, history number 2
Last 5 records

,synthetic_time,synthetic_url
48650,2024-11-30 12:08:44.145983,https://lidingo.se/toppmeny/byggabo
48651,2024-11-30 12:55:54.601473,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
48652,2024-11-30 14:07:01.801815,https://gamesradar.com
48653,2024-11-30 14:07:24.886193,https://looper.com
48654,2024-11-30 21:45:54.818593,https://mynewsdesk.com

Sweden, history number 3
Last 5 records

,synthetic_time,synthetic_url
48024,2024-11-30 11:41:07.131807,https://lidingo.se/toppmeny/byggabo
48025,2024-11-30 12:28:17.587297,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
48026,2024-11-30 13:39:24.787639,https://oxfordreference.com
48027,2024-11-30 13:39:47.872017,https://jiosaavn.com
48028,2024-11-30 21:18:17.804417,https://mynewsdesk.com

Sweden, history number 4
Last 5 records

,synthetic_time,synthetic_url
47389,2024-11-30 11:25:28.002484,https://lidingo.se/toppmeny/byggabo
47390,2024-11-30 12:12:38.457974,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
47391,2024-11-30 13:23:45.658316,https://oxfordreference.com
47392,2024-11-30 13:24:08.742694,https://looper.com
47393,2024-11-30 21:02:38.675094,https://sportskeeda.com

Sweden, history number 5
Last 5 records

,synthetic_time,synthetic_url
46767,2024-11-30 11:39:59.269508,https://lidingo.se/toppmeny/byggabo
46768,2024-11-30 12:27:09.724998,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
46769,2024-11-30 13:38:16.925340,https://oxfordreference.com
46770,2024-11-30 13:38:40.009718,https://looper.com
46771,2024-11-30 21:17:09.942118,https://sportskeeda.com

Sweden, history number 6
Last 5 records

,synthetic_time,synthetic_url
46141,2024-11-30 13:26:35.940052,https://lidingo.se/toppmeny/byggabo
46142,2024-11-30 14:13:46.395542,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
46143,2024-11-30 15:24:53.595884,https://gamesradar.com
46144,2024-11-30 15:25:16.680262,https://jiosaavn.com
46145,2024-11-30 23:03:46.612662,https://mynewsdesk.com

Sweden, history number 7
Last 5 records

,synthetic_time,synthetic_url
45511,2024-11-30 12:02:45.865451,https://lidingo.se/toppmeny/byggabo
45512,2024-11-30 12:49:56.320941,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
45513,2024-11-30 14:01:03.521283,https://oxfordreference.com
45514,2024-11-30 14:01:26.605661,https://jiosaavn.com
45515,2024-11-30 21:39:56.538061,https://sportskeeda.com

Sweden, history number 8
Last 5 records

,synthetic_time,synthetic_url
44883,2024-11-30 12:01:35.397730,https://lidingo.se/toppmeny/byggabo
44884,2024-11-30 12:48:45.853220,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
44885,2024-11-30 13:59:53.053562,https://untappd.com
44886,2024-11-30 14:00:16.137940,https://jiosaavn.com
44887,2024-11-30 21:38:46.070340,https://sportskeeda.com

Sweden, history number 9
Last 5 records

,synthetic_time,synthetic_url
44256,2024-11-30 13:28:17.522849,https://lidingo.se/toppmeny/byggabo
44257,2024-11-30 14:15:27.978339,https://www.spfseniorerna.se/distrikt/sormland/foreningslista/flensbygden/
44258,2024-11-30 15:26:35.178681,https://oxfordreference.com
44259,2024-11-30 15:26:58.263059,https://jiosaavn.com
44260,2024-11-30 23:05:28.195459,https://mynewsdesk.com

Switzerland, history number 0
Last 5 records

,synthetic_time,synthetic_url
43621,2024-11-30 12:06:57.694277,https://www.horgen.ch/trauzimmer
43622,2024-11-30 12:52:35.668364,https://stackoverflow.com/users/1272950/y%c7%9ds%ca%9e%c7%9dla
43623,2024-11-30 14:03:42.868706,https://thieme-connect.com
43624,2024-11-30 14:04:05.953084,https://target.com
43625,2024-11-30 21:42:35.885484,https://sky.it

Switzerland, history number 1
Last 5 records

,synthetic_time,synthetic_url
42999,2024-11-30 13:22:37.114433,https://www.horgen.ch/oeffnungszeiten
43000,2024-11-30 14:08:15.088520,https://stackoverflow.com/users/3864926/bret-van-putten
43001,2024-11-30 15:19:22.288862,https://thieme-connect.com
43002,2024-11-30 15:19:45.373240,https://nike.com
43003,2024-11-30 22:58:15.305640,https://stuttgarter-nachrichten.de

Switzerland, history number 2
Last 5 records

,synthetic_time,synthetic_url
42369,2024-11-30 12:27:28.081863,https://www.horgen.ch/sehenswertesfrei/2924
42370,2024-11-30 13:13:06.055950,https://www.dictionary.com/e/love-adding-emoji-dictionary/
42371,2024-11-30 14:24:13.256292,https://thieme-connect.com
42372,2024-11-30 14:24:36.340670,https://allmusic.com
42373,2024-11-30 22:03:06.273070,https://sportskeeda.com

Switzerland, history number 3
Last 5 records

,synthetic_time,synthetic_url
41741,2024-11-30 13:14:29.058260,https://www.horgen.ch/gesundheitprojekt
41742,2024-11-30 14:00:07.032347,https://stackoverflow.com/users/1786873/leonardo-allievi?tab=tags
41743,2024-11-30 15:11:14.232689,https://thieme-connect.com
41744,2024-11-30 15:11:37.317067,https://allmusic.com
41745,2024-11-30 22:50:07.249467,https://deutschlandfunk.de

Switzerland, history number 4
Last 5 records

,synthetic_time,synthetic_url
41120,2024-11-30 11:25:36.861677,https://www.horgen.ch/alter
41121,2024-11-30 12:11:14.835764,https://stackoverflow.com/help/badges/6/supporter?userid=14602915
41122,2024-11-30 13:22:22.036106,https://shell.com
41123,2024-11-30 13:22:45.120484,https://allmusic.com
41124,2024-11-30 21:01:15.052884,https://srf.ch

Switzerland, history number 5
Last 5 records

,synthetic_time,synthetic_url
40503,2024-11-30 13:27:29.931454,https://www.horgen.ch/zivilstand
40504,2024-11-30 14:13:07.905541,https://stackoverflow.com/help/badges/6/supporter?userid=14602915
40505,2024-11-30 15:24:15.105883,https://investing.com
40506,2024-11-30 15:24:38.190261,https://target.com
40507,2024-11-30 23:03:08.122661,https://capital.fr

Switzerland, history number 6
Last 5 records

,synthetic_time,synthetic_url
39872,2024-11-30 11:39:10.021553,https://www.montreux.ch/sport/sports-dhiver
39873,2024-11-30 12:24:47.995640,https://stackoverflow.com/users/1786873/leonardo-allievi?tab=tags
39874,2024-11-30 13:35:55.195982,https://byjus.com
39875,2024-11-30 13:36:18.280360,https://nike.com
39876,2024-11-30 21:14:48.212760,https://swr.de

Switzerland, history number 7
Last 5 records

,synthetic_time,synthetic_url
39245,2024-11-30 12:29:16.266020,https://www.horgen.ch/zivilstand
39246,2024-11-30 13:14:54.240107,https://stackoverflow.com/users/1272950/y%c7%9ds%ca%9e%c7%9dla
39247,2024-11-30 14:26:01.440449,https://byjus.com
39248,2024-11-30 14:26:24.524827,https://target.com
39249,2024-11-30 22:04:54.457227,https://stuttgarter-nachrichten.de

Switzerland, history number 8
Last 5 records

,synthetic_time,synthetic_url
38614,2024-11-30 13:32:55.740566,https://www.horgen.ch/alter
38615,2024-11-30 14:18:33.714653,https://stackoverflow.com/users/1272950/y%c7%9ds%ca%9e%c7%9dla
38616,2024-11-30 15:29:40.914995,https://shell.com
38617,2024-11-30 15:30:03.999373,https://target.com
38618,2024-11-30 23:08:33.931773,https://uefa.com

Switzerland, history number 9
Last 5 records

,synthetic_time,synthetic_url
37984,2024-11-30 12:13:10.225916,https://www.horgen.ch/gesundheitprojekt
37985,2024-11-30 12:58:48.200003,https://stackoverflow.com/help/badges/6/supporter?userid=14602915
37986,2024-11-30 14:09:55.400345,https://shell.com
37987,2024-11-30 14:10:18.484723,https://target.com
37988,2024-11-30 21:48:48.417123,https://uefa.com

Thailand, history number 0
Last 5 records

,synthetic_time,synthetic_url
37372,2024-11-30 11:24:40.604357,https://www.flash-mini.com/p4214639.world
37373,2024-11-30 12:10:18.578444,https://www.canva.com/hu_hu/help/team-banner-logo/
37374,2024-11-30 13:21:25.778786,https://www.starbucks.com/
37375,2024-11-30 13:21:48.863164,https://mrdiy.com
37376,2024-11-30 21:00:18.795564,https://mgronline.com

Thailand, history number 1
Last 5 records

,synthetic_time,synthetic_url
36756,2024-11-30 12:29:11.852027,https://www.flash-mini.com/p4214639.world
36757,2024-11-30 13:14:49.826114,https://www.canva.com/colors/color-palettes/ice-cold-rose/
36758,2024-11-30 14:25:57.026456,https://tradingview.com
36759,2024-11-30 14:26:20.110834,https://hinovel.com
36760,2024-11-30 22:04:50.043234,https://mgronline.com

Thailand, history number 2
Last 5 records

,synthetic_time,synthetic_url
36126,2024-11-30 13:04:10.225980,https://www.flash-mini.com/2250086.world
36127,2024-11-30 13:49:48.200067,https://www.canva.com/tr_tr/sablonlar/s/nisan/
36128,2024-11-30 15:00:55.400409,https://tradingview.com
36129,2024-11-30 15:01:18.484787,https://chordu.com
36130,2024-11-30 22:39:48.417187,https://mgronline.com

Thailand, history number 3
Last 5 records

,synthetic_time,synthetic_url
35499,2024-11-30 12:01:02.541159,https://www.flash-mini.com/2489782.world
35500,2024-11-30 12:46:40.515246,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
35501,2024-11-30 13:57:47.715588,https://www.starbucks.com/
35502,2024-11-30 13:58:10.799966,https://mrdiy.com
35503,2024-11-30 21:36:40.732366,https://mgronline.com

Thailand, history number 4
Last 5 records

,synthetic_time,synthetic_url
34872,2024-11-30 13:14:05.582277,https://www.flash-mini.com/2423429.world
34873,2024-11-30 13:59:43.556364,https://www.canva.com/pl_pl/help/connect-to-moodle/
34874,2024-11-30 15:10:50.756706,https://starbucks.com
34875,2024-11-30 15:11:13.841084,https://lg.com
34876,2024-11-30 22:49:43.773484,https://mgronline.com

Thailand, history number 5
Last 5 records

,synthetic_time,synthetic_url
34248,2024-11-30 11:48:22.505267,https://www.flash-mini.com/p4208046.world
34249,2024-11-30 12:34:00.479354,https://www.canva.com/colors/color-palettes/camera-ready/
34250,2024-11-30 13:45:07.679696,https://starbucks.com
34251,2024-11-30 13:45:30.764074,https://hinovel.com
34252,2024-11-30 21:24:00.696474,https://mgronline.com

Thailand, history number 6
Last 5 records

,synthetic_time,synthetic_url
33625,2024-11-30 11:45:12.630491,https://www.flash-mini.com/p4241743.world
33626,2024-11-30 12:30:50.604578,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
33627,2024-11-30 13:41:57.804920,https://www.starbucks.com/
33628,2024-11-30 13:42:20.889298,https://mrdiy.com
33629,2024-11-30 21:20:50.821698,https://mgronline.com

Thailand, history number 7
Last 5 records

,synthetic_time,synthetic_url
33002,2024-11-30 11:42:00.790216,https://www.flash-mini.com/2301904.world
33003,2024-11-30 12:27:38.764303,https://www.canva.com/ar_eg/graphs/flowcharts/
33004,2024-11-30 13:38:45.964645,https://tradingview.com
33005,2024-11-30 13:39:09.049023,https://hinovel.com
33006,2024-11-30 21:17:38.981423,https://mgronline.com

Thailand, history number 8
Last 5 records

,synthetic_time,synthetic_url
32380,2024-11-30 12:43:51.163549,https://www.flash-mini.com/874748.world
32381,2024-11-30 13:29:29.137636,https://www.canva.com/it_it/biglietti/modelli/invito/
32382,2024-11-30 14:40:36.337978,https://www.starbucks.com/
32383,2024-11-30 14:40:59.422356,https://hinovel.com
32384,2024-11-30 22:19:29.354756,https://mgronline.com

Thailand, history number 9
Last 5 records

,synthetic_time,synthetic_url
31763,2024-11-30 13:08:29.019869,https://www.flash-mini.com/p4215609.world
31764,2024-11-30 13:54:06.993956,https://www.canva.com/colors/color-palettes/ice-cold-rose/
31765,2024-11-30 15:05:14.194298,https://starbucks.com
31766,2024-11-30 15:05:37.278676,https://hinovel.com
31767,2024-11-30 22:44:07.211076,https://mgronline.com

Turkiye, history number 0
Last 5 records

,synthetic_time,synthetic_url
31135,2024-11-30 13:06:37.824221,https://www.turkhackteam.org/konular/s-a.10701/
31136,2024-11-30 13:53:31.579999,https://www.britannica.com/science/summer-solstice-astronomy
31137,2024-11-30 15:04:38.780341,https://labranda.com
31138,2024-11-30 15:05:01.864719,https://flipkart.com
31139,2024-11-30 22:43:31.797119,https://hepsiburada.com

Turkiye, history number 1
Last 5 records

,synthetic_time,synthetic_url
30505,2024-11-30 12:29:11.701471,https://www.turkhackteam.org/konular/anadolu.8463/
30506,2024-11-30 13:15:36.918425,https://www.britannica.com/biography/frank-morgan-american-actor
30507,2024-11-30 14:26:44.118767,https://labranda.com
30508,2024-11-30 14:27:07.203145,https://flipkart.com
30509,2024-11-30 22:05:37.135545,https://hepsiburada.com

Turkiye, history number 2
Last 5 records

,synthetic_time,synthetic_url
29881,2024-11-30 11:35:22.213349,https://www.turkhackteam.org/konular/s-a.10701/
29882,2024-11-30 12:21:00.187436,https://www.britannica.com/topic/thus-spake-zarathustra
29883,2024-11-30 13:32:07.387778,https://toravilla.com
29884,2024-11-30 13:32:30.472156,https://flipkart.com
29885,2024-11-30 21:11:00.404556,https://hepsiburada.com

Turkiye, history number 3
Last 5 records

,synthetic_time,synthetic_url
29265,2024-11-30 11:24:51.402189,https://www.turkhackteam.org/konular/anadolu.8463/
29266,2024-11-30 12:11:45.157967,https://www.britannica.com/topic/genesis-british-rock-group
29267,2024-11-30 13:22:52.358309,https://labranda.com
29268,2024-11-30 13:23:15.442687,https://flipkart.com
29269,2024-11-30 21:01:45.375087,https://hepsiburada.com

Turkiye, history number 4
Last 5 records

,synthetic_time,synthetic_url
28644,2024-11-30 12:57:33.891941,https://www.turkhackteam.org/konular/s-a.10701/
28645,2024-11-30 13:43:11.866028,https://www.britannica.com/biography/salif-keita-malian-athlete
28646,2024-11-30 14:54:19.066370,https://labranda.com
28647,2024-11-30 14:54:42.150748,https://lg.com
28648,2024-11-30 22:33:12.083148,https://hepsiburada.com

Turkiye, history number 5
Last 5 records

,synthetic_time,synthetic_url
28021,2024-11-30 13:07:50.239415,https://www.turkhackteam.org/konular/anadolu.8463/
28022,2024-11-30 13:53:28.213502,https://www.britannica.com/biography/michal-schwartz
28023,2024-11-30 15:04:35.413844,https://labranda.com
28024,2024-11-30 15:04:58.498222,https://flipkart.com
28025,2024-11-30 22:43:28.430622,https://hepsiburada.com

Turkiye, history number 6
Last 5 records

,synthetic_time,synthetic_url
27400,2024-11-30 13:08:02.185798,https://www.turkhackteam.org/konular/anadolu.8463/
27401,2024-11-30 13:53:40.159885,https://www.britannica.com/place/limerick-county-ireland
27402,2024-11-30 15:04:47.360227,https://toravilla.com
27403,2024-11-30 15:05:10.444605,https://lg.com
27404,2024-11-30 22:43:40.377005,https://hepsiburada.com

Turkiye, history number 7
Last 5 records

,synthetic_time,synthetic_url
26787,2024-11-30 12:48:29.404631,https://www.turkhackteam.org/konular/anadolu.8463/
26788,2024-11-30 13:35:39.860121,https://www.britannica.com/place/thar-desert/additional-info
26789,2024-11-30 14:46:47.060463,https://labranda.com
26790,2024-11-30 14:47:10.144841,https://flipkart.com
26791,2024-11-30 22:25:40.077241,https://hepsiburada.com

Turkiye, history number 8
Last 5 records

,synthetic_time,synthetic_url
26160,2024-11-30 12:47:42.660840,https://www.turkhackteam.org/konular/s-a.10701/
26161,2024-11-30 13:34:07.877794,https://www.britannica.com/topic/senate-united-states-government
26162,2024-11-30 14:45:15.078136,https://labranda.com
26163,2024-11-30 14:45:38.162514,https://flipkart.com
26164,2024-11-30 22:24:08.094914,https://hepsiburada.com

Turkiye, history number 9
Last 5 records

,synthetic_time,synthetic_url
25547,2024-11-30 12:51:24.257929,https://www.turkhackteam.org/konular/s-a.10701/
25548,2024-11-30 13:37:02.232016,https://www.britannica.com/place/thar-desert/additional-info
25549,2024-11-30 14:48:09.432358,https://labranda.com
25550,2024-11-30 14:48:32.516736,https://lg.com
25551,2024-11-30 22:27:02.449136,https://hepsiburada.com

Ukraine, history number 0
Last 5 records

,synthetic_time,synthetic_url
24915,2024-11-30 12:12:25.718872,https://www.rada.info/rada/04377581/
24916,2024-11-30 12:58:03.692959,https://www.britannica.com/biography/frank-morgan-american-actor
24917,2024-11-30 14:09:10.893301,https://autolux.ua
24918,2024-11-30 14:09:33.977679,https://discogs.com
24919,2024-11-30 21:48:03.910079,https://rbc.ua

Ukraine, history number 1
Last 5 records

,synthetic_time,synthetic_url
24306,2024-11-30 13:19:01.019879,https://www.rada.info/rada/04346037/
24307,2024-11-30 14:04:38.993966,https://www.britannica.com/science/pharyngeal-pouch
24308,2024-11-30 15:15:46.194308,https://autolux.ua
24309,2024-11-30 15:16:09.278686,https://discogs.com
24310,2024-11-30 22:54:39.211086,https://www.rbc.ua

Ukraine, history number 2
Last 5 records

,synthetic_time,synthetic_url
23701,2024-11-30 11:36:59.782834,https://www.rada.info/rada/04367364/
23702,2024-11-30 12:22:37.756921,https://www.britannica.com/topic/genesis-british-rock-group
23703,2024-11-30 13:33:44.957263,https://autolux.ua
23704,2024-11-30 13:34:08.041641,https://discogs.com
23705,2024-11-30 21:12:37.974041,https://www.rbc.ua

Ukraine, history number 3
Last 5 records

,synthetic_time,synthetic_url
23100,2024-11-30 13:35:04.320499,https://www.rada.info/rada/04367364/
23101,2024-11-30 14:20:42.294586,https://www.britannica.com/science/pharyngeal-pouch
23102,2024-11-30 15:31:49.494928,https://autolux.ua
23103,2024-11-30 15:32:12.579306,https://discogs.com
23104,2024-11-30 23:10:42.511706,https://www.rbc.ua

Ukraine, history number 4
Last 5 records

,synthetic_time,synthetic_url
22511,2024-11-30 12:38:20.137967,https://www.rada.info/rada/24905562/
22512,2024-11-30 13:23:58.112054,https://www.britannica.com/place/limerick-county-ireland
22513,2024-11-30 14:35:05.312396,https://autolux.ua
22514,2024-11-30 14:35:28.396774,https://discogs.com
22515,2024-11-30 22:13:58.329174,https://www.rbc.ua

Ukraine, history number 5
Last 5 records

,synthetic_time,synthetic_url
21907,2024-11-30 13:14:04.605695,https://www.rada.info/rada/04413118/
21908,2024-11-30 13:59:42.579782,https://www.britannica.com/topic/genesis-british-rock-group
21909,2024-11-30 15:10:49.780124,https://autolux.ua
21910,2024-11-30 15:11:12.864502,https://discogs.com
21911,2024-11-30 22:49:42.796902,https://rbc.ua

Ukraine, history number 6
Last 5 records

,synthetic_time,synthetic_url
21290,2024-11-30 12:51:31.326874,https://www.rada.info/rada/04380146/
21291,2024-11-30 13:37:09.300961,https://www.britannica.com/biography/frank-morgan-american-actor
21292,2024-11-30 14:48:16.501303,https://autolux.ua
21293,2024-11-30 14:48:39.585681,https://discogs.com
21294,2024-11-30 22:27:09.518081,https://www.rbc.ua

Ukraine, history number 7
Last 5 records

,synthetic_time,synthetic_url
20683,2024-11-30 12:05:05.410665,https://www.rada.info/rada/04367364/
20684,2024-11-30 12:50:43.384752,https://www.britannica.com/biography/frank-morgan-american-actor
20685,2024-11-30 14:01:50.585094,https://autolux.ua
20686,2024-11-30 14:02:13.669472,https://discogs.com
20687,2024-11-30 21:40:43.601872,https://www.rbc.ua

Ukraine, history number 8
Last 5 records

,synthetic_time,synthetic_url
20084,2024-11-30 11:33:16.381368,https://www.rada.info/rada/04380146/
20085,2024-11-30 12:18:54.355455,https://www.britannica.com/topic/thus-spake-zarathustra
20086,2024-11-30 13:30:01.555797,https://autolux.ua
20087,2024-11-30 13:30:24.640175,https://discogs.com
20088,2024-11-30 21:08:54.572575,https://www.rbc.ua

Ukraine, history number 9
Last 5 records

,synthetic_time,synthetic_url
19477,2024-11-30 13:33:13.578023,https://www.rada.info/rada/04380146/
19478,2024-11-30 14:18:51.552110,https://www.britannica.com/topic/genesis-british-rock-group
19479,2024-11-30 15:29:58.752452,https://autolux.ua
19480,2024-11-30 15:30:21.836830,https://discogs.com
19481,2024-11-30 23:08:51.769230,https://www.rbc.ua

United_Kingdom, history number 0
Last 5 records

,synthetic_time,synthetic_url
18881,2024-11-30 11:51:49.309586,https://www.getthedata.com/postcode/ta17-8tg
18882,2024-11-30 12:37:27.283673,https://www.hubspot.com/?utm_source=gimmemojo.com&utm_medium=referral
18883,2024-11-30 13:48:34.484015,https://petmd.com
18884,2024-11-30 13:48:57.568393,https://lloydspharmacy.com
18885,2024-11-30 21:27:27.500793,https://sportingnews.com

United_Kingdom, history number 1
Last 5 records

,synthetic_time,synthetic_url
18244,2024-11-30 11:54:35.571152,https://www.getthedata.com/postcode/ba7-7pr
18245,2024-11-30 12:40:13.545239,https://www.samsung.com/africa_en/microwave-ovens/grill/ms32-tas/
18246,2024-11-30 13:51:20.745581,https://lovetoknow.com
18247,2024-11-30 13:51:43.829959,https://littlewoods.com
18248,2024-11-30 21:30:13.762359,https://mentalfloss.com

United_Kingdom, history number 2
Last 5 records

,synthetic_time,synthetic_url
17605,2024-11-30 11:59:26.024098,https://www.getthedata.com/postcode/ta11-7hb
17606,2024-11-30 12:45:03.998185,https://www.digitaltrends.com/movies/10-best-martin-scorsese-movies-ranked/
17607,2024-11-30 13:56:11.198527,https://aafp.org
17608,2024-11-30 13:56:34.282905,https://littlewoods.com
17609,2024-11-30 21:35:04.215305,https://irishmirror.ie

United_Kingdom, history number 3
Last 5 records

,synthetic_time,synthetic_url
16964,2024-11-30 13:30:11.324792,https://www.getthedata.com/postcode/ta11-7hb
16965,2024-11-30 14:15:49.298879,https://www.samsung.com/africa_fr/support/model/cg-a515fzbsmmc/
16966,2024-11-30 15:26:56.499221,https://www.lovetoknow.com
16967,2024-11-30 15:27:19.583599,https://picturehouses.com
16968,2024-11-30 23:05:49.515999,https://heraldscotland.com

United_Kingdom, history number 4
Last 5 records

,synthetic_time,synthetic_url
16324,2024-11-30 12:57:10.325033,https://scotmid.coop/accessibility/
16325,2024-11-30 13:42:48.299120,https://www.hubspot.com/resources/courses/nonprofit
16326,2024-11-30 14:53:55.499462,https://stylecraze.com
16327,2024-11-30 14:54:18.583840,https://lloydspharmacy.com
16328,2024-11-30 22:32:48.516240,https://channel4.com

United_Kingdom, history number 5
Last 5 records

,synthetic_time,synthetic_url
15686,2024-11-30 12:57:22.075805,https://www.getthedata.com/postcode/e1-5lw
15687,2024-11-30 13:43:00.049892,https://www.samsung.com/hk_en/support/model/ef-zg99pcbegew/
15688,2024-11-30 14:54:07.250234,https://www.lovetoknow.com/
15689,2024-11-30 14:54:30.334612,https://picturehouses.com
15690,2024-11-30 22:33:00.267012,https://irishmirror.ie

United_Kingdom, history number 6
Last 5 records

,synthetic_time,synthetic_url
15048,2024-11-30 12:18:49.234380,https://www.getthedata.com/postcode/dy3-2dl
15049,2024-11-30 13:05:14.451334,https://www.hubspot.com/?utm_source=gimmemojo.com&utm_medium=referral
15050,2024-11-30 14:16:21.651676,https://investing.com
15051,2024-11-30 14:16:44.736054,https://atgtickets.com
15052,2024-11-30 21:55:14.668454,https://ladbible.com

United_Kingdom, history number 7
Last 5 records

,synthetic_time,synthetic_url
14407,2024-11-30 13:23:12.828308,https://www.eastofengland.coop/membership
14408,2024-11-30 14:08:50.802395,https://www.samsung.com/latin_en/support/model/sm-g360gzsytpa/
14409,2024-11-30 15:19:58.002737,https://shell.com
14410,2024-11-30 15:20:21.087115,https://lyrics.com
14411,2024-11-30 22:58:51.019515,https://worldatlas.com

United_Kingdom, history number 8
Last 5 records

,synthetic_time,synthetic_url
13764,2024-11-30 11:26:25.208497,https://www.getthedata.com/postcode/ta11-7nn
13765,2024-11-30 12:12:03.182584,https://www.hubspot.com/case-studies/great-minds
13766,2024-11-30 13:23:10.382926,https://visitscotland.com
13767,2024-11-30 13:23:33.467304,https://brewdog.com
13768,2024-11-30 21:02:03.399704,https://channel4.com

United_Kingdom, history number 9
Last 5 records

,synthetic_time,synthetic_url
13129,2024-11-30 12:25:53.266655,https://www.getthedata.com/postcode/ba7-7pr
13130,2024-11-30 13:11:31.240742,https://www.techradar.com/news/wandavision-episode-8-recap-review
13131,2024-11-30 14:22:38.441084,https://bp.com
13132,2024-11-30 14:23:01.525462,https://ents24.com
13133,2024-11-30 22:01:31.457862,https://irishmirror.ie

United_States, history number 0
Last 5 records

,synthetic_time,synthetic_url
12489,2024-11-30 12:39:28.592988,https://www.lincolnparkchamber.com/savor/
12490,2024-11-30 13:25:06.567075,https://www.nps.gov/rocr/learn/management/a-growing-problem.htm
12491,2024-11-30 14:36:13.767417,https://vg247.com
12492,2024-11-30 14:36:36.851795,https://looper.com
12493,2024-11-30 22:15:06.784195,https://upi.com

United_States, history number 1
Last 5 records

,synthetic_time,synthetic_url
11842,2024-11-30 12:11:18.342928,https://www.cityofelmirage.org/336/city-council-goals
11843,2024-11-30 12:56:56.317015,https://www.nps.gov/cajo/planyourvisit/things2do.htm
11844,2024-11-30 14:08:03.517357,https://starbucks.com
11845,2024-11-30 14:08:26.601735,https://looper.com
11846,2024-11-30 21:46:56.534135,https://upi.com

United_States, history number 2
Last 5 records

,synthetic_time,synthetic_url
11198,2024-11-30 11:58:34.270189,https://prescott-az.gov/departments/
11199,2024-11-30 12:44:12.244276,https://www.nps.gov/subjects/citizenscience/get-involved.htm
11200,2024-11-30 13:55:19.444618,https://homeadvisor.com
11201,2024-11-30 13:55:42.528996,https://kingsoopers.com
11202,2024-11-30 21:34:12.461396,https://nbcsports.com

United_States, history number 3
Last 5 records

,synthetic_time,synthetic_url
10556,2024-11-30 11:30:05.602803,https://www.cityofelmirage.org/426/wastewater-services
10557,2024-11-30 12:15:43.576890,https://www.digitaltrends.com/home/amazon-coding-dojo-alexa/
10558,2024-11-30 13:26:50.777232,https://atlasobscura.com
10559,2024-11-30 13:27:13.861610,https://lyrics.com
10560,2024-11-30 21:05:43.794010,https://usmagazine.com

United_States, history number 4
Last 5 records

,synthetic_time,synthetic_url
9912,2024-11-30 12:47:15.223058,https://www.kelso.gov/news/requests-proposals
9913,2024-11-30 13:32:53.197145,https://www.state.gov/report/custom/3f2ba92e51/
9914,2024-11-30 14:44:00.397487,https://amtrak.com
9915,2024-11-30 14:44:23.481865,https://looper.com
9916,2024-11-30 22:22:53.414265,https://pennmedicine.org

United_States, history number 5
Last 5 records

,synthetic_time,synthetic_url
9270,2024-11-30 12:42:58.497978,https://cityofelmirage.org/371/utilities
9271,2024-11-30 13:28:36.472065,https://www.digitaltrends.com/cool-tech/wi-fi-detects-suspicious-items/
9272,2024-11-30 14:39:43.672407,https://vg247.com
9273,2024-11-30 14:40:06.756785,https://lyrics.com
9274,2024-11-30 22:18:36.689185,https://nbcsports.com

United_States, history number 6
Last 5 records

,synthetic_time,synthetic_url
8626,2024-11-30 12:21:04.877648,https://www.cityofelmirage.org/426/wastewater-services
8627,2024-11-30 13:06:42.851735,https://www.state.gov/report/custom/03e090bad3-3/
8628,2024-11-30 14:17:50.052077,https://atlasobscura.com
8629,2024-11-30 14:18:13.136455,https://kingsoopers.com
8630,2024-11-30 21:56:43.068855,https://usmagazine.com

United_States, history number 7
Last 5 records

,synthetic_time,synthetic_url
7983,2024-11-30 11:56:16.781244,https://www.kirklandwa.gov/government
7984,2024-11-30 12:41:54.755331,https://www.state.gov/report/custom/113de4b387/
7985,2024-11-30 13:53:01.955673,https://vg247.com
7986,2024-11-30 13:53:25.040051,https://lyrics.com
7987,2024-11-30 21:31:54.972451,https://pennmedicine.org

United_States, history number 8
Last 5 records

,synthetic_time,synthetic_url
7334,2024-11-30 12:30:15.339802,https://www.cityofelmirage.org/336/city-council-goals
7335,2024-11-30 13:15:53.313889,https://www.state.gov/report/custom/0289093b77/
7336,2024-11-30 14:27:00.514231,https://www.starbucks.com/
7337,2024-11-30 14:27:23.598609,https://lyrics.com
7338,2024-11-30 22:05:53.531009,https://spectrumlocalnews.com

United_States, history number 9
Last 5 records

,synthetic_time,synthetic_url
6695,2024-11-30 11:49:31.240009,https://cityofelmirage.org/171/court-appearances
6696,2024-11-30 12:35:09.214096,https://www.nps.gov/places/000/south-turkey-run-park.htm
6697,2024-11-30 13:46:16.414438,https://atlasobscura.com
6698,2024-11-30 13:46:39.498816,https://lyrics.com
6699,2024-11-30 21:25:09.431216,https://allevents.in

Viet_Nam, history number 0
Last 5 records

,synthetic_time,synthetic_url
6050,2024-11-30 11:42:27.562754,https://www.phunuvagiadinh.vn/3-be-gai-mat-tich.topic
6051,2024-11-30 12:28:05.536841,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
6052,2024-11-30 13:39:12.737183,https://thesinhtourist.vn/
6053,2024-11-30 13:39:35.821561,https://5giay.vn
6054,2024-11-30 21:18:05.753961,https://tuoitre.vn

Viet_Nam, history number 1
Last 5 records

,synthetic_time,synthetic_url
5445,2024-11-30 13:28:53.290889,https://www.phunuvagiadinh.vn/lien-hoa-lau.topic
5446,2024-11-30 14:14:31.264976,https://www.canva.com/nl_nl/sjablonen/s/speurtocht/
5447,2024-11-30 15:25:38.465318,https://tastevietnam.asia
5448,2024-11-30 15:26:01.549696,https://5giay.vn
5449,2024-11-30 23:04:31.482096,https://tuoitre.vn

Viet_Nam, history number 2
Last 5 records

,synthetic_time,synthetic_url
4843,2024-11-30 11:48:42.336979,https://baovephapluat.vn/tim-kiem/q/con-trai
4844,2024-11-30 12:34:20.311066,https://www.canva.com/ar_eg/graphs/flowcharts/
4845,2024-11-30 13:45:27.511408,https://tigitmotorbikes.com
4846,2024-11-30 13:45:50.595786,https://5giay.vn
4847,2024-11-30 21:24:20.528186,https://tuoitre.vn

Viet_Nam, history number 3
Last 5 records

,synthetic_time,synthetic_url
4238,2024-11-30 12:54:28.470212,https://www.phunuvagiadinh.vn/benh-meo-cao.topic
4239,2024-11-30 13:40:06.444299,https://www.canva.com/es_mx/plantillas/s/catalogos/
4240,2024-11-30 14:51:13.644641,https://www.tastevietnam.asia
4241,2024-11-30 14:51:36.729019,https://5giay.vn
4242,2024-11-30 22:30:06.661419,https://tuoitre.vn

Viet_Nam, history number 4
Last 5 records

,synthetic_time,synthetic_url
3633,2024-11-30 13:09:06.979218,https://www.phunuvagiadinh.vn/dam-cuoi-van-hugo.topic
3634,2024-11-30 13:54:44.953305,https://www.canva.com/tr_tr/sablonlar/s/nisan/
3635,2024-11-30 15:05:52.153647,https://getupandgovietnam.com
3636,2024-11-30 15:06:15.238025,https://5giay.vn
3637,2024-11-30 22:44:45.170425,https://tuoitre.vn

Viet_Nam, history number 5
Last 5 records

,synthetic_time,synthetic_url
3023,2024-11-30 11:55:03.085231,https://www.phunuvagiadinh.vn/3-be-gai-mat-tich.topic
3024,2024-11-30 12:40:41.059318,https://www.canva.com/colors/color-palettes/camera-ready/
3025,2024-11-30 13:51:48.259660,https://thesinhtourist.vn/
3026,2024-11-30 13:52:11.344038,https://5giay.vn
3027,2024-11-30 21:30:41.276438,https://tuoitre.vn

Viet_Nam, history number 6
Last 5 records

,synthetic_time,synthetic_url
2417,2024-11-30 12:11:51.683070,https://www.phunuvagiadinh.vn/nu-hoc-sinh.topic
2418,2024-11-30 12:58:16.900024,https://www.canva.com/it_it/biglietti/modelli/invito/
2419,2024-11-30 14:09:24.100366,https://getupandgovietnam.com
2420,2024-11-30 14:09:47.184744,https://5giay.vn
2421,2024-11-30 21:48:17.117144,https://tuoitre.vn

Viet_Nam, history number 7
Last 5 records

,synthetic_time,synthetic_url
1809,2024-11-30 13:31:17.877320,https://www.phunuvagiadinh.vn/3-be-gai-mat-tich.topic
1810,2024-11-30 14:16:55.851407,https://www.canva.com/nl_nl/sjablonen/s/plan-van-aanpak/
1811,2024-11-30 15:28:03.051749,https://tastevietnam.asia
1812,2024-11-30 15:28:26.136127,https://5giay.vn
1813,2024-11-30 23:06:56.068527,https://tuoitre.vn

Viet_Nam, history number 8
Last 5 records

,synthetic_time,synthetic_url
1205,2024-11-30 13:18:57.634070,https://www.phunuvagiadinh.vn/lien-hoa-lau.topic
1206,2024-11-30 14:04:35.608157,https://www.canva.com/photos/mac6dldh0oa-abdominal-massage/
1207,2024-11-30 15:15:42.808499,https://quan-bui.com
1208,2024-11-30 15:16:05.892877,https://5giay.vn
1209,2024-11-30 22:54:35.825277,https://tuoitre.vn

Viet_Nam, history number 9
Last 5 records

,synthetic_time,synthetic_url
593,2024-11-30 12:26:58.480495,https://www.phunuvagiadinh.vn/3-be-gai-mat-tich.topic
594,2024-11-30 13:12:36.454582,https://www.canva.com/pl_pl/help/connect-to-moodle/
595,2024-11-30 14:23:43.654924,https://www.thesinhtourist.vn/
596,2024-11-30 14:24:06.739302,https://5giay.vn
597,2024-11-30 22:02:36.671702,https://tuoitre.vn